#!/bin/bash
# check-embedded-headers-stub.sh — src/embedded_headers.cpp must stay a STUB.
#
# The embedded-header table is a GENERATED file (scripts/gen_embedded_headers.sh
# bakes include/madc/* into a std::map at Makefile parse time). It is generated
# into the per-mode object tree — obj/<mode>/embedded_headers.cpp — and the
# build compiles THAT, never src/embedded_headers.cpp. The committed src/ file
# is a #error stub (a tracked, discoverable path + a loud guard). Committing
# real generated content there is the recurring drift this gate forbids
# (CHANGELOG:1306 — "had silently drifted since 2026-08-21").
#
# The committed file is a valid stub iff it carries the #error guard and none
# of the generated-content markers. The gate self-tests both directions.
#
# See .claude/rules/embedded-headers.md and docs/language/embedded-headers.md.

set -u
cd "$(dirname "$0")/.." || exit 2

TARGET="src/embedded_headers.cpp"

# Returns 0 when $1 is a valid stub, nonzero (with a reason on stderr) otherwise.
is_stub() {
	local f="$1"
	if [ ! -f "$f" ]; then
		echo "  $f: missing" >&2
		return 1
	fi
	if ! grep -q '#error' "$f"; then
		echo "  $f: no #error guard — a bypassed generation would bake an empty table silently" >&2
		return 1
	fi
	# Generated-CODE syntax means real content was committed. These markers
	# are the generated file's own syntax (raw-string header payloads and the
	# map declaration) — chosen so this stub's PROSE, which names the same
	# functions, is not itself flagged.
	if grep -Eq 'R"EMBED\(|std::map<[^>]*>[ \t]*embedded_headers[ \t]*=' "$f"; then
		echo "  $f: carries GENERATED content — commit the #error stub, not the table (it builds into obj/<mode>/embedded_headers.cpp)" >&2
		return 1
	fi
	return 0
}

# --- negative control -------------------------------------------------
ctrl_dir=$(mktemp -d)
trap 'rm -rf "$ctrl_dir"' EXIT

# real generated content (no #error) must FAIL is_stub
cat > "$ctrl_dir/real.cpp" <<'REAL'
// AUTO-GENERATED by scripts/gen_embedded_headers.sh — do not edit
#include <map>
static std::map<std::string, std::string> embedded_headers = { {"stdio.h", R"EMBED(int printf();)EMBED"} };
const std::string *find_embedded_header(const std::string &n){ return nullptr; }
REAL
if is_stub "$ctrl_dir/real.cpp" 2>/dev/null; then
	echo "check-embedded-headers-stub: NEGATIVE CONTROL FAILED — accepted a" >&2
	echo "file full of generated content as a stub; the gate is broken." >&2
	exit 2
fi

# a valid stub must PASS is_stub
cat > "$ctrl_dir/stub.cpp" <<'STUB'
// generated-file stub
#error "regenerate into obj/<mode>/embedded_headers.cpp; run make -C src"
STUB
if ! is_stub "$ctrl_dir/stub.cpp" 2>/dev/null; then
	echo "check-embedded-headers-stub: NEGATIVE CONTROL FAILED — rejected a" >&2
	echo "valid #error stub; the gate is broken." >&2
	exit 2
fi

# --- the real check ---------------------------------------------------
if ! is_stub "$TARGET"; then
	echo "check-embedded-headers-stub: FAIL — $TARGET is not a stub." >&2
	echo "The real table builds into obj/<mode>/embedded_headers.cpp; run" >&2
	echo "'git checkout $TARGET' if a build regenerated it, or restore the" >&2
	echo "#error stub. See .claude/rules/embedded-headers.md." >&2
	exit 1
fi
echo "check-embedded-headers-stub: OK"
exit 0
