#!/bin/bash
# forest_pack.sh — build the standard-header forest container and ship it
# with a madc binary (the release pack step; design doc
# 2026-07-04-forest-default-mode-design.md §7).
#
#   bash scripts/forest_pack.sh [--sidecar] [--image <file>] [bin/madc]
#
# Default (embedded carrier): append the container to the binary itself.
# MUST run AFTER strip: strip rewrites the ELF image and discards appended
# bytes, so strip-after-pack destroys the blob (mandatory ordering).
# Re-packing an already-packed binary appends a new footer; the reader finds
# the LAST one, so correctness holds (the stale blob's bytes are dead weight
# until the next relink).
#
# --sidecar (forest-carriers S3, --with-forest=sidecar): write the container
# as a standalone <image>.forest file beside the image instead — a
# --freeze-append onto an EMPTY file IS a valid standalone container
# (placement 2, container at offset 0; the S1 darwin cross-freeze precedent).
# The runtime discovery chain finds it as a sidecar arm.
#
# --image <file> (forest-carriers S4, --enable-shared): pack a carrier image
# OTHER than the binary — the shared libmadc, whose image the thin CLI and
# every embedding host load, so one container serves them all (discovery arm
# 2). The named binary still does the freezing and the verification; only the
# carrier changes. Same strip-before-pack ordering applies to that image.
#
# Pack failure = build failure (set -e).
set -e
cd "$(dirname "$0")/.."

SIDECAR=0
IMAGE=
while [ $# -gt 0 ]; do
    case "$1" in
	--sidecar) SIDECAR=1; shift ;;
	--image) IMAGE="$2"; shift 2 ;;
	--image=*) IMAGE="${1#--image=}"; shift ;;
	*) break ;;
    esac
done
BIN="${1:-bin/madc}"
IMAGE="${IMAGE:-$BIN}"
LIST=scripts/forest_pack_headers.txt
LEDGER_LIST=scripts/ledger_sources.txt
mkdir -p tmp
TU=tmp/forest_pack_tu.cpp

# AOT ledger (forest-carriers S5): the C-lane madc runtime, compiled by THIS
# madc into MIR modules and packed as one more container segment, so
# -static-libmadc programs carry the machinery inside their own image.
# scripts/ledger_sources.txt is the single owner of the list (src/Makefile
# reads the same file to build these into libmadc).
LEDGER_ARGS=()
while read -r src; do
    LEDGER_ARGS+=("--freeze-ledger=$src")
done < <(grep -vE '^[[:space:]]*(#|$)' "$LEDGER_LIST")

{
    echo "// generated by scripts/forest_pack.sh from $LIST (canonical order)"
    grep -vE '^[[:space:]]*(#|$)' "$LIST" | while read -r h; do
        echo "#include <$h>"
    done
    echo "int main() { return 0; }"
} > "$TU"

# The pack runs a COPY of the binary: Linux forbids writing to a running
# executable (ETXTBSY), and (in embedded mode) the append target IS the
# compiler doing the work.
cp "$BIN" tmp/forest_packer_madc

ulimit -t 900
if [ "$SIDECAR" = 1 ]; then
    OUT="$IMAGE.forest"
    rm -f "$OUT"
    APPEND_TO="$OUT"
elif [ "$IMAGE" = "$BIN" ]; then
    OUT="$IMAGE"
    APPEND_TO="$OUT"
else
    # A carrier image that is not the binary is (in the shared shape) the
    # libmadc the PACKER ITSELF has loaded. Append to a copy and rename it
    # over the image: the running mapping is never written through, and the
    # replacement is atomic.
    OUT="$IMAGE"
    APPEND_TO=tmp/forest_pack_image.bin
    cp -p "$IMAGE" "$APPEND_TO"
fi
timeout 900 tmp/forest_packer_madc --freeze-mir-cache "${LEDGER_ARGS[@]}" --freeze-append="$APPEND_TO" "$TU"
if [ "$APPEND_TO" != "$OUT" ]; then
    mv -f "$APPEND_TO" "$OUT"
fi

# Verify: the container reads back (context-hash pin + directory) and the
# binary still runs the frozen module — the dlsym-heavy smoke that proves
# plain strip kept .dynsym intact. Packing the binary's OWN image verifies
# through the self-image arm (no path: the running executable's blob); every
# other carrier names the container file explicitly.
if [ "$OUT" = "$BIN" ]; then
    timeout 120 "$BIN" --dump-forest > tmp/forest_pack_dump.txt
    timeout 120 "$BIN" --run-frozen
else
    timeout 120 "$BIN" --dump-forest="$OUT" > tmp/forest_pack_dump.txt
    timeout 120 "$BIN" --run-frozen="$OUT"
fi
grep -q '^forest	units=' tmp/forest_pack_dump.txt

# MIR-cache bind-lane equivalence (rung 3, opt-in lane): the packed binary
# compiling a real test with MADC_MIR_CACHE_BIND=1 must (a) actually engage
# the cache lane — a silent fallback would pass every equality check while
# testing nothing — and (b) produce byte-identical output vs the default
# (lane off) run: the blob is DERIVED state, never semantic. The bind reaches
# its container through the DISCOVERY chain, so for a sidecar or a library
# image this doubles as that carrier's arm smoke.
v=$(MADC_MIR_CACHE_BIND=1 timeout 120 "$BIN" -v tests/testfreezerun.mad 2>&1 | tr -d '\0')
grep -aq 'mir cache: bind module staged' <<<"$v"
out_cache=$(MADC_MIR_CACHE_BIND=1 timeout 120 "$BIN" tests/testfreezerun.mad 2>&1)
out_nocache=$(timeout 120 "$BIN" tests/testfreezerun.mad 2>&1)
[ "$out_cache" = "$out_nocache" ]

units=$(grep -c '^unit	' tmp/forest_pack_dump.txt)
if [ "$SIDECAR" = 1 ]; then
    echo "forest_pack: OK ($units units in sidecar $OUT; bind cache == no-cache)"
else
    echo "forest_pack: OK ($units units appended to $OUT; bind cache == no-cache)"
fi
