#!/bin/bash
# forest_pack_windows.sh — freeze the win64 standard-header groves + AOT
# ledger into a madc.exe (windows lane W4; execution decisions in
# docs/plans/2026-08-12-windows-release-lane.md).
#
#   bash scripts/forest_pack_windows.sh [bin/madc-release-x86-64-windows.exe]
#
# The FREEZER is the exe ITSELF, run under wine — the Linux forest_pack.sh
# self-freeze model, not the darwin cross-freezer (wine executes the consumer
# binary on the build container, so producer == consumer and LOADED == parsed
# is exact by construction: identical embedded text, target keys, config
# word). The pack runs a COPY of the exe because a PE image being executed
# cannot be written (the ETXTBSY analogue); the copy lives in tmp/, so it
# needs WINEPATH to reach the runtime DLLs staged beside bin/.
#
# Carrier = PE EOF trailer (the ELF model; probe-verified on real Windows,
# W3.3). MUST run AFTER strip — strip rewrites the PE image and discards
# appended bytes (the same law as the Linux pack).
#
# Every verify leg runs the EXACT shipped bytes under wine: container
# read-back (context-hash pin + directory), ledger presence per selected
# module, --run-frozen, and the MIR-cache bind-lane equivalence smoke.
# Pack failure = build failure (set -e).
set -e
cd "$(dirname "$0")/.."

BIN="${1:-bin/madc-release-x86-64-windows.exe}"
LIST=scripts/forest_pack_headers_windows.txt
GUARDED_LIST=scripts/forest_pack_guarded_windows.txt
LEDGER_LIST=scripts/ledger_sources.txt
WIN_CXX_INCLUDE="${MADC_WIN_CXX_INCLUDE:?missing MinGW libstdc++ include root}"
mkdir -p tmp

if [ ! -f "$BIN" ]; then
    echo "forest_pack_windows: exe '$BIN' not found" >&2
    exit 1
fi

# Wine lane posture: silence winediag chatter (it lands on stderr and would
# poison output comparisons) and let the packer copy in tmp/ bind the
# libstdc++-6/libwinpthread-1/libmadc_rt DLLs staged beside bin/.
export WINEDEBUG=-all
export WINEPATH='Z:\workspace\madc\bin'
WINE="${MADC_WINE:-wine}"

# AOT ledger (forest-carriers S5): the win64-selected C-lane runtime,
# compiled by the exe's OWN c2mir — the modules carry win64-target MIR by
# construction — and packed as one more container segment. This is what
# makes -static-libmadc work on PE: scripts/ledger_sources.txt stays the
# single membership owner.
if ! LEDGER_SOURCES=$(bash scripts/select_ledger_sources.sh win64 "$LEDGER_LIST"); then
    echo "forest_pack_windows: could not select win64 ledger sources" >&2
    exit 1
fi
LEDGER_ARGS=()
while IFS= read -r src; do
    [ -n "$src" ] || continue
    LEDGER_ARGS+=("--freeze-ledger=$src")
done <<<"$LEDGER_SOURCES"
LEDGER_MODULE_COUNT=${#LEDGER_ARGS[@]}

TU=tmp/forest_pack_tu_win.cpp
{
    echo "// generated by scripts/forest_pack_windows.sh from $LIST (canonical order)"
    grep -vE '^[[:space:]]*(#|$)' "$LIST" | while read -r h; do
        echo "#include <$h>"
    done
    # A default-standard preprocess cannot discover these C++20-guarded
    # edges. Absolute roots preserve their canonical sysroot names while
    # their guarded bodies stay semantically empty in this profile; v41 still
    # records the exact raw text for live C++20 re-tokenization.
    grep -vE '^[[:space:]]*(#|$)' "$GUARDED_LIST" | while read -r h; do
        echo "#include \"$WIN_CXX_INCLUDE/$h\""
    done
    echo "int main() { return 0; }"
} > "$TU"

# The pack runs a COPY of the exe (see header). The .exe suffix matters to
# wine's loader.
cp -p "$BIN" tmp/forest_packer_madc.exe

ulimit -t 1800
# ONE STDLIB FLAVOR PER SHIPPED ARTIFACT (owner policy 2026-08-16): Linux and
# Windows products carry libstdc++, macOS carries libc++, and no product
# carries both. The flavor a pack embeds is a property of the TARGET, not of
# what the build host happens to have installed — a host-capability probe put
# the container's own /usr/include/c++/v1 headers inside a Windows PE, where
# no libc++ runtime exists to resolve them and only wine's Z:\ mapping made it
# look serviceable. So this pack appends exactly one profile: the MinGW build
# default. `-stdlib=` remains a compile-time choice on a host that has both
# installed; it is not a licence to ship both corpora in one binary.
# verify_pe_release.sh gates the shipped artifact against a second profile.

# --no-config for the same reason as the native pack: an ambient madc.ini
# must never change the frozen corpus's producer config. The wall cap is
# wider than the Linux pack's — the freeze pays the wine translation tax.
#
# Captured for the degradation gate (task #63) — see scripts/forest_pack.sh for
# why this is redirect-then-cat and never `| tee`.
PACK_LOG=tmp/forest_pack_win_freeze.log
if ! timeout 1800 "$WINE" tmp/forest_packer_madc.exe --no-config --freeze-mir-cache "${LEDGER_ARGS[@]}" --freeze-append="$BIN" "$TU" > "$PACK_LOG" 2>&1; then
    cat "$PACK_LOG"
    echo "forest_pack_windows: FAILED - freeze-append exited nonzero" >&2
    exit 1
fi
cat "$PACK_LOG"

# Verify through the PACKED exe itself (self-image arm: the running
# executable's own trailer). Wine's CRT writes CRLF: the greps below are
# prefix/substring matches, never $-anchored, so the \r before each newline
# is inert — do not add $ anchors here.
timeout 300 "$WINE" "$BIN" --dump-forest > tmp/forest_pack_win_dump.txt
timeout 300 "$WINE" "$BIN" --run-frozen
if ! grep -q '^forest	units=' tmp/forest_pack_win_dump.txt; then
    echo "forest_pack_windows: FAILED - packed exe has no forest directory" >&2
    exit 1
fi
if ! grep -q "^ledger	modules=$LEDGER_MODULE_COUNT	symbols=" tmp/forest_pack_win_dump.txt; then
    echo "forest_pack_windows: FAILED - expected $LEDGER_MODULE_COUNT selected ledger modules" >&2
    if ! grep -a '^ledger' tmp/forest_pack_win_dump.txt >&2; then
        echo "forest_pack_windows: dump has no ledger record" >&2
    fi
    exit 1
fi
while IFS= read -r src; do
    [ -n "$src" ] || continue
    LEDGER_MODULE_PREFIX=$'ledgermod\t'"$src"$'\t'
    if ! grep -Fq "$LEDGER_MODULE_PREFIX" tmp/forest_pack_win_dump.txt; then
        echo "forest_pack_windows: FAILED - selected ledger module is missing: $src" >&2
        exit 1
    fi
done <<<"$LEDGER_SOURCES"
# Every listed entry point must be a directory unit — a missing unit means a
# consumer's #include of that name silently live-parses (the G2 class), and
# on a run-only Windows box live parse cannot succeed at all.
unit_present() {
    grep -Eq "^unit	[0-9]+	([^	]*/)?$1	" tmp/forest_pack_win_dump.txt
}
missing=0
while IFS= read -r h; do
    [ -n "$h" ] || continue
    if ! unit_present "$h"; then
        echo "forest_pack_windows: MISSING unit for <$h>" >&2
        missing=1
    fi
done < <(grep -vE '^[[:space:]]*(#|$)' "$LIST")
# The guarded roots are not public entry points, but their raw source must be
# in the same default-flavor profile selected by a C++20 live fallback.
while IFS= read -r guarded; do
    [ -n "$guarded" ] || continue
    guarded_pattern=$'^unit\t[0-9]+\t.*'"$guarded"$'\t'
    if ! grep -Eq "$guarded_pattern" tmp/forest_pack_win_dump.txt; then
        echo "forest_pack_windows: MISSING guarded source unit: $guarded" >&2
        missing=1
    fi
done < <(grep -vE '^[[:space:]]*(#|$)' "$GUARDED_LIST")
if [ "$missing" -ne 0 ]; then
    echo "forest_pack_windows: FAILED - see missing units above" >&2
    exit 1
fi

# Default-lane product smoke: the PACKED exe compiles and runs a real
# C++ test through its forest-served include world, byte-correct.
out_frozen=$(timeout 300 "$WINE" "$BIN" tests/testfreezerun.mad 2>&1 | tr -d '\r')
grep -q 'sum=55 count=5' <<<"$out_frozen"
grep -q 'list=1,4,9,16,25' <<<"$out_frozen"

# The Linux pack's rung-3 MIR-cache bind-equivalence leg is DELIBERATELY
# absent here: the opt-in MADC_MIR_CACHE_BIND=1 lane crashes on win64
# (EXCEPTION_ILLEGAL_INSTRUCTION in a JIT frame right after the cache
# trap prebind — task #55 has the reducer and the layer chain). The lane
# is default-off, so the shipped artifact's default path is unaffected
# and verified above + by the packed suite lanes. Restore the
# equivalence leg (forest_pack.sh's shape) when #55 is fixed.

# Degradation gate (task #63) — producer ratchet + consumer hard zero, the
# same two halves as the Linux pack. The load probe is its own -v run of the
# shipped exe (the smoke above compares OUTPUT, which a degraded bind can still
# get right); the wall cap is wider than Linux's because every line of the -v
# trace pays the wine translation tax.
LOAD_LOG=tmp/forest_pack_win_load.log
timeout 900 "$WINE" "$BIN" -v tests/testfreezerun.mad > "$LOAD_LOG" 2>&1
bash scripts/forest_pack_gate.sh --profile win64 --pack-log "$PACK_LOG" --load-log "$LOAD_LOG"

units=$(grep -c '^unit	' tmp/forest_pack_win_dump.txt)
echo "forest_pack_windows: OK (1 profile, $units units appended to $BIN; product smokes green)"
