#!/bin/bash
# forest_dm_oracle.sh — PP parity ratchet for the packed header closure
# (B4a; design doc 2026-07-04-forest-default-mode-design.md §7).
#
# Compares the SET OF MACRO NAMES the packed headers define under madc's PP
# (madc -dM, minus the empty-TU predefine baseline) against g++'s
# (g++ -dM -E, likewise). The two PPs are not expected to be identical today
# — the KNOWN divergence lives in scripts/forest_dm_baseline.txt — but any
# NEW divergence fails: the pack's macro surface must never silently drift.
# Shrinking the baseline is the improvement direction (each gcc-only entry
# is a header-branch madc's PP doesn't take yet). Regenerate with
#   bash scripts/forest_dm_oracle.sh --rebaseline
# and review the diff like any other ratchet move.
set -e
cd "$(dirname "$0")/.."

BIN="${1:-bin/madc}"
[ "$1" = "--rebaseline" ] && { REBASE=1; BIN="${2:-bin/madc}"; } || REBASE=0
LIST=scripts/forest_pack_headers.txt
BASE=scripts/forest_dm_baseline.txt
mkdir -p tmp
TU=tmp/forest_dm_tu.cpp

{
    grep -vE '^[[:space:]]*(#|$)' "$LIST" | while read -r h; do
        echo "#include <$h>"
    done
    echo "int main() { return 0; }"
} > "$TU"
echo 'int main() { return 0; }' > tmp/forest_dm_empty.cpp

names() { awk '{print $2}' | sed 's/(.*//' | sort -u; }

ulimit -t 900
timeout 600 "$BIN" -dM "$TU" 2>/dev/null | names > tmp/forest_dm_madc_full.txt
timeout 120 "$BIN" -dM tmp/forest_dm_empty.cpp 2>/dev/null | names > tmp/forest_dm_madc_base.txt
comm -23 tmp/forest_dm_madc_full.txt tmp/forest_dm_madc_base.txt > tmp/forest_dm_madc.txt
timeout 600 g++ -dM -E -x c++ "$TU" 2>/dev/null | names > tmp/forest_dm_gcc_full.txt
timeout 120 g++ -dM -E -x c++ tmp/forest_dm_empty.cpp 2>/dev/null | names > tmp/forest_dm_gcc_base.txt
comm -23 tmp/forest_dm_gcc_full.txt tmp/forest_dm_gcc_base.txt > tmp/forest_dm_gcc.txt

{
    comm -23 tmp/forest_dm_madc.txt tmp/forest_dm_gcc.txt | sed 's/^/madc-only\t/'
    comm -13 tmp/forest_dm_madc.txt tmp/forest_dm_gcc.txt | sed 's/^/gcc-only\t/'
} | sort > tmp/forest_dm_diff.txt

if [ "$REBASE" = 1 ]; then
    { echo "# forest_dm_baseline.txt — KNOWN madc-vs-g++ macro-name divergence for"
      echo "# the packed closure (see scripts/forest_dm_oracle.sh). Generated by"
      echo "# --rebaseline; review every change. gcc-only = header branches madc's"
      echo "# PP doesn't take yet; madc-only = madc-implementation macros."
      cat tmp/forest_dm_diff.txt
    } > "$BASE"
    echo "forest_dm_oracle: baseline rewritten ($(grep -vc '^#' "$BASE") lines)"
    exit 0
fi

grep -vE '^[[:space:]]*(#|$)' "$BASE" | sort > tmp/forest_dm_base_known.txt
comm -23 tmp/forest_dm_diff.txt tmp/forest_dm_base_known.txt > tmp/forest_dm_new.txt

if [ -s tmp/forest_dm_new.txt ]; then
    echo "forest_dm_oracle: FAIL — NEW macro-surface divergence vs g++:"
    cat tmp/forest_dm_new.txt
    exit 1
fi
RESOLVED=$(comm -13 tmp/forest_dm_diff.txt tmp/forest_dm_base_known.txt | wc -l)
echo "forest_dm_oracle: OK ($(wc -l < tmp/forest_dm_diff.txt) known divergences, $RESOLVED baseline entries now resolved — rebaseline to ratchet down)"
