#!/bin/bash
# forest_pack.sh — build the standard-header forest container and append it
# to a madc binary (the release pack step; design doc
# 2026-07-04-forest-default-mode-design.md §7).
#
#   bash scripts/forest_pack.sh [bin/madc]
#
# MUST run AFTER strip: strip rewrites the ELF image and discards appended
# bytes, so strip-after-pack destroys the blob (mandatory ordering).
# Pack failure = build failure (set -e). Re-packing an already-packed binary
# appends a new footer; the reader finds the LAST one, so correctness holds
# (the stale blob's bytes are dead weight until the next relink).
set -e
cd "$(dirname "$0")/.."

BIN="${1:-bin/madc}"
LIST=scripts/forest_pack_headers.txt
mkdir -p tmp
TU=tmp/forest_pack_tu.cpp

{
    echo "// generated by scripts/forest_pack.sh from $LIST (canonical order)"
    grep -vE '^[[:space:]]*(#|$)' "$LIST" | while read -r h; do
        echo "#include <$h>"
    done
    echo "int main() { return 0; }"
} > "$TU"

# The pack runs a COPY of the binary: Linux forbids writing to a running
# executable (ETXTBSY), and the append target IS the compiler doing the work.
cp "$BIN" tmp/forest_packer_madc

ulimit -t 900
timeout 900 tmp/forest_packer_madc --freeze-mir-cache --freeze-append="$BIN" "$TU"

# Verify: the blob reads back from the packed binary itself (context-hash pin
# + directory), and the stripped+appended binary still runs a frozen module —
# the dlsym-heavy smoke that proves plain strip kept .dynsym intact.
timeout 120 "$BIN" --dump-forest > tmp/forest_pack_dump.txt
grep -q '^forest	units=' tmp/forest_pack_dump.txt
timeout 120 "$BIN" --run-frozen

# MIR-cache bind-lane equivalence (rung 3): the packed binary compiling a real
# test must (a) actually engage the cache lane — a silent fallback would pass
# every equality check while testing nothing — and (b) produce byte-identical
# output with the lane disabled (the blob is DERIVED state, never semantic).
timeout 120 "$BIN" -v tests/testfreezerun.mad 2>/dev/null \
    | grep -aq 'mir cache: bind module staged'
out_cache=$(timeout 120 "$BIN" tests/testfreezerun.mad 2>&1)
out_nocache=$(MADC_NO_MIR_CACHE=1 timeout 120 "$BIN" tests/testfreezerun.mad 2>&1)
[ "$out_cache" = "$out_nocache" ]

echo "forest_pack: OK ($(grep -c '^unit	' tmp/forest_pack_dump.txt) units appended to $BIN; bind cache == no-cache)"
