#!/bin/bash
# forest_pack_darwin.sh — cross-freeze the darwin standard-header groves into
# a standalone forest container for the hosted-*-macos binaries
# (forest-carriers plan S1, docs/plans/2026-07-25-forest-carriers-plan.md).
#
#   bash scripts/forest_pack_darwin.sh <cross-madc> <prelude-manifest> <out.bin>
#
# The FREEZER is the Linux-hosted cross madc for the same Apple target
# (bin/madc-{arm64,x86-64}-macos): it embeds the identical darwin prelude
# text the hosted binary carries and parses with the target's type facts,
# so LOADED == parsed holds across the cross-freeze (same source tree, same
# embedded text, same target keys -> same context hash + config word).
#
# The container is written as a STANDALONE file and embedded at hosted link
# time via -Wl,-sectcreate,__MADC,__forest (src/Makefile hosted MODEs): lld
# computes the ad-hoc code signature AFTER section layout, so the build path
# needs no re-signer. Appended blobs are ILLEGAL on signed Mach-O (the file
# must end exactly at the signature) — the section is the darwin carrier.
#
# --freeze-append onto an EMPTY file: placement 2 selects the release-pack
# compression profile (zstd level 15 + compressed intern spine — the same
# trade the Linux release pack ships); with nothing to append to, the
# container starts at offset 0 and the file IS a valid standalone container
# (footer at EOF), exactly what -sectcreate expects.
#
# All paths are caller-relative (no cd): the Makefile invokes this from src/
# with ../-relative arguments.
set -e

CROSS="$1"
MANIFEST="$2"
OUT="$3"

if [ -z "$CROSS" ] || [ -z "$MANIFEST" ] || [ -z "$OUT" ]; then
    echo "usage: $0 <cross-madc> <prelude-manifest> <out.bin>" >&2
    exit 2
fi
if [ ! -x "$CROSS" ]; then
    echo "Error: cross madc '$CROSS' not found/executable" >&2
    exit 1
fi
if [ ! -f "$MANIFEST" ]; then
    echo "Error: prelude manifest '$MANIFEST' not found" >&2
    exit 1
fi

# AOT ledger (forest-carriers S5): the SAME C-lane runtime sources, compiled
# by THIS cross madc — so the modules carry darwin-target MIR — and packed as
# one more container segment. This is what makes -static-libmadc work on
# Mach-O at all: there is no libmadc dylib to fall back to, so a hosted madc
# whose container has no ledger can never emit a try/catch program.
# scripts/ledger_sources.txt is the single owner of the tagged list.
LEDGER_LIST="$(dirname "$0")/ledger_sources.txt"
LEDGER_ROOT="$(dirname "$0")/.."
if ! LEDGER_SOURCES=$(bash "$(dirname "$0")/select_ledger_sources.sh" darwin "$LEDGER_LIST"); then
    echo "forest_pack_darwin: could not select Darwin ledger sources" >&2
    exit 1
fi
LEDGER_ARGS=()
while IFS= read -r src; do
    [ -n "$src" ] || continue
    LEDGER_ARGS+=("--freeze-ledger=$LEDGER_ROOT/$src")
done <<<"$LEDGER_SOURCES"
LEDGER_MODULE_COUNT=${#LEDGER_ARGS[@]}

# The C++ grove set (macos-release-lane plan W1): the darwin canonical-order
# list, frozen from LLVM's libc++ behind the prelude's C names. One combined
# TU keeps a single frozen context (the C++ headers reach the C world through
# libc++'s include_next wrappers, which must land on the SAME prelude units).
CXXLIST="$(dirname "$0")/forest_pack_headers_darwin.txt"
CXXNAMES=$(grep -vE '^[[:space:]]*(#|$)' "$CXXLIST")

TU="$OUT.tu.cpp"
{
    echo "// generated by scripts/forest_pack_darwin.sh from $MANIFEST + $(basename "$CXXLIST") (canonical order)"
    while IFS= read -r h; do
        [ -n "$h" ] || continue
        echo "#include <$h>"
    done < "$MANIFEST"
    for h in $CXXNAMES; do
        echo "#include <$h>"
    done
    echo "int main() { return 0; }"
} > "$TU"

: > "$OUT"
ulimit -t 900
# --no-config for the same reason as the native pack: an ambient madc.ini must
# never change the frozen corpus's producer config (see scripts/forest_pack.sh).
#
# Captured for the degradation gate (task #63) — see scripts/forest_pack.sh for
# why this is redirect-then-cat and never `| tee`. The log lands beside the
# container (a build product, caller-relative like every path here).
PACK_LOG="$OUT.freeze.log"
if ! timeout 900 "$CROSS" --no-config --freeze-mir-cache "${LEDGER_ARGS[@]}" --freeze-append="$OUT" "$TU" > "$PACK_LOG" 2>&1; then
    cat "$PACK_LOG"
    echo "forest_pack_darwin: FAILED - freeze-append exited nonzero" >&2
    exit 1
fi
cat "$PACK_LOG"

# Verify: the container reads back (context-hash pin + directory), and every
# manifest name is a directory unit — a missing stub unit means a consumer's
# #include of that name would silently live-parse (the G2 silent-degradation
# class this gate exists to catch).
DUMP="$OUT.dump.txt"
timeout 120 "$CROSS" --dump-forest="$OUT" > "$DUMP"
if ! grep -q '^forest	units=' "$DUMP"; then
    rm -f "$OUT"
    echo "forest_pack_darwin: FAILED - packed image has no forest directory" >&2
    exit 1
fi
# The exact selected ledger must be THERE: a hosted darwin madc without it
# cannot emit a runtime-needing program at all (no dylib fallback exists on
# Mach-O), and accepting merely "some ledger" hides target-selection loss.
if ! grep -q "^ledger	modules=$LEDGER_MODULE_COUNT	symbols=" "$DUMP"; then
    rm -f "$OUT"
    echo "forest_pack_darwin: FAILED - expected $LEDGER_MODULE_COUNT selected ledger modules" >&2
    if ! grep -a '^ledger' "$DUMP" >&2; then
        echo "forest_pack_darwin: dump has no ledger record" >&2
    fi
    exit 1
fi
while IFS= read -r src; do
    [ -n "$src" ] || continue
    LEDGER_MODULE_PATH=$LEDGER_ROOT/$src
    LEDGER_MODULE_PREFIX=$'ledgermod\t'"$LEDGER_MODULE_PATH"$'\t'
    if ! grep -Fq "$LEDGER_MODULE_PREFIX" "$DUMP"; then
        rm -f "$OUT"
        echo "forest_pack_darwin: FAILED - selected ledger module is missing: $LEDGER_MODULE_PATH" >&2
        exit 1
    fi
done <<<"$LEDGER_SOURCES"
# A unit is named by its bare spelling (embedded headers) OR by the
# producer's full path (filesystem headers — the C++ groves); consumers
# match the latter by path tail (find_unit_path_tail), so the gate accepts
# either form.
unit_present() {
    grep -Eq "^unit	[0-9]+	([^	]*/)?$1	" "$DUMP"
}
missing=0
while IFS= read -r h; do
    [ -n "$h" ] || continue
    if ! unit_present "$h"; then
        echo "forest_pack_darwin: MISSING unit for <$h>" >&2
        missing=1
    fi
done < "$MANIFEST"
for h in $CXXNAMES; do
    if ! unit_present "$h"; then
        echo "forest_pack_darwin: MISSING unit for <$h>" >&2
        missing=1
    fi
done
if [ "$missing" -ne 0 ]; then
    rm -f "$OUT"
    echo "forest_pack_darwin: FAILED — container dropped (see missing units above)" >&2
    exit 1
fi

# Degradation gate (task #63) — the PRODUCER half only. Both arches check
# against the same `darwin pack-errors` key, each on its own log, so a
# divergence between them still fails loudly (58 apiece today).
#
# There is no --load-log here, and that is structural, not an omission: this is
# a CROSS freeze, so the build container cannot execute the consumer that would
# materialize the container. Darwin's consumer half runs where the artifact
# runs — scripts/mac_battery.sh's forest-degradation leg, on a Mac, against the
# exact shipped binary. That is the same split task #60 (the macOS headerless
# cell) exists to close.
bash "$(dirname "$0")/forest_pack_gate.sh" --profile darwin --pack-log "$PACK_LOG"

echo "forest_pack_darwin: OK ($(grep -c '^unit	' "$DUMP") units in $OUT for $(basename "$CROSS"))"
