#!/bin/bash
# forest_pack_darwin.sh — cross-freeze the darwin standard-header groves into
# a standalone forest container for the hosted-*-macos binaries
# (forest-carriers plan S1, docs/plans/2026-07-25-forest-carriers-plan.md).
#
#   bash scripts/forest_pack_darwin.sh <cross-madc> <prelude-manifest> <out.bin>
#
# The FREEZER is the Linux-hosted cross madc for the same Apple target
# (bin/madc-{arm64,x86-64}-macos): it embeds the identical darwin prelude
# text the hosted binary carries and parses with the target's type facts,
# so LOADED == parsed holds across the cross-freeze (same source tree, same
# embedded text, same target keys -> same context hash + config word).
#
# The container is written as a STANDALONE file and embedded at hosted link
# time via -Wl,-sectcreate,__MADC,__forest (src/Makefile hosted MODEs): lld
# computes the ad-hoc code signature AFTER section layout, so the build path
# needs no re-signer. Appended blobs are ILLEGAL on signed Mach-O (the file
# must end exactly at the signature) — the section is the darwin carrier.
#
# --freeze-append onto an EMPTY file: placement 2 selects the release-pack
# compression profile (zstd level 15 + compressed intern spine — the same
# trade the Linux release pack ships); with nothing to append to, the
# container starts at offset 0 and the file IS a valid standalone container
# (footer at EOF), exactly what -sectcreate expects.
#
# All paths are caller-relative (no cd): the Makefile invokes this from src/
# with ../-relative arguments.
set -e

CROSS="$1"
MANIFEST="$2"
OUT="$3"

if [ -z "$CROSS" ] || [ -z "$MANIFEST" ] || [ -z "$OUT" ]; then
    echo "usage: $0 <cross-madc> <prelude-manifest> <out.bin>" >&2
    exit 2
fi
if [ ! -x "$CROSS" ]; then
    echo "Error: cross madc '$CROSS' not found/executable" >&2
    exit 1
fi
if [ ! -f "$MANIFEST" ]; then
    echo "Error: prelude manifest '$MANIFEST' not found" >&2
    exit 1
fi

TU="$OUT.tu.c"
{
    echo "// generated by scripts/forest_pack_darwin.sh from $MANIFEST (canonical order)"
    while IFS= read -r h; do
        [ -n "$h" ] || continue
        echo "#include <$h>"
    done < "$MANIFEST"
    echo "int main() { return 0; }"
} > "$TU"

: > "$OUT"
ulimit -t 900
timeout 900 "$CROSS" --freeze-mir-cache --freeze-append="$OUT" "$TU"

# Verify: the container reads back (context-hash pin + directory), and every
# manifest name is a directory unit — a missing stub unit means a consumer's
# #include of that name would silently live-parse (the G2 silent-degradation
# class this gate exists to catch).
DUMP="$OUT.dump.txt"
timeout 120 "$CROSS" --dump-forest="$OUT" > "$DUMP"
grep -q '^forest	units=' "$DUMP"
missing=0
while IFS= read -r h; do
    [ -n "$h" ] || continue
    if ! grep -q "^unit	[0-9]*	$h	" "$DUMP"; then
        echo "forest_pack_darwin: MISSING unit for <$h>" >&2
        missing=1
    fi
done < "$MANIFEST"
if [ "$missing" -ne 0 ]; then
    rm -f "$OUT"
    echo "forest_pack_darwin: FAILED — container dropped (see missing units above)" >&2
    exit 1
fi

echo "forest_pack_darwin: OK ($(grep -c '^unit	' "$DUMP") units in $OUT for $(basename "$CROSS"))"
