#!/bin/bash
# Generate src/predefined_macros.cpp — the host compiler's predefined macros
# (`<CXX> -dM -E`), so madc presents the SAME predefined-macro environment the
# toolchain does. Real system headers branch heavily on these (__STDC_HOSTED__,
# __cplusplus, __SIZEOF_*, __*_TYPE__, feature-test macros, …).
#
# Emits two C arrays (object-like and function-like); the lexer seeds them into
# define_map / macro_map at init. Programmatic seeding (NOT source #defines) —
# feeding 460 #define lines through the lexer breaks on the macro bodies.
#
# Host/std-specific: gitignored, regenerated each build; `make clean` refreshes.
set -u

CXX="${CXX:-c++}"
STD="${MADC_PREDEF_STD:-c++17}"
OUT="$(dirname "$0")/../src/predefined_macros.cpp"

# GCC posture (MADC_PREDEF_GCC_POSTURE=<gnuc version, e.g. 13.3.0>): drop the
# __clang__/__llvm__ identity macros and present the given GCC version, so the
# headers madc SERVES take their GCC branches — the posture every host lane
# already runs (the host tables come from g++), under which libc++ keys off
# __GCC_ATOMIC_* instead of __has_feature probes and disables the clang-only
# availability-annotation machinery. Used by the Apple-target modes, whose
# capture compiler is necessarily clang (only clang cross-targets darwin) but
# whose served posture must match what madc actually implements. The version
# floor matters: libc++ rejects _LIBCPP_COMPILER_GCC older than its support
# window, and clang's compat value is a fictional GCC 4.
POSTURE="${MADC_PREDEF_GCC_POSTURE:-}"
posture_filter() {
    # ONE filter, shared with gen_darwin_prelude.sh (whose flattened output
    # keeps clang's identity #defines and would re-poison the posture).
    "$(dirname "$0")/gcc_posture_filter.sh" "$POSTURE"
}

# $CXX is word-split on purpose: cross toolchains are multi-word commands.
$CXX -dM -E -std="$STD" -x c++ /dev/null 2>/dev/null | posture_filter | awk '
function esc(s) { gsub(/\\/, "\\\\", s); gsub(/"/, "\\\"", s); return s }
BEGIN {
    print "// AUTO-GENERATED by scripts/gen_predefined_macros.sh — DO NOT EDIT/COMMIT."
    print "struct MadcPredefObj  { const char *name; const char *value; };"
    print "struct MadcPredefFunc { const char *name; const char *params; const char *body; };"
    obj = "const MadcPredefObj madc_predefined_obj[] = {\n"
    fn  = "const MadcPredefFunc madc_predefined_func[] = {\n"
}
/^#define / {
    rest = substr($0, 9)                         # strip "#define "
    # function-like iff "(" immediately follows the name (no space before it)
    sp = index(rest, " ")
    par = index(rest, "(")
    if (par > 0 && (sp == 0 || par < sp)) {
        name = substr(rest, 1, par - 1)
        close_par = index(rest, ")")
        params = substr(rest, par + 1, close_par - par - 1)
        body = substr(rest, close_par + 1)
        sub(/^ /, "", body)
        fn = fn "    {\"" esc(name) "\", \"" esc(params) "\", \"" esc(body) "\"},\n"
    } else {
        if (sp == 0) { name = rest; val = "" }
        else { name = substr(rest, 1, sp - 1); val = substr(rest, sp + 1) }
        obj = obj "    {\"" esc(name) "\", \"" esc(val) "\"},\n"
    }
}
END {
    print obj "    {(const char *)0, (const char *)0}\n};"
    print fn  "    {(const char *)0, (const char *)0, (const char *)0}\n};"
    # Accessor functions (not direct extern data refs) so the lexer reaches the
    # arrays via a PLT-resolved call — avoids text relocations in the PIE binary
    # (same pattern as embedded_headers.cpp / find_embedded_header).
    print "const MadcPredefObj  *madc_predefined_objects()  { return madc_predefined_obj; }"
    print "const MadcPredefFunc *madc_predefined_functions() { return madc_predefined_func; }"
}
' > "$OUT.tmp"

# A near-empty capture means the compiler probe or the filter pipeline
# FAILED (a real -dM table has hundreds of entries) — installing it would
# silently strip every predefined macro from the built madc (the exact G2
# silent-degradation class; a non-executable filter script did precisely
# this once). Keep the previous table and fail loudly instead.
if [ "$(grep -c '{"' "$OUT.tmp")" -lt 50 ]; then
    rm -f "$OUT.tmp"
    echo "gen_predefined_macros: capture came back (near) empty — refusing to install" >&2
    exit 1
fi

# Idempotent write: rewrite only on real content change, so the parse-time
# regeneration in src/Makefile never churns mtimes / forces rebuilds.
if cmp -s "$OUT.tmp" "$OUT" 2>/dev/null; then
    rm -f "$OUT.tmp"
else
    mv "$OUT.tmp" "$OUT"
fi
