// gen_format_oracle.cpp — capture the g++ <format> oracle as fixture rows.
//
// std::format IS the specification for madc's rt_format engine (the
// std::print/println/format intrinsic arc — see
// docs/plans/2026-08-19-std-print-format-intrinsics.md). This tool runs every
// (kind, value, spec) cell of the coverage matrix through the REAL libstdc++
// std::vformat and emits one C initializer row per cell into
// tests/unit/rt_format_oracle.inc, which tests/unit/test_rt_format.cpp replays
// against the engine. A cell libstdc++ REJECTS (throws std::format_error) is
// skipped with a stderr note — invalid combinations are compile-time errors in
// madc's lowering, so the engine only ever sees the valid matrix.
//
// Build/run (container; needs GCC 13+ for <format>):
//   g++ -std=c++23 -O0 -o tmp/gen_format_oracle scripts/gen_format_oracle.cpp
//   tmp/gen_format_oracle > tests/unit/rt_format_oracle.inc
//
// The .inc is CHECKED IN: the oracle outputs are the contract, regenerated
// only when the matrix grows (or the oracle compiler majorly changes — a
// diff at regeneration is a finding, not noise).

#include <format>
#include <cstdio>
#include <cstring>
#include <cstdint>
#include <bit>
#include <string>
#include <limits>
#include <cmath>

static int emitted = 0, skipped = 0;

// C-escape for emission inside a "" literal. Octal (never \xHH: a hex escape
// swallows following hex digits and corrupts rows like \x41BC).
static std::string cesc(const std::string &s)
{
	std::string o;
	for ( size_t i = 0; i < s.size(); ++i )
	{
		unsigned char c = (unsigned char)s[i];
		if ( c == '\\' || c == '"' )
		{
			o += '\\';
			o += (char)c;
		}
		else if ( c >= 0x20 && c < 0x7f )
			o += (char)c;
		else
		{
			char b[8];
			std::snprintf(b, sizeof b, "\\%03o", c);
			o += b;
		}
	}
	return o;
}

template <class T>
static void row(const char *kind, const char *spec, unsigned long long bits,
		const char *strpay, T value)
{
	// ORACLE DEFECT, measured 2026-08-19 (tmp/fmt/maxf.cpp, g++ 13.3):
	// libstdc++'s "{:#.0f}" of DBL_MAX returns 311 bytes whose byte 0 is
	// NUL and whose digits are shifted one position ("...836.8" where
	// printf %#.0f correctly gives "...8368.") — the alt-form '.'
	// insertion corrupts the buffer head at this size. The engine keeps
	// printf's correct behavior; the corrupt cell is excluded rather than
	// pinned.
	if ( std::strcmp(spec, "#.0f") == 0 && bits == 0x7fefffffffffffffull )
	{
		std::fprintf(stderr, "skip %-11s \"%s\": libstdc++ 13 corrupt cell (see comment)\n",
			     kind, spec);
		++skipped;
		return;
	}
	std::string fmt = std::string("{:") + spec + "}";
	std::string out;
	try
	{
		// P2905: make_format_args wants an lvalue.
		out = std::vformat(fmt, std::make_format_args(value));
	}
	catch ( const std::exception &e )
	{
		std::fprintf(stderr, "skip %-11s \"%s\": %s\n", kind, spec, e.what());
		++skipped;
		return;
	}
	// out.size() rides along because an expected string can legitimately
	// contain an embedded NUL ("{:5c}" of integer 0) — a C-string compare
	// would silently truncate it.
	if ( strpay )
		std::printf("{ %s, \"%s\", 0ull, \"%s\", \"%s\", %zu },\n",
			    kind, cesc(spec).c_str(), cesc(strpay).c_str(),
			    cesc(out).c_str(), out.size());
	else
		std::printf("{ %s, \"%s\", 0x%llxull, nullptr, \"%s\", %zu },\n",
			    kind, cesc(spec).c_str(), bits, cesc(out).c_str(),
			    out.size());
	++emitted;
}

int main()
{
	std::printf("// AUTO-GENERATED by scripts/gen_format_oracle.cpp — do not edit.\n");
	std::printf("// Oracle: libstdc++ std::vformat, g++ -std=c++23 (see the generator\n");
	std::printf("// for the matrix). Row shape: { kind, spec, bits, str, expect, expect_n }.\n");

	// --- signed integers -------------------------------------------------
	static const char *ispecs[] = {
		"", "d", "b", "B", "o", "x", "X",
		"#x", "#X", "#b", "#B", "#o", "#d",
		"+d", " d", "-d",
		"08d", "8d", "<8d", ">8d", "^8d",
		"*<8d", "*>8d", "*^8d", "+#010X", "010b", "#06x",
		"c", "5c",
		0
	};
	static const long long ivals[] = {
		0, 1, 42, -42, 7, 65, 255, -1, 1000000,
		std::numeric_limits<long long>::max(),
		std::numeric_limits<long long>::min()
	};
	for ( size_t v = 0; v < sizeof(ivals) / sizeof(*ivals); ++v )
		for ( int s = 0; ispecs[s]; ++s )
			row("FMTORC_I64", ispecs[s],
			    (unsigned long long)ivals[v], nullptr, ivals[v]);

	// --- unsigned integers ------------------------------------------------
	static const unsigned long long uvals[] = {
		0ull, 255ull, 1ull << 63,
		std::numeric_limits<unsigned long long>::max()
	};
	for ( size_t v = 0; v < sizeof(uvals) / sizeof(*uvals); ++v )
		for ( int s = 0; ispecs[s]; ++s )
			row("FMTORC_U64", ispecs[s], uvals[v], nullptr, uvals[v]);

	// --- doubles -----------------------------------------------------------
	static const char *fspecs[] = {
		"", "f", "F", ".0f", ".3f", "10.3f", "<10.3f", ">10.3f",
		"^10.3f", "*^12.3f", "010.3f", "+f", " f",
		"e", ".3e", ".0e", "E", ".3E", "12.4e",
		"g", ".3g", ".17g", "G", "#g", "#.0f",
		"a", "A", ".3a", "#a",
		"+10f", " 010.2f",
		// typeless-with-precision: general presentation at that precision
		".3", ".17", ".0", "10.3",
		0
	};
	static const double fvals[] = {
		0.0, -0.0, 1.0, -1.0, 3.5, 0.1, 1.0 / 3.0,
		1e-5, 1e20, 123456.789, 6.02214076e23,
		// fixed-vs-scientific length TIES and crossovers — the tie-break
		// rule is read off the oracle, never derived from memory:
		// 1e4 -> "10000"/"1e+04" (5/5), 0.001 -> "0.001"/"1e-03" (5/5).
		1e3, 1e4, 1e5, 0.001, 0.0001, 1e15, 1e16, 0.5, 1024.0,
		2.2250738585072014e-308,	// DBL_MIN
		1.7976931348623157e308,		// DBL_MAX
		4.9406564584124654e-324,	// denormal min
		std::numeric_limits<double>::infinity(),
		-std::numeric_limits<double>::infinity(),
		std::numeric_limits<double>::quiet_NaN()
	};
	for ( size_t v = 0; v < sizeof(fvals) / sizeof(*fvals); ++v )
		for ( int s = 0; fspecs[s]; ++s )
			row("FMTORC_F64", fspecs[s],
			    std::bit_cast<unsigned long long>(fvals[v]),
			    nullptr, fvals[v]);

	// --- strings ------------------------------------------------------------
	static const char *sspecs[] = {
		"", "s", "10s", "<10s", ">10s", "^10s",
		".3s", "10.3s", "*^10s", "2s", "?",
		0
	};
	static const char *svals[] = {
		"", "hello", "h\303\251llo", "ab\tc", "abcdefghijkl", 0
	};
	for ( int v = 0; svals[v]; ++v )
		for ( int s = 0; sspecs[s]; ++s )
		{
			std::string payload(svals[v]);
			row("FMTORC_STR", sspecs[s], 0, svals[v], payload);
		}

	// --- char ----------------------------------------------------------------
	static const char *cspecs[] = {
		"", "c", "d", "#x", "b", "5c", "<5c", "?", 0
	};
	static const char cvals[] = { 'a', 'Z', '0', '\n' };
	for ( size_t v = 0; v < sizeof(cvals); ++v )
		for ( int s = 0; cspecs[s]; ++s )
			row("FMTORC_CHAR", cspecs[s],
			    (unsigned long long)(unsigned char)cvals[v],
			    nullptr, cvals[v]);

	// --- bool ------------------------------------------------------------------
	static const char *bspecs[] = { "", "s", "d", "#x", "b", "6s", ">6s", 0 };
	for ( int v = 0; v <= 1; ++v )
		for ( int s = 0; bspecs[s]; ++s )
			row("FMTORC_BOOL", bspecs[s],
			    (unsigned long long)v, nullptr, (bool)(v != 0));

	// --- pointers -----------------------------------------------------------
	static const char *pspecs[] = { "", "p", "20p", ">20p", 0 };
	{
		const void *p = (const void *)(uintptr_t)0xdeadbeefull;
		for ( int s = 0; pspecs[s]; ++s )
			row("FMTORC_PTR", pspecs[s], 0xdeadbeefull, nullptr, p);
		const void *nullp = nullptr;
		for ( int s = 0; pspecs[s]; ++s )
			row("FMTORC_PTR", pspecs[s], 0ull, nullptr, nullp);
	}

	std::fprintf(stderr, "%d rows emitted, %d cells rejected by the oracle\n",
		     emitted, skipped);
	return 0;
}
