#!/usr/bin/env bash
# gen_mangle_oracle.sh — capture the g++ AND clang++ Itanium-mangling oracle for
# the user-shape corpus (tests/abi/mangle_corpus.cpp) as tests/unit/mangle_oracle.inc.
#
# THE ORACLE IS THE FIXTURE. Rule #1: gcc/clang is canon — in c++/madc mode a
# user-defined C++ symbol madc emits must be byte-identical to theirs, or a
# madc-compiled .o/.so does not link against real C++
# (docs/plans/2026-09-16-free-function-overloading-linkage.md). Nothing here is
# hand-transcribed: BOTH canon compilers compile the corpus, their DEFINED
# symbol sets must be identical (a disagreement is a finding — investigate
# the shape, never pick one), and the agreed set is emitted one row per
# symbol as `{ "mangled", "demangled" }`. tests/unit/test_mangle.cpp replays
# every row against madc's Itanium encoders (phase 0); scripts/mangle_abi_gate.sh
# regenerates it on every fulltest and fails on drift.
#
# Usage (on the CONTAINER — it has both compilers; the QNAP never builds):
#   bash scripts/gen_mangle_oracle.sh            # writes tests/unit/mangle_oracle.inc
#   bash scripts/gen_mangle_oracle.sh OUTFILE    # writes elsewhere (the drift gate)
#   MANGLE_CORPUS=path ...                       # another corpus (the gate's negative control)
#
# ⚠️ Regeneration happens on the CONTAINER but the SOURCE OF TRUTH is the repo
# tree: scp the fresh .inc back to the local tree IMMEDIATELY — the next rsync
# sync overwrites the container copy with whatever the local tree holds
# (rt_format_oracle.inc, 2026-08-20: 1428 assertions failed exactly this way).
#
# Host model: LP64 (the corpus's std::size_t row is `m`; an LLP64 host says `y`).
# Mach-O symbols carry a leading underscore — stripped so the rows are the
# Itanium names themselves and one .inc serves the Linux and the Mac lane.
set -u
cd "$(dirname "$0")/.."

GXX="${GXX:-g++}"
CLANGXX="${CLANGXX:-clang++}"
corpus="${MANGLE_CORPUS:-tests/abi/mangle_corpus.cpp}"
out="${1:-tests/unit/mangle_oracle.inc}"
dir="$PWD/tmp/mangle_oracle"

fail() { echo "gen_mangle_oracle: $1" >&2; exit 1; }

command -v "$GXX" >/dev/null 2>&1 || fail "no $GXX — the oracle needs BOTH canon compilers (GXX= to point at one)"
command -v "$CLANGXX" >/dev/null 2>&1 || fail "no $CLANGXX — the oracle needs BOTH canon compilers (CLANGXX= to point at one)"
command -v nm >/dev/null 2>&1 || fail "no nm"
command -v c++filt >/dev/null 2>&1 || fail "no c++filt"
[ -f "$corpus" ] || fail "no corpus at $corpus"

rm -rf "$dir"; mkdir -p "$dir"
"$GXX" -std=c++20 -O0 -c -o "$dir/gxx.o" "$corpus" || fail "$GXX rejected the corpus"
"$CLANGXX" -std=c++20 -O0 -c -o "$dir/clang.o" "$corpus" || fail "$CLANGXX rejected the corpus"

# Every DEFINED symbol (text, weak, data — vtables and typeinfo live in
# .rodata), sorted. Mach-O prefixes an underscore; drop exactly one.
strip_underscore=''
case "$(uname -s)" in Darwin) strip_underscore='s/^_//';; esac
syms() {
	nm --defined-only "$1" | awk 'NF >= 3 { print $3 }' | sed -e "$strip_underscore" | sort -u
}
syms "$dir/gxx.o" > "$dir/gxx.syms"
syms "$dir/clang.o" > "$dir/clang.syms"

if ! cmp -s "$dir/gxx.syms" "$dir/clang.syms"; then
	echo "gen_mangle_oracle: $GXX and $CLANGXX DISAGREE on the corpus's defined symbols (< $GXX only, > $CLANGXX only):" >&2
	diff "$dir/gxx.syms" "$dir/clang.syms" >&2
	fail "two canon compilers must agree — investigate the shape, never pick one"
fi

n=$(grep -c . "$dir/gxx.syms")
[ "$n" -ge 100 ] || fail "only $n defined symbols — the corpus no longer exercises the shapes (floor 100)"

c++filt < "$dir/gxx.syms" > "$dir/gxx.dem"
mkdir -p "$(dirname "$out")"
{
	echo "// tests/unit/mangle_oracle.inc — GENERATED by scripts/gen_mangle_oracle.sh. DO NOT EDIT."
	echo "// Corpus: tests/abi/mangle_corpus.cpp. Both canon compilers emitted exactly this"
	echo "// defined-symbol set (scripts/mangle_abi_gate.sh re-agrees it on every fulltest):"
	echo "//   $("$GXX" --version | head -1)"
	echo "//   $("$CLANGXX" --version | head -1)"
	echo "// Row: { mangled, demangled }. Regenerate on the container; scp it back at once."
	paste -d '\t' "$dir/gxx.syms" "$dir/gxx.dem" | while IFS=$'\t' read -r s d; do
		printf '{ "%s", "%s" },\n' "$s" "$d"
	done
} > "$out" || fail "could not write $out"

echo "gen_mangle_oracle: $n symbols, $GXX == $CLANGXX, written to $out"
