#!/bin/bash
# Generate pre-compiled headers (.madh) from system headers.
#
# Pipeline: gcc -E -P (preprocess) → madc --emit-pch (tokenize+compress)
# → xxd -i (C array) → precompiled_headers.cpp
#
# Uses GCC's preprocessor to handle all GNU extensions, then madc's
# own lexer to tokenize the clean C output.

set -e

SCRIPTDIR="$(cd "$(dirname "$0")" && pwd)"
TOPDIR="$(cd "$SCRIPTDIR/.." && pwd)"
MADC="$TOPDIR/bin/madc"
OUTFILE="$TOPDIR/src/precompiled_headers.cpp"
TMPDIR="$TOPDIR/tmp/pch_build"

# Headers to pre-compile (relative to /usr/include or absolute)
HEADERS=(
    stdio.h
    stdlib.h
    string.h
    strings.h
    stdint.h
    stddef.h
    stdbool.h
    errno.h
    fcntl.h
    signal.h
    math.h
    unistd.h
    time.h
    ctype.h
    assert.h
    float.h
    locale.h
    dirent.h
    dlfcn.h
    grp.h
    pwd.h
    poll.h
    regex.h
    pthread.h
    termios.h
    syslog.h
    fnmatch.h
    glob.h
    malloc.h
    alloca.h
    crypt.h
    netdb.h
    arpa/inet.h
    netinet/in.h
    sys/stat.h
    sys/types.h
    sys/wait.h
    sys/time.h
    sys/socket.h
    sys/select.h
    sys/resource.h
)

# Check prerequisites
if [ ! -x "$MADC" ]; then
    echo "Error: $MADC not found. Build madc first." >&2
    exit 1
fi

if ! command -v gcc >/dev/null 2>&1; then
    echo "Error: gcc not found. Install gcc to pre-compile headers." >&2
    exit 1
fi

mkdir -p "$TMPDIR"

# Start output file
cat > "$OUTFILE" <<'HEADER'
// AUTO-GENERATED by scripts/gen_precompiled_headers.sh — do not edit
// Pre-compiled headers in .madh format (post-lexer token stream, compressed)
#include <cstdint>
#include <cstddef>
#include <map>
#include <string>

struct PrecompiledHeader {
    const uint8_t *data;
    size_t size;
};

HEADER

echo "Generating pre-compiled headers..."
count=0
failed=0
entries=""

for h in "${HEADERS[@]}"; do
    safe_name=$(echo "$h" | sed 's|[/.]|_|g')
    pp_file="$TMPDIR/${safe_name}_pp.h"
    madh_file="$TMPDIR/${safe_name}.madh"

    # Find the header
    header_path=""
    if [ -f "/usr/include/$h" ]; then
        header_path="/usr/include/$h"
    elif [ -f "/usr/include/x86_64-linux-gnu/$h" ]; then
        header_path="/usr/include/x86_64-linux-gnu/$h"
    fi

    if [ -z "$header_path" ]; then
        echo "  SKIP: $h (not found)"
        continue
    fi

    # Step 1: Preprocess with GCC
    if ! gcc -E -P "$header_path" -o "$pp_file" 2>/dev/null; then
        echo "  FAIL: $h (gcc -E failed)"
        failed=$((failed + 1))
        continue
    fi

    # Step 2: Tokenize with madc
    if ! "$MADC" --emit-pch -o "$madh_file" "$pp_file" 2>/dev/null; then
        echo "  FAIL: $h (madc --emit-pch failed)"
        failed=$((failed + 1))
        continue
    fi

    # Step 3: Convert to C array
    size=$(wc -c < "$madh_file")
    echo "static const uint8_t pch_${safe_name}[] = {" >> "$OUTFILE"
    xxd -i < "$madh_file" >> "$OUTFILE"
    echo "};" >> "$OUTFILE"
    echo "" >> "$OUTFILE"

    entries="$entries    {\"$h\", {pch_${safe_name}, sizeof(pch_${safe_name})}},\n"
    count=$((count + 1))
    echo "  OK: $h ($size bytes compressed)"
done

# Write the index map
cat >> "$OUTFILE" <<'INDEX'

static std::map<std::string, PrecompiledHeader> precompiled_headers = {
INDEX
echo -e "$entries" >> "$OUTFILE"
cat >> "$OUTFILE" <<'FOOTER'
};

const PrecompiledHeader *find_precompiled_header(const std::string &name)
{
    auto it = precompiled_headers.find(name);
    if (it != precompiled_headers.end())
        return &it->second;
    return nullptr;
}
FOOTER

echo "Done: $count headers pre-compiled, $failed failed"
echo "Output: $OUTFILE"

# Cleanup
rm -rf "$TMPDIR"
