#!/bin/bash
# Generate src/embedded_headers.cpp from include/madc/*.h files
# Each file becomes an entry in a map<string, string> keyed by its basename

SRCDIR="$(dirname "$0")/../include/madc"
OUTFILE="$(dirname "$0")/../src/embedded_headers.cpp"

cat > "$OUTFILE" <<'HEADER'
// AUTO-GENERATED by scripts/gen_embedded_headers.sh — do not edit
#include <map>
#include <string>

static std::map<std::string, std::string> embedded_headers = {
HEADER

first=1
for f in "$SRCDIR"/*.h; do
    [ -f "$f" ] || continue
    name=$(basename "$f")
    if [ "$first" -ne 1 ]; then
        echo "," >> "$OUTFILE"
    fi
    first=0
    printf '    {"%s", ' "$name" >> "$OUTFILE"
    # output file content as a C++ raw string literal
    printf 'R"EMBED(' >> "$OUTFILE"
    cat "$f" >> "$OUTFILE"
    printf ')EMBED"}' >> "$OUTFILE"
done

cat >> "$OUTFILE" <<'FOOTER'

};

const std::string *find_embedded_header(const std::string &name)
{
    auto it = embedded_headers.find(name);
    if ( it != embedded_headers.end() )
        return &it->second;
    return nullptr;
}
FOOTER

echo "Generated $OUTFILE"
