#!/bin/bash
# Generate src/embedded_headers.cpp from include/madc/* files
# Supports subdirectories — keys are paths relative to include/madc/
# e.g. include/madc/sys/wait.h becomes "sys/wait.h"

SRCDIR="$(dirname "$0")/../include/madc"
OUTFILE="$(dirname "$0")/../src/embedded_headers.cpp"
# Generate into a temp file and only replace OUTFILE when the content actually
# changes. This keeps the rule safe to run on EVERY build (so a DELETED embedded
# header is reflected — an mtime-only prereq never sees a deletion) without
# churning embedded_headers.o's mtime when nothing changed.
TMPFILE="${OUTFILE}.tmp.$$"
OUTFILE_REAL="$OUTFILE"
OUTFILE="$TMPFILE"

cat > "$OUTFILE" <<'HEADER'
// AUTO-GENERATED by scripts/gen_embedded_headers.sh — do not edit
#include <map>
#include <string>

static std::map<std::string, std::string> embedded_headers = {
HEADER

first=1
while IFS= read -r f; do
    [ -f "$f" ] || continue
    # key = path relative to SRCDIR (e.g. "sys/wait.h")
    name="${f#${SRCDIR}/}"
    if [ "$first" -ne 1 ]; then
        printf ',\n' >> "$OUTFILE"
    fi
    first=0
    printf '    {"%s", ' "$name" >> "$OUTFILE"
    printf 'R"EMBED(' >> "$OUTFILE"
    cat "$f" >> "$OUTFILE"
    printf ')EMBED"}' >> "$OUTFILE"
done < <(find "$SRCDIR" -type f | sort)

cat >> "$OUTFILE" <<'FOOTER'

};

const std::string *find_embedded_header(const std::string &name)
{
    auto it = embedded_headers.find(name);
    if ( it != embedded_headers.end() )
        return &it->second;
    return nullptr;
}
FOOTER

if [ ! -f "$OUTFILE_REAL" ] || ! cmp -s "$TMPFILE" "$OUTFILE_REAL"; then
    mv "$TMPFILE" "$OUTFILE_REAL"
    echo "Generated $OUTFILE_REAL"
else
    rm -f "$TMPFILE"
    echo "Up to date: $OUTFILE_REAL"
fi
