#!/bin/bash
# Generate src/embedded_headers.cpp from include/madc/* files
# Supports subdirectories — keys are paths relative to include/madc/
# e.g. include/madc/sys/wait.h becomes "sys/wait.h"
#
# Usage: gen_embedded_headers.sh [extra_dir] [outfile]
#   extra_dir — optional second root of headers to embed (keys relative to
#               it), e.g. a hosted mode's generated darwin prelude dir.
#               Committed include/madc/ names win on collision (first key
#               in the std::map initializer wins).
#   outfile   — optional output path; per-mode builds point this into their
#               obj tree so generated (SDK-derived) content never lands in
#               the committed src/embedded_headers.cpp.

SRCDIR="$(dirname "$0")/../include/madc"
EXTRADIR="$1"
OUTFILE="${2:-$(dirname "$0")/../src/embedded_headers.cpp}"

if [ -n "$EXTRADIR" ] && [ ! -d "$EXTRADIR" ]; then
    echo "Error: extra embedded-header dir '$EXTRADIR' not found" >&2
    exit 1
fi

# Generate into a temp file and only replace OUTFILE when the content actually
# changes. This keeps the rule safe to run on EVERY build (so a DELETED embedded
# header is reflected — an mtime-only prereq never sees a deletion) without
# churning embedded_headers.o's mtime when nothing changed.
TMPFILE="${OUTFILE}.tmp.$$"
OUTFILE_REAL="$OUTFILE"
OUTFILE="$TMPFILE"

cat > "$OUTFILE" <<'HEADER'
// AUTO-GENERATED by scripts/gen_embedded_headers.sh — do not edit
#include <map>
#include <string>

static std::map<std::string, std::string> embedded_headers = {
HEADER

first=1
emit_dir() {
    local dir="$1"
    while IFS= read -r f; do
        [ -f "$f" ] || continue
        # skip generator scratch (write_on_change temporaries)
        case "$(basename "$f")" in .*) continue ;; esac
        # key = path relative to the dir (e.g. "sys/wait.h")
        name="${f#${dir}/}"
        if [ "$first" -ne 1 ]; then
            printf ',\n' >> "$OUTFILE"
        fi
        first=0
        printf '    {"%s", ' "$name" >> "$OUTFILE"
        printf 'R"EMBED(' >> "$OUTFILE"
        cat "$f" >> "$OUTFILE"
        printf ')EMBED"}' >> "$OUTFILE"
    done < <(find "$dir" -type f | sort)
}

emit_dir "$SRCDIR"
if [ -n "$EXTRADIR" ]; then
    emit_dir "$EXTRADIR"
fi

cat >> "$OUTFILE" <<'FOOTER'

};

const std::string *find_embedded_header(const std::string &name)
{
    auto it = embedded_headers.find(name);
    if ( it != embedded_headers.end() )
        return &it->second;
    // <madc/X> is the explicit spelling of madc's compiler-owned include
    // tree: keys here are relative to include/madc/, and the dual-build
    // runtime sources (src/rt/rt_posix_*.c) include their own public
    // headers as <madc/posix/X> so ONE spelling serves both compilers —
    // mingw-g++ resolves it through -I../include, madc through this map.
    // The bare internal keys (e.g. posix/X) stay non-includable: policy
    // (is_embedded_header_allowed) never sees them spelled bare.
    if ( name.compare(0, 5, "madc/") == 0 )
    {
        it = embedded_headers.find(name.substr(5));
        if ( it != embedded_headers.end() )
            return &it->second;
    }
    return nullptr;
}
FOOTER

if [ ! -f "$OUTFILE_REAL" ] || ! cmp -s "$TMPFILE" "$OUTFILE_REAL"; then
    mv "$TMPFILE" "$OUTFILE_REAL"
    echo "Generated $OUTFILE_REAL"
else
    rm -f "$TMPFILE"
    echo "Up to date: $OUTFILE_REAL"
fi
