#!/bin/bash
# Generate src/sys_include_paths.cpp — the host's system #include <...> search
# list, captured from the configured compiler so madc searches the SAME paths the
# build toolchain does (incl. the C++ paths the hardcoded list lacked).
#
# Host-specific: gitignored, regenerated on build. `make clean` forces a refresh
# if the toolchain changes. Empty output => madc falls back to its hardcoded list.
set -u

CXX="${CXX:-c++}"
OUT="$(dirname "$0")/../src/sys_include_paths.cpp"

# `<compiler> -x c++ -E -v` prints the search list between two marker lines;
# each path line is indented by one space. Strip indent + any trailing annotation.
paths=$(printf '' | "$CXX" -x c++ -E -v - 2>&1 \
        | sed -n '/#include <...> search starts here:/,/End of search list/p' \
        | sed -n 's/^ \([^ ]*\).*$/\1/p')

{
    echo '// AUTO-GENERATED by scripts/gen_sys_includes.sh — DO NOT EDIT, DO NOT COMMIT.'
    echo "// Host system #include search paths from \`$CXX -x c++ -E -v\`."
    echo 'const char *madc_sys_include_paths[] = {'
    if [ -n "$paths" ]; then
        while IFS= read -r p; do
            [ -z "$p" ] && continue
            case "$p" in */) ;; *) p="$p/";; esac
            printf '    "%s",\n' "$p"
        done <<< "$paths"
    fi
    echo '    (const char *)0'
    echo '};'
    # The compiler-owned (bucket-1/2 freestanding) include dir — the one GCC
    # supplies itself (stddef.h, stdarg.h, limits.h, intrinsics, …). The header
    # partition (madc-header-partition-handoff.md) says madc PROVIDES equivalents
    # for these, so when bypassing embedded SYSTEM-library shims we must still
    # keep them: a header resolving here is freestanding, not a glibc/libstdc++
    # twin. Empty string when detection fails (no compiler at build time).
    owned=$("$CXX" -print-file-name=include 2>/dev/null)
    case "$owned" in
        include) owned="" ;;   # not found: -print-file-name echoes the bare arg
        */) ;; *) [ -n "$owned" ] && owned="$owned/" ;;
    esac
    echo "const char *madc_compiler_owned_include_dir = \"$owned\";"
} > "$OUT"
