#!/bin/bash
# Generate src/sys_include_paths.cpp — the host's system #include <...> search
# list, captured from the configured compiler so madc searches the SAME paths the
# build toolchain does (incl. the C++ paths the hardcoded list lacked).
#
# Host-specific: gitignored, regenerated on build. `make clean` forces a refresh
# if the toolchain changes. Empty output => madc falls back to its hardcoded list.
set -u

CXX="${CXX:-c++}"
OUT="$(dirname "$0")/../src/sys_include_paths.cpp"

# `<compiler> -x c++ -E -v` prints the search list between two marker lines;
# each path line is indented by one space. Strip indent + any trailing annotation.
paths=$(printf '' | "$CXX" -x c++ -E -v - 2>&1 \
        | sed -n '/#include <...> search starts here:/,/End of search list/p' \
        | sed -n 's/^ \([^ ]*\).*$/\1/p')

{
    echo '// AUTO-GENERATED by scripts/gen_sys_includes.sh — DO NOT EDIT, DO NOT COMMIT.'
    echo "// Host system #include search paths from \`$CXX -x c++ -E -v\`."
    echo 'const char *madc_sys_include_paths[] = {'
    if [ -n "$paths" ]; then
        while IFS= read -r p; do
            [ -z "$p" ] && continue
            case "$p" in */) ;; *) p="$p/";; esac
            printf '    "%s",\n' "$p"
        done <<< "$paths"
    fi
    echo '    (const char *)0'
    echo '};'
} > "$OUT"
