#!/usr/bin/env python3
"""Embed upstream's C API plus madc's own extension header; never maintain a
second declarations list for either: upstream's comes from third_party/webview,
madc's from src/madcwebview_chrome.h (the header libmadcwebview implements)."""
import argparse
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
args = parser.parse_args()
root = Path(__file__).resolve().parent.parent
source = (root / 'third_party/webview/core/include/webview/webview.h').read_text()
end = '\n#ifdef __cplusplus\n}\n\n#ifndef WEBVIEW_HEADER\n'
assert source.count(end) == 1, 'upstream C API boundary changed; review the new header'
api = source.split(end)[0]
# Upstream defaults to inline in C++ header-only mode. This declaration-only
# rendering consumes the shared C library, with identical types and C linkage.
begin = api.index('#ifndef WEBVIEW_API\n')
finish = api.index('/// @name Version', begin)
api = api[:begin] + '#define WEBVIEW_API extern\n\n' + api[finish:]
# madc's extension (the native menu bar): the same header libmadcwebview's
# madcwebview_chrome.cc implements, appended verbatim inside the C API block.
extension = (root / 'src/madcwebview_chrome.h').read_text()
generated = ('// Generated by scripts/gen_webview_header.py from third_party/webview\n'
             '// and src/madcwebview_chrome.h (madc\'s extension of the library).\n'
             '// Thread contract: use the UI thread; dispatch/terminate may be called\n'
             '// from background threads. Bind callback strings are borrowed.\n' + api +
             '\n' + extension +
             '\n#ifdef __cplusplus\n}\n#endif\n#undef WEBVIEW_API\n#endif /* WEBVIEW_H */\n')
output = root / 'include/madc/webview.h'
if args.check:
    if not output.exists() or output.read_text() != generated:
        raise SystemExit('webview.h differs from upstream C API; run scripts/gen_webview_header.py')
    print('webview C API matches upstream')
elif not output.exists() or output.read_text() != generated:
    output.write_text(generated)
