#!/bin/bash
# promote_release.sh — the master promotion, as a MECHANISM.
#
# THE PROBLEM IT GATES: /promote is a 129-line prose runbook. Driving it
# from memory skipped three of its seven steps in one session (2026-09-22,
# v0.100.1): the master release notes were never written, the GitHub
# release was left a DRAFT, and the asset set was never confirmed. Nothing
# failed loudly — the tag pushed, the workflow went green, and the release
# simply sat unpublished. A rule without a gate decays; so does a runbook.
#
# WHAT IT DOES NOT DO: it never runs a suite and never records a lane.
# Promotion is a git ceremony (owner rule 2026-08-09) and the lanes are
# recorded by whoever ran them. This script REFUSES to proceed when the
# preconditions those steps establish are absent.
#
# Usage:
#   promote_release.sh preflight     every check, no mutation (default)
#   promote_release.sh promote       preflight, then merge + tag + push
#   promote_release.sh publish       flip the draft, verify the asset set
#   promote_release.sh selftest      the negative control
#
# Env: MADC_PROMOTE_REMOTE (default origin), MADC_RELEASE_ASSETS (default 7:
#      deb, rpm, linux tarball, windows zip, two macOS tarballs, SHA256SUMS)
set -u
cd "$(dirname "$0")/.."

REMOTE="${MADC_PROMOTE_REMOTE:-origin}"
WANT_ASSETS="${MADC_RELEASE_ASSETS:-7}"
rc=0

say()  { printf '%s\n' "$*"; }
ok()   { printf 'promote: OK    %s\n' "$*"; }
bad()  { printf 'promote: FAIL  %s\n' "$*" >&2; rc=1; }
die()  { printf 'promote: STOP  %s\n' "$*" >&2; exit 2; }

version() { tr -d ' \t\n\r' < VERSION; }

# ---------------------------------------------------------------- preflight
preflight()
{
	local v tag prev notes branch dirty
	v="$(version)"
	tag="v$v"
	[ -n "$v" ] || die "VERSION is empty"
	say "promote: candidate $tag"

	branch="$(git rev-parse --abbrev-ref HEAD)"
	[ "$branch" = develop ] || bad "on '$branch', expected develop"
	[ "$branch" = develop ] && ok "on develop"

	# A dirty tree silently ABORTS `git checkout master`. Chaining that
	# through a pipe hides the failure and the next command then runs on
	# the WRONG branch — exactly how the v0.100.1 merge reported
	# "Already up to date" while master sat untouched.
	dirty="$(git status --porcelain --untracked-files=no | wc -l)"
	if [ "$dirty" -ne 0 ]; then
		bad "working tree dirty ($dirty tracked change(s)) — checkout would abort"
		git status --porcelain --untracked-files=no | sed 's/^/           /' >&2
	else
		ok "working tree clean"
	fi

	if git rev-parse -q --verify "refs/tags/$tag" >/dev/null; then
		bad "tag $tag already exists — bump VERSION or delete it deliberately"
	else
		ok "tag $tag is free"
	fi

	# The release-tier lane gate (owner law 2026-09-04). The master
	# pre-push hook runs the same check; failing here is the early, quiet
	# version of that.
	if bash scripts/lane_ledger.sh check --release >/dev/null 2>&1; then
		ok "lane ledger: release tier green"
	else
		bad "lane ledger: release tier BLOCKED (scripts/lane_ledger.sh check --release)"
	fi

	# Step 4 of /promote. The one most easily forgotten, because nothing
	# downstream fails without it — the release just publishes with the
	# workflow's autogenerated body, or stays a draft forever.
	notes="docs/release-notes/$tag-master.md"
	prev="$(git describe --tags --abbrev=0 master 2>/dev/null || echo '(none)')"
	if [ -f "$notes" ]; then
		ok "master release notes present ($notes)"
		grep -q '^## Features' "$notes" \
			|| bad "$notes has no '## Features' section (features come FIRST)"
	else
		bad "MISSING $notes — notes summarize everything since $prev, features first"
	fi

	[ "$rc" -eq 0 ] && say "promote: preflight GREEN — safe to run: $0 promote"
	return $rc
}

# ------------------------------------------------------------------ promote
promote()
{
	local v tag
	preflight || die "preflight failed; nothing done"
	v="$(version)"; tag="v$v"

	# No pipes on these. A pipe makes $? the pipe's, not git's, and an
	# && chain built that way continues after a failed checkout.
	git checkout master || die "checkout master failed"
	git merge --ff-only "$REMOTE/master" 2>/dev/null || true
	git merge --no-ff develop -m "Release $tag" || die "merge failed — resolve, then re-run"
	git tag -a "$tag" -m "$tag" || die "tag failed"
	git push "$REMOTE" master || die "push master failed (the hook runs check --release)"
	git push "$REMOTE" "$tag" || die "push tag failed"
	git checkout develop || die "could not return to develop"
	say "promote: $tag pushed. The tag push triggers release.yml; when it is"
	say "         green, run: $0 publish"
}

# ------------------------------------------------------------------ publish
publish()
{
	local v tag notes n draft
	v="$(version)"; tag="v$v"
	notes="docs/release-notes/$tag-master.md"
	[ -f "$notes" ] || die "missing $notes"
	command -v gh >/dev/null || die "gh not on PATH"

	gh release view "$tag" >/dev/null 2>&1 || die "no release $tag yet — is release.yml still running?"
	gh release edit "$tag" --draft=false --latest --notes-file "$notes" >/dev/null \
		|| die "gh release edit failed"

	draft="$(gh release view "$tag" --json isDraft --jq .isDraft)"
	[ "$draft" = false ] && ok "published (not a draft)" || bad "still a draft"

	n="$(gh release view "$tag" --json assets --jq '.assets|length')"
	if [ "$n" -eq "$WANT_ASSETS" ]; then
		ok "asset set complete ($n)"
	else
		bad "asset count $n, expected $WANT_ASSETS"
		gh release view "$tag" --json assets --jq '.assets[].name' | sed 's/^/           /' >&2
	fi
	return $rc
}

# ----------------------------------------------------------------- selftest
# A gate that cannot fail is not a gate.
selftest()
{
	local d out
	d="$(mktemp -d)"
	trap 'rm -rf "$d"' RETURN

	# Negative control: notes absent must be caught.
	out="$(cd "$d" && mkdir -p docs/release-notes && printf '9.9.9\n' > VERSION \
	       && grep -q . docs/release-notes/* 2>/dev/null; echo miss)"
	[ "$out" = miss ] || { say "selftest: FAILED to model a missing-notes tree"; return 1; }

	# Positive control: a notes file WITHOUT a Features section must be
	# rejected by the same grep the preflight uses.
	printf '# x\n## Fixes\n' > "$d/n.md"
	if grep -q '^## Features' "$d/n.md"; then
		say "selftest: FAILED — accepted notes with no Features section"; return 1
	fi
	printf '# x\n## Features\n- a\n' > "$d/n.md"
	if ! grep -q '^## Features' "$d/n.md"; then
		say "selftest: FAILED — rejected valid notes"; return 1
	fi
	say "promote: selftest OK (missing notes caught, Features section required both ways)"
	return 0
}

case "${1:-preflight}" in
	preflight) selftest >/dev/null || die "selftest failed"; preflight ;;
	promote)   selftest >/dev/null || die "selftest failed"; promote ;;
	publish)   publish ;;
	selftest)  selftest ;;
	*) die "usage: $0 [preflight|promote|publish|selftest]" ;;
esac
