// AUTO-GENERATED by scripts/gen_embedded_headers.sh — do not edit
#include <map>
#include <string>

static std::map<std::string, std::string> embedded_headers = {
    {"alloca.h", R"EMBED(// madc embedded alloca.h
// alloca() allocates on the stack — madc maps it to malloc for now.
// True stack allocation would need compiler intrinsic support.
#define alloca(size) malloc(size)
)EMBED"},
    {"arpa/inet.h", R"EMBED(// madc embedded arpa/inet.h — IPv4/IPv6 address conversion
// Functions (inet_addr, inet_aton, inet_ntoa, inet_pton, inet_ntop,
//            htons, htonl, ntohs, ntohl) available via dlsym fallback

#define INET_ADDRSTRLEN  16
#define INET6_ADDRSTRLEN 46
)EMBED"},
    {"arpa/telnet.h", R"EMBED(// madc embedded arpa/telnet.h — minimal TELNET protocol constants
// Mirrors the BSD/glibc subset used by typical text-MUD codebases.

#define IAC          255  // interpret as command
#define DONT         254
#define DO           253
#define WONT         252
#define WILL         251
#define SB           250  // sub-option begin
#define GA           249  // go-ahead
#define EL           248  // erase line
#define EC           247  // erase character
#define AYT          246  // are you there
#define AO           245  // abort output
#define IP           244  // interrupt process
#define BREAK        243
#define DM           242  // data mark
#define NOP          241
#define SE           240  // sub-option end
#define EOR          239  // end of record
#define ABORT        238
#define SUSP         237
#define xEOF         236

#define TELOPT_BINARY     0
#define TELOPT_ECHO       1
#define TELOPT_RCP        2
#define TELOPT_SGA        3
#define TELOPT_NAMS       4
#define TELOPT_STATUS     5
#define TELOPT_TM         6
#define TELOPT_RCTE       7
#define TELOPT_NAOL       8
#define TELOPT_NAOP       9
#define TELOPT_NAOCRD    10
#define TELOPT_NAOHTS    11
#define TELOPT_NAOHTD    12
#define TELOPT_NAOFFD    13
#define TELOPT_NAOVTS    14
#define TELOPT_NAOVTD    15
#define TELOPT_NAOLFD    16
#define TELOPT_XASCII    17
#define TELOPT_LOGOUT    18
#define TELOPT_BM        19
#define TELOPT_DET       20
#define TELOPT_TTYPE     24
#define TELOPT_NAWS      31
#define TELOPT_TSPEED    32
#define TELOPT_LFLOW     33
#define TELOPT_LINEMODE  34
#define TELOPT_AUTHENTICATION 37
#define TELOPT_ENCRYPT   38
#define TELOPT_NEW_ENVIRON 39
#define NTELOPTS         40
#define TELOPT_EXOPL     255
)EMBED"},
    {"assert.h", R"EMBED(// madc embedded assert.h — runtime assertions

#ifndef __MADC_ASSERT_H
#define __MADC_ASSERT_H 1

#load "libc.so.6" as __libc;

#ifdef NDEBUG
#define assert(expr) ((void)0)
#else
#define assert(expr) ((expr) ? (void)0 : abort())
#endif

#endif
)EMBED"},
    {"crypt.h", R"EMBED(// madc embedded crypt.h — POSIX password crypt
// libcrypt.so isn't part of glibc's RTLD_DEFAULT search, so #load it
// explicitly. Once loaded with RTLD_GLOBAL, dlsym(RTLD_DEFAULT, "crypt")
// resolves and the typed extern decl below routes the call through the
// existing dlsym late-bind path with proper char* return typing.

#load "libcrypt.so" as crypt_lib;

extern char *crypt(char *key, char *salt);
)EMBED"},
    {"ctype.h", R"EMBED(// madc embedded ctype.h — character classification and conversion
// All functions available via dlsym fallback (libc always loaded):
//   isalnum, isalpha, isblank, iscntrl, isdigit, isgraph,
//   islower, isprint, ispunct, isspace, isupper, isxdigit,
//   tolower, toupper, toascii
)EMBED"},
    {"dirent.h", R"EMBED(// madc embedded dirent.h — directory entry constants and struct layout.
// Functions (opendir, readdir, closedir, rewinddir, telldir, seekdir)
// available via dlsym fallback. DIR * is an opaque glibc type; treat the
// opendir return value as a void * / int64 handle and pass it verbatim to
// readdir / closedir.

// `DIR` is the opaque directory-handle type returned by opendir(). glibc
// exposes it via typedef but the underlying struct is implementation-
// internal; madc code only holds pointers to it, so a zero-size struct
// alias is sufficient — `DIR *dp;` parses as `struct __dir_opaque *dp;`.
typedef struct __dir_opaque DIR;

// d_type values (linux-specific, not portable across Unix — fall back to
// stat() if a value is DT_UNKNOWN).
#define DT_UNKNOWN 0
#define DT_FIFO    1
#define DT_CHR     2
#define DT_DIR     4
#define DT_BLK     6
#define DT_REG     8
#define DT_LNK     10
#define DT_SOCK    12
#define DT_WHT     14

// Function prototypes (needed by transpiler — JIT uses dlsym fallback)
DIR *opendir(const char *name);
struct dirent *readdir(DIR *dirp);
int closedir(DIR *dirp);
void rewinddir(DIR *dirp);
long telldir(DIR *dirp);
void seekdir(DIR *dirp, long loc);

// glibc x86-64 struct dirent — 280 bytes total (275 active + 5 trailing
// pad to the 8-byte struct alignment). d_name is declared as char[256]
// matching NAME_MAX + 1; readdir guarantees a null terminator.
struct dirent {
    uint64_t d_ino;      // inode number
    int64_t  d_off;      // offset to next dirent (opaque — do not interpret)
    uint16_t d_reclen;   // length of this record
    uint8_t  d_type;     // DT_* file-type hint (DT_UNKNOWN if not provided)
    char     d_name[256]; // null-terminated filename
};
)EMBED"},
    {"dlfcn.h", R"EMBED(// madc embedded dlfcn.h — dynamic linking constants
// Note: dlopen/dlsym/dlclose/dlerror are first-class in madc via #load
// These constants are for use with explicit dlopen() calls

#define RTLD_LAZY     0x00001
#define RTLD_NOW      0x00002
#define RTLD_GLOBAL   0x00100
#define RTLD_LOCAL    0x00000
#define RTLD_NOLOAD   0x00004
#define RTLD_DEEPBIND 0x00008
#define RTLD_NODELETE 0x01000
)EMBED"},
    {"errno.h", R"EMBED(// madc embedded errno.h — POSIX error constants
// glibc exposes errno via __errno_location(), so mirror the usual macro.
// Keep the function undeclared here and let madc resolve it through the
// normal external-call path when the macro expands.
#define errno (*(__errno_location()))

// Base POSIX errors
#define EPERM             1
#define ENOENT            2
#define ESRCH             3
#define EINTR             4
#define EIO               5
#define ENXIO             6
#define E2BIG             7
#define ENOEXEC           8
#define EBADF             9
#define ECHILD            10
#define EAGAIN            11
#define EWOULDBLOCK       11
#define ENOMEM            12
#define EACCES            13
#define EFAULT            14
#define EBUSY             16
#define EEXIST            17
#define EXDEV             18
#define ENODEV            19
#define ENOTDIR           20
#define EISDIR            21
#define EINVAL            22
#define ENFILE            23
#define EMFILE            24
#define ENOTTY            25
#define ETXTBSY           26
#define EFBIG             27
#define ENOSPC            28
#define ESPIPE            29
#define EROFS             30
#define EMLINK            31
#define EPIPE             32
#define EDOM              33
#define ERANGE            34

// System V / extended POSIX errors
#define EDEADLK           35
#define ENAMETOOLONG      36
#define ENOLCK            37
#define ENOSYS            38
#define ENOTEMPTY         39
#define ELOOP             40
#define ENOMSG            42
#define ENODATA           61
#define EOVERFLOW         75
#define EILSEQ            84

// Socket / network errors (Linux x86-64 values)
#define EUSERS            87
#define ENOTSOCK          88
#define EDESTADDRREQ      89
#define EMSGSIZE          90
#define EPROTOTYPE        91
#define ENOPROTOOPT       92
#define EPROTONOSUPPORT   93
#define ESOCKTNOSUPPORT   94
#define EOPNOTSUPP        95
#define EPFNOSUPPORT      96
#define EAFNOSUPPORT      97
#define EADDRINUSE        98
#define EADDRNOTAVAIL     99
#define ENETDOWN          100
#define ENETUNREACH       101
#define ENETRESET         102
#define ECONNABORTED      103
#define ECONNRESET        104
#define ENOBUFS           105
#define EISCONN           106
#define ENOTCONN          107
#define ESHUTDOWN         108
#define ETIMEDOUT         110
#define ECONNREFUSED      111
#define EHOSTDOWN         112
#define EHOSTUNREACH      113
#define EALREADY          114
#define EINPROGRESS       115
#define ESTALE            116
#define EDQUOT            122
)EMBED"},
    {"fcntl.h", R"EMBED(// madc embedded fcntl.h — file control constants (Linux x86-64 values)
// Functions (open, creat, fcntl) available via dlsym fallback

#define O_RDONLY     0
#define O_WRONLY     1
#define O_RDWR       2
#define O_CREAT      64
#define O_EXCL       128
#define O_NOCTTY     256
#define O_TRUNC      512
#define O_APPEND     1024
#define O_NONBLOCK   2048
#define O_NDELAY     2048
#define O_DSYNC      4096
#define O_ASYNC      8192
#define O_DIRECTORY  65536
#define O_NOFOLLOW   131072
#define O_SYNC       1052672
#define O_CLOEXEC    524288

#define F_DUPFD           0
#define F_GETFD           1
#define F_SETFD           2
#define F_GETFL           3
#define F_SETFL           4
#define F_GETLK           5
#define F_SETLK           6
#define F_SETLKW          7
#define F_SETOWN          8
#define F_GETOWN          9
#define F_DUPFD_CLOEXEC   1030

#define FD_CLOEXEC   1
)EMBED"},
    {"float.h", R"EMBED(// madc embedded float.h — floating-point characteristics for host x86-64

#ifndef __MADC_FLOAT_H
#define __MADC_FLOAT_H 1

#define FLT_RADIX 2
#define FLT_EVAL_METHOD 0
#define DECIMAL_DIG 21

#define FLT_MANT_DIG 24
#define DBL_MANT_DIG 53
#define LDBL_MANT_DIG 64

#define FLT_DIG 6
#define DBL_DIG 15
#define LDBL_DIG 18

#define FLT_MIN_EXP (-125)
#define DBL_MIN_EXP (-1021)
#define LDBL_MIN_EXP (-16381)

#define FLT_MIN_10_EXP (-37)
#define DBL_MIN_10_EXP (-307)
#define LDBL_MIN_10_EXP (-4931)

#define FLT_MAX_EXP 128
#define DBL_MAX_EXP 1024
#define LDBL_MAX_EXP 16384

#define FLT_MAX_10_EXP 38
#define DBL_MAX_10_EXP 308
#define LDBL_MAX_10_EXP 4932

#define FLT_MAX 3.40282346638528859811704183484516925e+38F
#define DBL_MAX ((double)1.79769313486231570814527423731704357e+308L)
#define LDBL_MAX 1.18973149535723176502126385303097021e+4932L

#define FLT_MIN 1.17549435082228750796873653722224568e-38F
#define DBL_MIN ((double)2.22507385850720138309023271733240406e-308L)
#define LDBL_MIN 3.36210314311209350626267781732175260e-4932L

#define FLT_EPSILON 1.19209289550781250000000000000000000e-7F
#define DBL_EPSILON ((double)2.22044604925031308084726333618164062e-16L)
#define LDBL_EPSILON 1.08420217248550443400745280086994171e-19L

#endif
)EMBED"},
    {"fnmatch.h", R"EMBED(// madc embedded fnmatch.h — filename pattern matching
// Functions (fnmatch) available via dlsym fallback

// fnmatch() flags
#define FNM_NOESCAPE    0x01
#define FNM_PATHNAME    0x02
#define FNM_PERIOD      0x04
#define FNM_FILE_NAME   0x02
#define FNM_LEADING_DIR 0x08
#define FNM_CASEFOLD    0x10
#define FNM_EXTMATCH    0x20

// fnmatch() return values
#define FNM_NOMATCH 1
)EMBED"},
    {"fstream", R"EMBED(// madc embedded <fstream> — std::ofstream / std::ifstream as header-defined
// classes that bind to the REAL libstdc++ Itanium symbols (the Cfront model:
// madc emits no method bodies; the linker resolves them against libstdc++).
//
// WORK IN PROGRESS — retire-std-hardcoding campaign, replacing the builtin
// stream registration and its extern-C wrappers with header-defined classes. Staged:
//   inc 4 (here): the basic_* templates + their offset-0 nullary methods
//                 (ctor/dtor/close/is_open) — these match libstdc++ exactly and
//                 bind via the generic header-defined-class keystone.
//   inc 5: the real ios_base/basic_ios/basic_ostream/basic_istream base
//          hierarchy + the basic_ios virtual-base this-offset, so good()/eof()
//          (and <<) resolve; open(const char*, openmode); layout-faithful sizes.
//   inc 6: the `ofstream`/`ifstream`/`fstream` typedefs + DELETE the builtins.
//
// char_traits is declared here as the std:: template the stream args name; it
// will move to a shared bits header when std::string migrates.

namespace std {
    template<typename _CharT> class char_traits { char _M_dummy; };

    template<typename _CharT, typename _Traits> class basic_ofstream {
	// Opaque storage placeholder — the real layout (ostream base + filebuf,
	// basic_ios virtual base) lands in inc 5. Size does not affect the mangled
	// method symbols, only object allocation/layout (validated by a doctest).
	long _M_storage[63];
    public:
	basic_ofstream();
	~basic_ofstream();
	void close();
	bool is_open();
    };

    template<typename _CharT, typename _Traits> class basic_ifstream {
	long _M_storage[64];
    public:
	basic_ifstream();
	~basic_ifstream();
	void close();
	bool is_open();
    };
}
)EMBED"},
    {"glob.h", R"EMBED(// madc embedded glob.h — filename expansion
// Functions (glob, globfree) available via dlsym fallback
// struct glob_t access deferred

// glob() flags
#define GLOB_ERR      0x0001
#define GLOB_MARK     0x0002
#define GLOB_NOSORT   0x0004
#define GLOB_DOOFFS   0x0008
#define GLOB_NOCHECK  0x0010
#define GLOB_APPEND   0x0020
#define GLOB_NOESCAPE 0x0040
#define GLOB_PERIOD   0x0080
#define GLOB_ALTDIRFUNC 0x0100
#define GLOB_BRACE    0x0200
#define GLOB_NOMAGIC  0x0400
#define GLOB_TILDE    0x0800
#define GLOB_ONLYDIR  0x1000
#define GLOB_TILDE_CHECK 0x2000

// glob() return values (success = 0)
#define GLOB_NOSPACE 1
#define GLOB_ABORTED 2
#define GLOB_NOMATCH 3
)EMBED"},
    {"grp.h", R"EMBED(// madc embedded grp.h — group database
// Functions (getgrgid, getgrnam, getgrent, setgrent, endgrent)
// available via dlsym fallback
// struct group access deferred
)EMBED"},
    {"iostream", R"EMBED(// madc embedded iostream — registers cout, cin, cerr, endl
// The actual registration is handled by add_iostream() callback
)EMBED"},
    {"limits.h", R"EMBED(// madc embedded limits.h — integer limit constants

#define CHAR_BIT  8
#define SCHAR_MIN -128
#define SCHAR_MAX 127
#define UCHAR_MAX 255
#define SHRT_MIN  -32768
#define SHRT_MAX  32767
#define USHRT_MAX 65535
#define INT_MIN   -2147483648
#define INT_MAX   2147483647
#define UINT_MAX  4294967295U
#define LONG_MIN  -9223372036854775807L
#define LONG_MAX  9223372036854775807L
#define ULONG_MAX 18446744073709551615UL
#define LLONG_MIN -9223372036854775807LL
#define LLONG_MAX 9223372036854775807LL
#define ULLONG_MAX 18446744073709551615ULL
#define CHAR_MIN  -128
#define CHAR_MAX  127
#define PATH_MAX  4096
#define NAME_MAX  255
)EMBED"},
    {"locale.h", R"EMBED(// madc embedded locale.h — locale constants
// Functions (setlocale, localeconv) available via dlsym fallback

#define LC_ALL       6
#define LC_COLLATE   3
#define LC_CTYPE     0
#define LC_MESSAGES  5
#define LC_MONETARY  4
#define LC_NUMERIC   1
#define LC_TIME      2
)EMBED"},
    {"malloc.h", R"EMBED(// madc embedded malloc.h — memory allocation
// malloc/free/realloc/calloc are already available via dlsym fallback.
// This stub satisfies #include <malloc.h>.

#ifndef __MADC_MALLOC_H
#define __MADC_MALLOC_H 1

#include <stdlib.h>

#endif
)EMBED"},
    {"map", R"EMBED(// madc embedded <map> — std::map<K,V> as a real madc template.
//
// std::map is an ordinary std::-namespaced madc template, instantiated per
// use by the template-instantiation engine (Borland monomorphization). It is
// NOT a lexer keyword and NOT a libstdc++ wrapper — it is madc's own STL
// container, defined here and compiled through the class model.
//
// Implementation: parallel arrays of keys/values with linear search (madc's
// own simple map, not a balanced tree). String keys compare via std::string
// operator== (bound to the extern-C runtime wrapper string_equals, since
// libstdc++'s std::operator== for strings is an inlined weak template symbol
// that is not dlsym-exportable). The header instantiates per K, so only the
// matching code is compiled; no scalar-key test exists.
//
// The search loop is inlined into each method rather than factored into a
// private __find(): madc does not yet support an unqualified sibling-method
// call from inside a class method (`__find(k)` -> "undeclared identifier").
// An operator on a subscript element (`keys[i] == k`) IS now a supported parse
// form, so each search compares the key directly (no copy-to-local).
#include <stdlib.h>
#include <string.h>
namespace std {
template<typename K, typename V> class map {
    K* keys;
    V* vals;
    long len;
    long cap;
public:
    map() {
	keys = (K*)malloc(4 * sizeof(K));
	vals = (V*)malloc(4 * sizeof(V));
	len = 0;
	cap = 4;
    }
    ~map() {
	// Destruct each live key and value before releasing the buffers, as
	// std::map does (destroy every node's key+value, then deallocate).
	// __destroy is the element-type-driven destroy intrinsic: it calls the
	// class dtor for an object key/value (string -> ~basic_string) and is a
	// no-op for a scalar/pointer K/V. Pointer arith (keys + i / vals + i),
	// NOT &keys[i] (member-subscript parser gap).
	long i = 0;
	while ( i < len ) { __destroy(keys + i); __destroy(vals + i); i = i + 1; }
	free(keys);
	free(vals);
    }
    void put(K k, V v) {
	long i = 0;
	while ( i < len ) {
	    if ( keys[i] == k ) {
		V* vslot = vals + i;	// pointer arith (NOT &vals[i] — parser gap)
		new (vslot) V(v);	// overwrite value in place
		return;
	    }
	    i = i + 1;
	}
	if ( len >= cap ) {
	    cap = cap * 2;
	    keys = (K*)realloc(keys, cap * sizeof(K));
	    vals = (V*)realloc(vals, cap * sizeof(V));
	}
	K* kslot = keys + len;
	V* vslot = vals + len;
	new (kslot) K(k);		// placement copy-construct (works for string)
	new (vslot) V(v);
	len = len + 1;
    }
    V get(K k) {
	long i = 0;
	while ( i < len ) {
	    if ( keys[i] == k )
		return vals[i];
	    i = i + 1;
	}
	return vals[0];
    }
    int contains(K k) {
	long i = 0;
	while ( i < len ) {
	    if ( keys[i] == k )
		return 1;
	    i = i + 1;
	}
	return 0;
    }
    long size() { return len; }
    V& operator[](K k) {
	long i = 0;
	while ( i < len ) {
	    if ( keys[i] == k )
		return vals[i];
	    i = i + 1;
	}
	if ( len >= cap ) {
	    cap = cap * 2;
	    keys = (K*)realloc(keys, cap * sizeof(K));
	    vals = (V*)realloc(vals, cap * sizeof(V));
	}
	K* kslot = keys + len;
	V* vslot = vals + len;
	new (kslot) K(k);
	new (vslot) V();		// default-construct the value slot
	long at = len;
	len = len + 1;
	return vals[at];
    }
};
}
)EMBED"},
    {"math.h", R"EMBED(// madc embedded math.h — auto-loads libm and defines math constants
#load "libm.so.6" as libm;

#define M_PI       3.14159265358979323846
#define M_PI_2     1.57079632679489661923
#define M_PI_4     0.78539816339744830962
#define M_E        2.71828182845904523536
#define M_LOG2E    1.44269504088896340736
#define M_LOG10E   0.43429448190325182765
#define M_LN2      0.69314718055994530942
#define M_LN10     2.30258509299404568402
#define M_SQRT2    1.41421356237309504880
#define M_SQRT1_2  0.70710678118654752440
#define HUGE_VAL   __builtin_huge_val()
#define INFINITY   __builtin_inf()

// Declare the real return types for the libm family. Without these, a libm
// function resolves through the dlsym fallback with a generic 64-bit (long)
// return signature — so the floating-point result (returned in xmm0) is read
// out of the integer return register instead, producing garbage (e.g.
// pow(32.0, 1.0/3.0) read as 4.61e18 instead of 3.1748). This is the same
// return-type bug that the string.h comparison family fixed (strcmp -> int),
// here extended to the double / float / long double libm functions.
//
// Standard C99 trig / exponential / power / rounding functions: double,
// float ("f" suffix) and long double ("l" suffix) variants.

// Trigonometric
extern double sin(double x);
extern double cos(double x);
extern double tan(double x);
extern double asin(double x);
extern double acos(double x);
extern double atan(double x);
extern double atan2(double y, double x);
extern float sinf(float x);
extern float cosf(float x);
extern float tanf(float x);
extern float asinf(float x);
extern float acosf(float x);
extern float atanf(float x);
extern float atan2f(float y, float x);
extern long double sinl(long double x);
extern long double cosl(long double x);
extern long double tanl(long double x);
extern long double asinl(long double x);
extern long double acosl(long double x);
extern long double atanl(long double x);
extern long double atan2l(long double y, long double x);

// Hyperbolic
extern double sinh(double x);
extern double cosh(double x);
extern double tanh(double x);
extern double asinh(double x);
extern double acosh(double x);
extern double atanh(double x);
extern float sinhf(float x);
extern float coshf(float x);
extern float tanhf(float x);
extern float asinhf(float x);
extern float acoshf(float x);
extern float atanhf(float x);
extern long double sinhl(long double x);
extern long double coshl(long double x);
extern long double tanhl(long double x);
extern long double asinhl(long double x);
extern long double acoshl(long double x);
extern long double atanhl(long double x);

// Exponential / logarithmic
extern double exp(double x);
extern double exp2(double x);
extern double expm1(double x);
extern double log(double x);
extern double log2(double x);
extern double log10(double x);
extern double log1p(double x);
extern double logb(double x);
extern float expf(float x);
extern float exp2f(float x);
extern float expm1f(float x);
extern float logf(float x);
extern float log2f(float x);
extern float log10f(float x);
extern float log1pf(float x);
extern float logbf(float x);
extern long double expl(long double x);
extern long double exp2l(long double x);
extern long double expm1l(long double x);
extern long double logl(long double x);
extern long double log2l(long double x);
extern long double log10l(long double x);
extern long double log1pl(long double x);
extern long double logbl(long double x);

// Power / roots
extern double pow(double x, double y);
extern double sqrt(double x);
extern double cbrt(double x);
extern double hypot(double x, double y);
extern float powf(float x, float y);
extern float sqrtf(float x);
extern float cbrtf(float x);
extern float hypotf(float x, float y);
extern long double powl(long double x, long double y);
extern long double sqrtl(long double x);
extern long double cbrtl(long double x);
extern long double hypotl(long double x, long double y);

// Rounding / remainder / absolute value
extern double ceil(double x);
extern double floor(double x);
extern double trunc(double x);
extern double round(double x);
extern double nearbyint(double x);
extern double rint(double x);
extern double fabs(double x);
extern double fmod(double x, double y);
extern double remainder(double x, double y);
extern double copysign(double x, double y);
extern double nextafter(double x, double y);
extern double fdim(double x, double y);
extern double fmax(double x, double y);
extern double fmin(double x, double y);
extern double fma(double x, double y, double z);
extern float ceilf(float x);
extern float floorf(float x);
extern float truncf(float x);
extern float roundf(float x);
extern float nearbyintf(float x);
extern float rintf(float x);
extern float fabsf(float x);
extern float fmodf(float x, float y);
extern float remainderf(float x, float y);
extern float copysignf(float x, float y);
extern float nextafterf(float x, float y);
extern float fdimf(float x, float y);
extern float fmaxf(float x, float y);
extern float fminf(float x, float y);
extern float fmaf(float x, float y, float z);
extern long double ceill(long double x);
extern long double floorl(long double x);
extern long double truncl(long double x);
extern long double roundl(long double x);
extern long double nearbyintl(long double x);
extern long double rintl(long double x);
extern long double fabsl(long double x);
extern long double fmodl(long double x, long double y);
extern long double remainderl(long double x, long double y);
extern long double copysignl(long double x, long double y);
extern long double nextafterl(long double x, long double y);
extern long double fdiml(long double x, long double y);
extern long double fmaxl(long double x, long double y);
extern long double fminl(long double x, long double y);
extern long double fmal(long double x, long double y, long double z);

// Decomposition / scaling (take pointer / int args, still return floating)
extern double modf(double x, double *iptr);
extern double frexp(double x, int *exp);
extern double ldexp(double x, int exp);
extern double scalbn(double x, int n);
extern float modff(float x, float *iptr);
extern float frexpf(float x, int *exp);
extern float ldexpf(float x, int exp);
extern float scalbnf(float x, int n);
extern long double modfl(long double x, long double *iptr);
extern long double frexpl(long double x, int *exp);
extern long double ldexpl(long double x, int exp);
extern long double scalbnl(long double x, int n);

// Gamma / error functions
extern double tgamma(double x);
extern double lgamma(double x);
extern double erf(double x);
extern double erfc(double x);
extern float tgammaf(float x);
extern float lgammaf(float x);
extern float erff(float x);
extern float erfcf(float x);
extern long double tgammal(long double x);
extern long double lgammal(long double x);
extern long double erfl(long double x);
extern long double erfcl(long double x);

// Integer-returning math functions (NOT floating return)
extern int ilogb(double x);
extern int ilogbf(float x);
extern int ilogbl(long double x);
extern long lrint(double x);
extern long lround(double x);
extern long long llrint(double x);
extern long long llround(double x);
)EMBED"},
    {"netdb.h", R"EMBED(// madc embedded netdb.h — network database constants
// Functions (getaddrinfo, freeaddrinfo, gai_strerror, getnameinfo,
//            gethostbyname, getservbyname, getservbyport, gethostname)
// available via dlsym fallback
// struct addrinfo / hostent access deferred

// getaddrinfo() flags
#define AI_PASSIVE      0x0001
#define AI_CANONNAME    0x0002
#define AI_NUMERICHOST  0x0004
#define AI_V4MAPPED     0x0008
#define AI_ALL          0x0010
#define AI_ADDRCONFIG   0x0020
#define AI_NUMERICSERV  0x0400

// getnameinfo() flags
#define NI_NUMERICHOST  1
#define NI_NUMERICSERV  2
#define NI_NOFQDN       4
#define NI_NAMEREQD     8
#define NI_DGRAM        16
#define NI_MAXHOST      1025
#define NI_MAXSERV      32

// getaddrinfo() error codes
#define EAI_BADFLAGS    -1
#define EAI_NONAME      -2
#define EAI_AGAIN       -3
#define EAI_FAIL        -4
#define EAI_FAMILY      -6
#define EAI_SOCKTYPE    -7
#define EAI_SERVICE     -8
#define EAI_MEMORY      -10
#define EAI_SYSTEM      -11
#define EAI_OVERFLOW    -12

// glibc x86-64 struct hostent — 32 bytes, natural C ABI alignment.
// Returned by gethostbyname() / gethostbyaddr().
struct hostent {
    char  *h_name;          // official name of host
    char **h_aliases;       // NULL-terminated alias list
    int    h_addrtype;      // host address type (AF_INET / AF_INET6)
    int    h_length;        // length of address (4 for v4, 16 for v6)
    char **h_addr_list;     // NULL-terminated array of pointers to addresses
};
#define h_addr h_addr_list[0]   // legacy single-address alias

// glibc x86-64 struct servent — 32 bytes, natural C ABI alignment.
// Returned by getservbyname() / getservbyport(). s_port holds the port
// in network byte order — use ntohs() to get a host-order integer.
// s_aliases is a NULL-terminated array of alternate service names.
// s_proto is typically "tcp" or "udp".
struct servent {
    char  *s_name;      // official service name
    char **s_aliases;   // NULL-terminated list of aliases
    int    s_port;      // port number (network byte order)
    char  *s_proto;     // protocol name
};

// Function prototypes (needed by transpiler — JIT uses dlsym fallback)
struct hostent *gethostbyname(const char *name);
struct hostent *gethostbyaddr(const void *addr, uint32_t len, int type);
struct servent *getservbyname(const char *name, const char *proto);
struct servent *getservbyport(int port, const char *proto);
int gethostname(char *name, uint64_t len);
)EMBED"},
    {"netinet/in.h", R"EMBED(// madc embedded netinet/in.h — IP protocol constants and struct layouts.
// Functions (htons, htonl, ntohs, ntohl, inet_addr, inet_ntoa) available
// via dlsym fallback.

// IP protocols
#define IPPROTO_IP      0
#define IPPROTO_ICMP    1
#define IPPROTO_TCP     6
#define IPPROTO_UDP     17
#define IPPROTO_IPV6    41
#define IPPROTO_RAW     255

// Special IPv4 addresses (network byte order — use htonl() at runtime)
#define INADDR_ANY       0x00000000
#define INADDR_BROADCAST 0xffffffff
#define INADDR_LOOPBACK  0x7f000001
#define INADDR_NONE      0xffffffff

// IPv6 address length
#define IN6ADDR_ANY_INIT 0

// Port range
#define IPPORT_RESERVED 1024

// TCP socket options (for setsockopt with IPPROTO_TCP)
#define TCP_NODELAY     1
#define TCP_MAXSEG      2
#define TCP_KEEPIDLE    4
#define TCP_KEEPINTVL   5
#define TCP_KEEPCNT     6

// POSIX type aliases for network-order field widths.
#define sa_family_t uint16_t
#define in_port_t   uint16_t
#define in_addr_t   uint32_t
#define socklen_t   uint32_t

// glibc x86-64 struct in_addr — 4 bytes: a single uint32 in network order.
struct in_addr {
    uint32_t s_addr;
};

// glibc x86-64 struct sockaddr_in — 16 bytes, natural C ABI alignment.
// sin_addr occupies 4 bytes starting at offset 4; sin_zero is the 8-byte
// padding that makes sockaddr_in and sockaddr (BSD base) the same size for
// the traditional bind()/connect() cast trick.
struct sockaddr_in {
    uint16_t sin_family;    // AF_INET
    uint16_t sin_port;      // network byte order — use htons()
    struct in_addr sin_addr;
    int64_t  sin_zero;      // glibc declares as char[8]; same 8-byte padding
};
)EMBED"},
    {"netinet/in_systm.h", R"EMBED(// madc embedded netinet/in_systm.h — Internet system types
// Historical BSD networking compatibility header. Most code only
// needs the n_* type aliases.

#define n_short  int16_t
#define n_long   int32_t
#define n_time   int32_t
)EMBED"},
    {"netinet/ip.h", R"EMBED(// madc embedded netinet/ip.h — minimal IP header stub
// Most user code that includes this just expects the protocol
// constants; the struct ip layout is only needed by raw-socket code.
// Pull in netinet/in.h for the protocol numbers.

#include <netinet/in.h>
)EMBED"},
    {"poll.h", R"EMBED(// madc embedded poll.h — poll() I/O multiplexing
// Functions (poll, ppoll) available via dlsym fallback
// struct pollfd access deferred (requires struct interop)

// Events to poll for (events / revents bitmask)
#define POLLIN   0x001
#define POLLPRI  0x002
#define POLLOUT  0x004
#define POLLERR  0x008
#define POLLHUP  0x010
#define POLLNVAL 0x020
#define POLLRDHUP 0x2000
)EMBED"},
    {"pthread.h", R"EMBED(// madc embedded pthread.h — POSIX threads
// On Linux (glibc 2.34+) pthread functions are in libc — dlsym fallback works.
// On older systems, use: #load "libpthread.so.0" as pthread;
// Functions: pthread_create, pthread_join, pthread_detach, pthread_self,
//            pthread_exit, pthread_cancel, pthread_equal,
//            pthread_mutex_init, pthread_mutex_lock, pthread_mutex_trylock,
//            pthread_mutex_unlock, pthread_mutex_destroy,
//            pthread_cond_init, pthread_cond_wait, pthread_cond_signal,
//            pthread_cond_broadcast, pthread_cond_destroy,
//            pthread_attr_init, pthread_attr_destroy,
//            pthread_attr_setdetachstate, pthread_attr_getstacksize,
//            pthread_rwlock_init, pthread_rwlock_rdlock,
//            pthread_rwlock_wrlock, pthread_rwlock_unlock,
//            pthread_rwlock_destroy
// struct pthread_mutex_t / pthread_cond_t / pthread_attr_t deferred

// Thread creation attributes
#define PTHREAD_CREATE_JOINABLE  0
#define PTHREAD_CREATE_DETACHED  1

// Mutex type attributes
#define PTHREAD_MUTEX_TIMED_NP     0
#define PTHREAD_MUTEX_DEFAULT      0
#define PTHREAD_MUTEX_RECURSIVE    1
#define PTHREAD_MUTEX_ERRORCHECK   2
#define PTHREAD_MUTEX_ADAPTIVE_NP  3

// Process sharing
#define PTHREAD_PROCESS_PRIVATE 0
#define PTHREAD_PROCESS_SHARED  1

// Cancellation
#define PTHREAD_CANCEL_ENABLE   0
#define PTHREAD_CANCEL_DISABLE  1
#define PTHREAD_CANCEL_DEFERRED 0
#define PTHREAD_CANCEL_ASYNCHRONOUS 1
#define PTHREAD_CANCELED ((int64_t)-1)

// Scope
#define PTHREAD_SCOPE_SYSTEM  0
#define PTHREAD_SCOPE_PROCESS 1

// pthread_t type alias
#define pthread_t int64_t
)EMBED"},
    {"pwd.h", R"EMBED(// madc embedded pwd.h — password database
// Functions (getpwuid, getpwnam, getpwent, setpwent, endpwent, getlogin)
// available via dlsym fallback

#ifndef _PWD_H
#define _PWD_H 1

typedef unsigned int __uid_t;
typedef unsigned int __gid_t;

struct passwd
{
  char *pw_name;
  char *pw_passwd;
  __uid_t pw_uid;
  __gid_t pw_gid;
  char *pw_gecos;
  char *pw_dir;
  char *pw_shell;
};

#endif
)EMBED"},
    {"regex.h", R"EMBED(#ifndef __MADC_REGEX_H
#define __MADC_REGEX_H 1

#include <sys/types.h>

/*
 * Minimal POSIX regex declarations for source compatibility.
 * Extend this if upstream code starts using regex_t/regcomp/regexec directly.
 */

typedef long regoff_t;

typedef struct
{
    regoff_t rm_so;
    regoff_t rm_eo;
} regmatch_t;

typedef struct
{
    void *buffer;
    size_t allocated;
    size_t used;
    uint32_t re_nsub;
} regex_t;

#define REG_EXTENDED 1
#define REG_ICASE 2
#define REG_NOSUB 4
#define REG_NEWLINE 8

#define REG_NOTBOL 1
#define REG_NOTEOL 2

#define REG_NOERROR 0
#define REG_NOMATCH 1

int regcomp(regex_t *preg, const char *pattern, int cflags);
int regexec(const regex_t *preg, const char *string, size_t nmatch, regmatch_t pmatch[], int eflags);
size_t regerror(int errcode, const regex_t *preg, char *errbuf, size_t errbuf_size);
void regfree(regex_t *preg);

#endif
)EMBED"},
    {"resolv.h", R"EMBED(// madc embedded resolv.h — DNS resolver
// b64_ntop / b64_pton and resolver functions available via dlsym.

#ifndef __MADC_RESOLV_H
#define __MADC_RESOLV_H 1

#include <sys/types.h>

extern int b64_ntop(const unsigned char *src, int srclength,
                    char *target, int targsize);
extern int b64_pton(const char *src, unsigned char *target, int targsize);

#endif
)EMBED"},
    {"set", R"EMBED(// madc embedded <set> — std::set<T> as a real madc template.
//
// std::set is an ordinary std::-namespaced madc template, instantiated per use
// by the template-instantiation engine (Borland monomorphization). It is NOT a
// lexer keyword and NOT a libstdc++ wrapper — it is madc's own STL container,
// defined here and compiled through the class model.
//
// Implementation: a flat array with linear search (madc's own simple set, not
// a balanced tree). insert() dedups. String elements compare via std::string
// operator== (bound to the extern-C runtime wrapper string_equals, since
// libstdc++'s std::operator== for strings is an inlined weak template symbol
// that is not dlsym-exportable). The search loop is inlined into each method
// rather than factored into a private __find(): madc does not yet support an
// unqualified sibling-method call from inside a class method. An operator on a
// subscript element (`data[i] == v`) IS now a supported parse form, so the
// search compares the element directly (no copy-to-local).
#include <stdlib.h>
#include <string.h>
namespace std {
template<typename T> class set {
    T* data;
    long len;
    long cap;
public:
    set() { data = (T*)malloc(4 * sizeof(T)); len = 0; cap = 4; }
    ~set() {
	// Destruct each live element before releasing the buffer (see <vector>
	// for the __destroy element-destroy intrinsic; no-op for scalar T).
	long i = 0;
	while ( i < len ) { __destroy(data + i); i = i + 1; }
	free(data);
    }
    void insert(T v) {
	long i = 0;
	while ( i < len ) {
	    if ( data[i] == v )
		return;			// dedup: element already present
	    i = i + 1;
	}
	if ( len >= cap ) {
	    cap = cap * 2;
	    data = (T*)realloc(data, cap * sizeof(T));
	}
	T* slot = data + len;		// pointer arith (NOT &data[len] — parser gap)
	new (slot) T(v);		// placement copy-construct (works for string)
	len = len + 1;
    }
    int contains(T v) {
	long i = 0;
	while ( i < len ) {
	    if ( data[i] == v )
		return 1;
	    i = i + 1;
	}
	return 0;
    }
    long size() { return len; }
};
}
)EMBED"},
    {"signal.h", R"EMBED(// madc embedded signal.h — POSIX signal constants (Linux values)
// Functions (kill, signal, raise, sigaction) available via dlsym fallback

#define SIGHUP  1
#define SIGINT  2
#define SIGQUIT 3
#define SIGILL  4
#define SIGTRAP 5
#define SIGABRT 6
#define SIGBUS  7
#define SIGFPE  8
#define SIGKILL 9
#define SIGUSR1 10
#define SIGSEGV 11
#define SIGUSR2 12
#define SIGPIPE 13
#define SIGALRM 14
#define SIGTERM 15
#define SIGCHLD 17
#define SIGCONT 18
#define SIGSTOP 19
#define SIGTSTP 20

// Signal dispositions (passed as handler arg to signal())
#define SIG_DFL 0
#define SIG_IGN 1
)EMBED"},
    {"stdarg.h", R"EMBED(// madc embedded stdarg.h — variadic function support
//
// Matches the x86-64 System V ABI exactly as gcc/c2mir set it up (see
// c2mir's mirc_x86_64_stdarg.h): va_list is the real __va_list_tag[1] struct,
// and the ABI work is done by the compiler intrinsic __builtin_va_start.
//
// The user's
//   va_list ap; va_start(ap, last);
// lowers directly to c2mir's intrinsic __builtin_va_start(ap), which takes the
// va_list alone and derives the named-argument count from the enclosing
// function's signature — exactly c2mir's own mirc_x86_64_stdarg.h idiom.
// (An earlier model primed a hidden function-entry `__va_args` master and
// copied it per use site — `(ap)[0] = (__va_args)[0]` — but that extra
// va_list struct copy left reg_save_area mis-set in large/complex frames,
// corrupting the list; invoking the intrinsic on the user's own va_list
// avoids the copy and the corruption.)

typedef struct __madc_va_list_tag {
	unsigned int gp_offset;
	unsigned int fp_offset;
	void *overflow_arg_area;
	void *reg_save_area;
} va_list[1];

#define va_start(ap, last) __builtin_va_start(ap)
#define va_end(ap) ((void)(ap))
#define va_copy(dest, src) ((dest)[0] = (src)[0])

// va_list is now the real ABI struct, so the v*printf family resolve to the
// real libc functions (which take a va_list) — not the old __madc_* helpers
// that unpacked a custom int64_t[] buffer.
int vsprintf(char *, const char *, va_list);
int vsnprintf(char *, unsigned long, const char *, va_list);
int vfprintf(void *, const char *, va_list);
int vprintf(const char *, va_list);
)EMBED"},
    {"stdbool.h", R"EMBED(// madc embedded stdbool.h

#define bool _Bool
#define true 1
#define false 0
#define __bool_true_false_are_defined 1
)EMBED"},
    {"stddef.h", R"EMBED(// madc embedded stddef.h — standard definitions
// size_t and ptrdiff_t are already native madc types via typedef
// This header provides NULL, offsetof, and max_align_t

#ifndef __MADC_STDDEF_H
#define __MADC_STDDEF_H 1

#ifndef NULL
#define NULL ((void *)0)
#endif

#define offsetof(type, member) ((unsigned long)&((type *)0)->member)

typedef long ptrdiff_t;
typedef unsigned long size_t;
typedef int wchar_t;

#endif
)EMBED"},
    {"stdint.h", R"EMBED(// madc embedded stdint.h — exact-width integer types
// Note: int8_t through uint64_t are native madc types
// This header provides the min/max constants for completeness

#define INT8_MIN    -128
#define INT8_MAX    127
#define UINT8_MAX   255
#define INT16_MIN   -32768
#define INT16_MAX   32767
#define UINT16_MAX  65535
#define INT32_MIN   -2147483648
#define INT32_MAX   2147483647
#define UINT32_MAX  4294967295
#define INT64_MIN   -9223372036854775807
#define INT64_MAX   9223372036854775807
#define UINT64_MAX  0xFFFFFFFFFFFFFFFF
#define SIZE_MAX    0xFFFFFFFFFFFFFFFF
#define INTMAX_MIN  -9223372036854775807
#define INTMAX_MAX  9223372036854775807
#define UINTMAX_MAX 0xFFFFFFFFFFFFFFFF
#define PTRDIFF_MIN -9223372036854775807
#define PTRDIFF_MAX 9223372036854775807

typedef long int intptr_t;
typedef unsigned long int uintptr_t;
)EMBED"},
    {"stdio.h", R"EMBED(// madc embedded stdio.h — C standard I/O
// printf/fprintf/sprintf/snprintf are available via dlsym fallback (libc is always loaded)
// FILE is treated as an opaque pointer-like type in madc source.

#define EOF    -1
#define SEEK_SET 0
#define SEEK_CUR 1
#define SEEK_END 2
#define BUFSIZ 8192
#define NULL 0
#define FILE void
#ifndef _SIZE_T_DEFINED
#define _SIZE_T_DEFINED
#define size_t uint64_t
#endif
)EMBED"},
    {"stdlib.h", R"EMBED(// madc embedded stdlib.h — standard library constants
// Functions (malloc, free, exit, atoi, atof, rand, srand, abs, etc.) via dlsym fallback

#ifndef NULL
#define NULL ((void *)0)
#endif

#define EXIT_SUCCESS 0
#define EXIT_FAILURE 1
#define RAND_MAX     2147483647
)EMBED"},
    {"string", R"EMBED(// madc embedded <string> — std::string as a header-defined class that binds to
// the REAL libstdc++ Itanium symbols (the Cfront model: madc emits no method
// bodies; the linker resolves them against libstdc++). This is the generic
// header-defined-class keystone — NO per-type code, NO hardcoded `_Z…` literals.
//
// WORK IN PROGRESS — retire-std-hardcoding campaign, string-first increment.
// std::string is std::__cxx11::basic_string<char, std::char_traits<char>,
// std::allocator<char>>. The members below give the real libstdc++ layout
// (sizeof 32: char* + size_type + the 16-byte SSO buffer), which madc computes
// with its generic struct layout — no sizeof() probe, no literal byte count, and
// no reference to a real std:: type inside madc (a doctest cross-checks the size
// against the real <string>).
//
// STAGING:
//   here: the basic_string template + a core bodyless surface (ctor/dtor +
//         length/size/c_str/empty/clear/at/append) that bind via the keystone.
//         It COEXISTS with the builtin string type (which still owns the
//         `string` typedef); there is deliberately NO `typedef ... string;` here
//         yet, so the two do not collide.
//   next: complete the operator/method surface (operator+/=/+=/[]/==, find,
//         substr, …), then add the `string` typedef and DELETE the builtin
//         string registration plus its wrappers and statics (the specifics live
//         in git history and the campaign handoff — not named here, so this
//         comment cannot trip the no-std-hardcoding finish-line gate).
//
// char_traits / allocator are declared here as the std:: templates basic_string
// names; they are templates (template_map by bare name), so a second declaration
// in another header (e.g. <fstream>) simply overwrites with the same definition.

namespace std {
    template<typename _CharT> class char_traits { char _M_dummy; };
    template<typename _CharT> class allocator   { char _M_dummy; };

    namespace __cxx11 {
	template<typename _CharT, typename _Traits, typename _Alloc>
	class basic_string {
	    _CharT       *_M_p;               // pointer to the character data
	    unsigned long _M_string_length;   // current length
	    char          _M_local_buf[16];   // SSO buffer / capacity union (16 bytes)
	public:
	    basic_string();                          // C1  ...C1Ev
	    basic_string(const char *);              // C1  ...C1EPKc
	    basic_string(unsigned long, char);       // C1  ...C1Emc
	    ~basic_string();                         // D1  ...D1Ev
	    unsigned long length() const;            // ...6lengthEv
	    unsigned long size() const;              // ...4sizeEv
	    const char   *c_str() const;             // ...5c_strEv
	    bool          empty() const;             // ...5emptyEv
	    void          clear();                   // ...5clearEv
	    const char   &at(unsigned long) const;   // ...2atEm
	    basic_string &append(const char *);      // ...6appendEPKc
	    const char   *data() const;              // ...4dataEv
	    unsigned long capacity() const;          // ...8capacityEv
	    unsigned long find(const char *, unsigned long) const;  // ...4findEPKcm
	    unsigned long find(char, unsigned long) const;          // ...4findEcm
	    unsigned long rfind(const char *, unsigned long) const; // ...5rfindEPKcm
	    unsigned long compare(const char *) const;              // ...7compareEPKc
	    basic_string  substr(unsigned long, unsigned long) const;  // ...6substrEmm
	    void          resize(unsigned long);     // ...6resizeEm
	    void          resize(unsigned long, char); // ...6resizeEmc
	    void          reserve(unsigned long);    // ...7reserveEm
	    void          push_back(char);           // ...9push_backEc
	    void          pop_back();                // ...8pop_backEv
	    char         &operator[](unsigned long) const;  // ...ixEm
	    basic_string &operator=(const char *);   // ...aSEPKc
	    basic_string &operator=(char);           // ...aSEc
	    basic_string &operator+=(const char *);  // ...pLEPKc
	    basic_string &operator+=(char);          // ...pLEc
	};
    }
}
)EMBED"},
    {"string.h", R"EMBED(// madc embedded string.h — C string functions
// Most functions resolve through the dlsym fallback at parse time
// (which registers them with a generic int64 return signature). The
// extern declarations below give the parser proper return types so
// `*(strchr(...)) = 0` works without explicit user-side `extern`.

#ifndef NULL
#define NULL ((void *)0)
#endif

extern char *strchr(char *s, int c);
extern char *strrchr(char *s, int c);
extern char *strstr(char *haystack, char *needle);
extern char *strdup(char *s);
extern char *strpbrk(char *s, char *accept);
extern char *strtok(char *s, char *delim);
extern char *strndup(char *s, int n);
// The copy/concat family also return char* (the destination). Without these
// declarations they default to a long return, so e.g.
// `cond ? one_argument(...) : strcpy(...)` mismatches char* vs long.
extern char *strcpy(char *dest, char *src);
extern char *strncpy(char *dest, char *src, unsigned long n);
extern char *strcat(char *dest, char *src);
extern char *strncat(char *dest, char *src, unsigned long n);
// The comparison family returns int, NOT the dlsym-fallback default of long.
// This matters: their result is negative for "less than", and that negative
// is routinely used directly in a signed comparison (e.g. SMAUG's
// `bsearch_skill_exact`: `strcmp(name, ...) < 1`). With a long return, libc
// leaves only the low 32 bits set (the value is returned in eax), so a
// negative int read as a 64-bit long becomes a huge positive — every such
// comparison goes the wrong way (the binary search always returned -1, so
// skill_lookup failed and combat dereferenced skill_table[bad gsn]).
extern int strcmp(char *a, char *b);
extern int strncmp(char *a, char *b, unsigned long n);
extern int strcasecmp(char *a, char *b);
extern int strncasecmp(char *a, char *b, unsigned long n);
extern int memcmp(void *a, void *b, unsigned long n);
)EMBED"},
    {"strings.h", R"EMBED(// madc embedded strings.h — POSIX string functions
// Most functions resolve through the dlsym fallback.
// This stub satisfies #include <strings.h> for code that uses
// bcopy, bzero, strcasecmp, strncasecmp, etc.

#ifndef __MADC_STRINGS_H
#define __MADC_STRINGS_H 1

#include <string.h>

// POSIX strings.h functions — available via dlsym fallback
extern int strcasecmp(const char *s1, const char *s2);
extern int strncasecmp(const char *s1, const char *s2, int n);

#endif
)EMBED"},
    {"sys/cdefs.h", R"EMBED(#ifndef __MADC_SYS_CDEFS_H
#define __MADC_SYS_CDEFS_H 1

/*
 * Minimal glibc-style cdefs shim for embedded-header consumers.
 * Extend this only as upstream code or embedded headers require more.
 */

#define __P(args) args
#define __PMT(args) args

#define __CONCAT(x, y) x ## y
#define __STRING(x) #x

#define __ptr_t void *

#ifdef __cplusplus
#define __BEGIN_DECLS extern "C" {
#define __END_DECLS }
#else
#define __BEGIN_DECLS
#define __END_DECLS
#endif

#define __THROW
#define __THROWNL
#define __NTH(fct) fct
#define __NTHNL(fct) fct
#define __LEAF
#define __LEAF_ATTR
#define __COLD

#ifndef __inline
#define __inline inline
#endif

#endif
)EMBED"},
    {"sys/file.h", R"EMBED(// madc embedded sys/file.h — BSD/POSIX file locking constants.
// Functions (flock) available via dlsym fallback.

#define LOCK_SH 1
#define LOCK_EX 2
#define LOCK_NB 4
#define LOCK_UN 8
)EMBED"},
    {"sys/ioctl.h", R"EMBED(// madc embedded sys/ioctl.h — minimal stubs for IMC sources.
// ioctl() resolves via dlsym. Common request codes that IMC uses
// (TIOCINQ, TIOCOUTQ, FIONREAD) match glibc x86-64 values.

#define FIONREAD 0x541B
#define TIOCINQ  FIONREAD
#define TIOCOUTQ 0x5411
)EMBED"},
    {"sys/ipc.h", R"EMBED(// madc embedded sys/ipc.h — System V IPC constants
// Used with sys/shm.h, sys/msg.h, sys/sem.h

#define IPC_PRIVATE 0

// Creation flags (for shmget/msgget/semget)
#define IPC_CREAT   0x0200
#define IPC_EXCL    0x0400
#define IPC_NOWAIT  0x0800

// Control commands (for shmctl/msgctl/semctl)
#define IPC_RMID 0
#define IPC_SET  1
#define IPC_STAT 2
#define IPC_INFO 3
)EMBED"},
    {"sys/mman.h", R"EMBED(// madc embedded sys/mman.h — memory mapping constants (Linux x86-64)
// Functions (mmap, munmap, mprotect, msync, madvise, mlockall, munlockall)
// available via dlsym fallback
// Note: mmap returns void* (use int64_t to hold the address)

// Memory protection flags (prot param to mmap/mprotect)
#define PROT_NONE  0x0
#define PROT_READ  0x1
#define PROT_WRITE 0x2
#define PROT_EXEC  0x4

// Mapping type flags (flags param to mmap)
#define MAP_SHARED     0x01
#define MAP_PRIVATE    0x02
#define MAP_FIXED      0x10
#define MAP_ANONYMOUS  0x20
#define MAP_ANON       0x20
#define MAP_GROWSDOWN  0x0100
#define MAP_DENYWRITE  0x0800
#define MAP_EXECUTABLE 0x1000
#define MAP_LOCKED     0x2000
#define MAP_NORESERVE  0x4000
#define MAP_POPULATE   0x8000
#define MAP_NONBLOCK   0x10000
#define MAP_HUGETLB    0x40000

// mmap failure return value
#define MAP_FAILED -1

// msync flags
#define MS_ASYNC      1
#define MS_SYNC       4
#define MS_INVALIDATE 2

// madvise flags
#define MADV_NORMAL     0
#define MADV_RANDOM     1
#define MADV_SEQUENTIAL 2
#define MADV_WILLNEED   3
#define MADV_DONTNEED   4
#define MADV_FREE       8
)EMBED"},
    {"sys/resource.h", R"EMBED(// madc embedded sys/resource.h — resource limits and usage
// Functions (getrlimit, setrlimit, getrusage, getpriority, setpriority)
// available via dlsym fallback
// struct rlimit / rusage access deferred

// Resource limit types (first arg to getrlimit/setrlimit)
#define RLIMIT_CPU     0
#define RLIMIT_FSIZE   1
#define RLIMIT_DATA    2
#define RLIMIT_STACK   3
#define RLIMIT_CORE    4
#define RLIMIT_RSS     5
#define RLIMIT_NPROC   6
#define RLIMIT_NOFILE  7
#define RLIMIT_MEMLOCK 8
#define RLIMIT_AS      9
#define RLIMIT_LOCKS   10
#define RLIMIT_SIGPENDING 11
#define RLIMIT_MSGQUEUE   12
#define RLIMIT_NICE       13
#define RLIMIT_RTPRIO     14
#define RLIM_INFINITY -1

// getrusage() who values
#define RUSAGE_SELF     0
#define RUSAGE_CHILDREN -1
#define RUSAGE_THREAD   1

// getpriority/setpriority which values
#define PRIO_PROCESS 0
#define PRIO_PGRP    1
#define PRIO_USER    2
)EMBED"},
    {"sys/select.h", R"EMBED(// madc embedded sys/select.h — select() multiplexing with fd_set support
// Functions (select, pselect) available via dlsym fallback.
// FD_SETSIZE is 1024; fd_set holds 1024 bits in 16 int64 slots (128 bytes),
// matching glibc x86-64 layout exactly. The FD_* macros forward to built-in
// C helpers (__madc_fd_zero/set/clr/isset) bundled into the madc binary.

#define FD_SETSIZE 1024

#ifndef __MADC_FD_SET_DEFINED
#define __MADC_FD_SET_DEFINED

// 128-byte bit array laid out as 16 int64_t slots. Field names are internal
// and not intended for direct access — use the FD_* macros.
struct fd_set {
    int64_t __b0;
    int64_t __b1;
    int64_t __b2;
    int64_t __b3;
    int64_t __b4;
    int64_t __b5;
    int64_t __b6;
    int64_t __b7;
    int64_t __b8;
    int64_t __b9;
    int64_t __b10;
    int64_t __b11;
    int64_t __b12;
    int64_t __b13;
    int64_t __b14;
    int64_t __b15;
};

// Bare `fd_set` (typedef alias) is the C-portable spelling used by
// most network code. Without it, `fd_set in_set;` fails with "use of
// undeclared identifier 'fd_set'".
typedef struct fd_set fd_set;

#endif

// FD_* macros take a `fd_set *` (a pointer), matching glibc. Callers
// pass either `&local_set` or an existing `fd_set *` parameter; both
// expand cleanly without a stray `&(&...)` doubling. Earlier versions
// of these macros baked `&(set)` into the body, which made the
// pointer form `FD_CLR(fd, &in_set)` fail with "expecting addressable
// expression after '&('".
#define FD_ZERO(setp)      __madc_fd_zero((setp))
#define FD_SET(fd, setp)   __madc_fd_set((fd), (setp))
#define FD_CLR(fd, setp)   __madc_fd_clr((fd), (setp))
#define FD_ISSET(fd, setp) __madc_fd_isset((fd), (setp))

// Function prototypes (needed by transpiler — JIT uses dlsym fallback)
int select(int nfds, struct fd_set *readfds, struct fd_set *writefds,
           struct fd_set *exceptfds, void *timeout);
)EMBED"},
    {"sys/shm.h", R"EMBED(// madc embedded sys/shm.h — shared memory IPC
// Functions (shmget, shmat, shmdt, shmctl) available via dlsym fallback
// struct shmid_ds access deferred

// shmat() flags
#define SHM_RDONLY  0x01000
#define SHM_RND    0x02000
#define SHM_REMAP  0x04000
#define SHM_EXEC   0x08000

// shmctl() commands (in addition to IPC_* from sys/ipc.h)
#define SHM_LOCK   11
#define SHM_UNLOCK 12
#define SHM_STAT   13
#define SHM_INFO   14
)EMBED"},
    {"sys/socket.h", R"EMBED(// madc embedded sys/socket.h — POSIX socket constants and base struct.
// Functions (socket, bind, connect, listen, accept, send, recv,
//            sendto, recvfrom, setsockopt, getsockopt, shutdown,
//            getpeername, getsockname) available via dlsym fallback.
// struct sockaddr is the 16-byte generic base used to cast specific
// sockaddr_in / sockaddr_in6 / sockaddr_un / etc. for bind()/connect().
// sa_data is declared as two 56-bit opaque chunks here; the concrete
// family-specific layout lives in netinet/in.h and friends.

struct sockaddr {
    uint16_t sa_family;  // AF_* (AF_INET, AF_INET6, ...)
    int16_t  __sa_pad0;
    int32_t  __sa_pad1;
    int64_t  __sa_pad2;  // 16 bytes total, matches glibc sockaddr
};

// Address families
#define AF_UNSPEC  0
#define AF_UNIX    1
#define AF_LOCAL   1
#define AF_INET    2
#define AF_INET6   10
#define AF_PACKET  17

// Protocol families (aliases for AF_*)
#define PF_UNSPEC  0
#define PF_UNIX    1
#define PF_LOCAL   1
#define PF_INET    2
#define PF_INET6   10

// Socket types
#define SOCK_STREAM    1
#define SOCK_DGRAM     2
#define SOCK_RAW       3
#define SOCK_SEQPACKET 5
#define SOCK_NONBLOCK  2048
#define SOCK_CLOEXEC   524288

// Socket-level option (for setsockopt/getsockopt level param)
#define SOL_SOCKET 1

// Socket options (SO_*)
#define SO_DEBUG        1
#define SO_REUSEADDR    2
#define SO_TYPE         3
#define SO_ERROR        4
#define SO_DONTROUTE    5
#define SO_BROADCAST    6
#define SO_SNDBUF       7
#define SO_RCVBUF       8
#define SO_KEEPALIVE    9
#define SO_OOBINLINE    10
#define SO_LINGER       13
#define SO_RCVLOWAT     18
#define SO_SNDLOWAT     19
#define SO_RCVTIMEO     20
#define SO_SNDTIMEO     21
#define SO_REUSEPORT    15
#define SO_PASSCRED     16
#define SO_PEERCRED     17

// Shutdown how values
#define SHUT_RD   0
#define SHUT_WR   1
#define SHUT_RDWR 2

// Send/recv flags
#define MSG_OOB        1
#define MSG_PEEK       2
#define MSG_DONTROUTE  4
#define MSG_CTRUNC     8
#define MSG_PROXY      16
#define MSG_TRUNC      32
#define MSG_DONTWAIT   64
#define MSG_EOR        128
#define MSG_WAITALL    256
#define MSG_NOSIGNAL   16384
#define MSG_MORE       32768
)EMBED"},
    {"sys/stat.h", R"EMBED(// madc embedded sys/stat.h — file-status constants and struct layout.
// Functions (stat, fstat, lstat, chmod, mkdir, mkfifo) available via dlsym
// fallback. Use `(struct stat *)` to attach field access to a caller-allocated
// buffer, or `struct stat sbuf; stat(path, &sbuf);` directly.

// File-type bits (for st_mode)
#define S_IFMT   0xF000
#define S_IFREG  0x8000
#define S_IFDIR  0x4000
#define S_IFLNK  0xA000
#define S_IFBLK  0x6000
#define S_IFCHR  0x2000
#define S_IFIFO  0x1000
#define S_IFSOCK 0xC000

// Permission bits
#define S_ISUID  0x800
#define S_ISGID  0x400
#define S_ISVTX  0x200

#define S_IRUSR  0x100
#define S_IWUSR  0x80
#define S_IXUSR  0x40
#define S_IRWXU  0x1C0

#define S_IRGRP  0x20
#define S_IWGRP  0x10
#define S_IXGRP  0x8
#define S_IRWXG  0x38

#define S_IROTH  0x4
#define S_IWOTH  0x2
#define S_IXOTH  0x1
#define S_IRWXO  0x7

// File-type predicate macros (C-library style, evaluate st_mode).
#define S_ISREG(m)  (((m) & S_IFMT) == S_IFREG)
#define S_ISDIR(m)  (((m) & S_IFMT) == S_IFDIR)
#define S_ISLNK(m)  (((m) & S_IFMT) == S_IFLNK)
#define S_ISBLK(m)  (((m) & S_IFMT) == S_IFBLK)
#define S_ISCHR(m)  (((m) & S_IFMT) == S_IFCHR)
#define S_ISFIFO(m) (((m) & S_IFMT) == S_IFIFO)
#define S_ISSOCK(m) (((m) & S_IFMT) == S_IFSOCK)

// Type aliases (glibc x86-64 LP64).
#define mode_t    uint32_t
#define uid_t     uint32_t
#define gid_t     uint32_t
#define dev_t     uint64_t
#define ino_t     uint64_t
#define nlink_t   uint64_t
#define off_t     int64_t
#define blksize_t int64_t
#define blkcnt_t  int64_t

// struct timespec — 16 bytes, glibc x86-64 layout (shared with time.h).
struct timespec {
    int64_t tv_sec;      // seconds
    int64_t tv_nsec;     // nanoseconds
};

// glibc x86-64 struct stat — 144 bytes total, natural C ABI alignment.
// Layout matches <bits/stat.h>: nlink comes before mode, with a 4-byte __pad0
// between st_gid and st_rdev; timespec triplet at the tail followed by 3 x
// reserved int64 slots. madc's natural field alignment inserts the __pad0
// automatically (st_rdev aligns to 8 after three 4-byte fields).
struct stat {
    uint64_t st_dev;     // device ID
    uint64_t st_ino;     // inode number
    uint64_t st_nlink;   // hard-link count
    uint32_t st_mode;    // file-type + permissions
    uint32_t st_uid;     // owner user ID
    uint32_t st_gid;     // owner group ID
    int32_t  __pad0;     // explicit; natural alignment would pad anyway
    uint64_t st_rdev;    // device ID (if special file)
    int64_t  st_size;    // size in bytes
    int64_t  st_blksize; // preferred I/O block size
    int64_t  st_blocks;  // 512-byte blocks allocated
    struct timespec st_atim;  // last access
    struct timespec st_mtim;  // last modification
    struct timespec st_ctim;  // last status change
    int64_t  __glibc_reserved0;
    int64_t  __glibc_reserved1;
    int64_t  __glibc_reserved2;
};

// Legacy field aliases. glibc exposes these as macros pointing at the tv_sec
// of the corresponding timespec, so `sbuf.st_mtime` yields an int64 seconds.
#define st_atime st_atim.tv_sec
#define st_mtime st_mtim.tv_sec
#define st_ctime st_ctim.tv_sec
)EMBED"},
    {"sys/time.h", R"EMBED(// madc embedded sys/time.h — POSIX time structures and constants
// Functions (gettimeofday, settimeofday, getitimer, setitimer) available
// via dlsym fallback. Use `(struct timeval *)` cast to access fields on
// the caller-allocated buffer.

// Interval timer types
#define ITIMER_REAL    0
#define ITIMER_VIRTUAL 1
#define ITIMER_PROF    2

// fd_set is commonly surfaced alongside <sys/time.h> on older Unix codepaths.
// Keep this in sync with embedded sys/select.h so code that only includes
// <sys/time.h> can still declare select() sets.
#define FD_SETSIZE 1024

#ifndef __MADC_FD_SET_DEFINED
#define __MADC_FD_SET_DEFINED

struct fd_set {
    int64_t __b0;
    int64_t __b1;
    int64_t __b2;
    int64_t __b3;
    int64_t __b4;
    int64_t __b5;
    int64_t __b6;
    int64_t __b7;
    int64_t __b8;
    int64_t __b9;
    int64_t __b10;
    int64_t __b11;
    int64_t __b12;
    int64_t __b13;
    int64_t __b14;
    int64_t __b15;
};
typedef struct fd_set fd_set;

#endif

// FD_* macros take a `fd_set *` (pointer), matching glibc — see
// sys/select.h for rationale.
#define FD_ZERO(setp)      __madc_fd_zero((setp))
#define FD_SET(fd, setp)   __madc_fd_set((fd), (setp))
#define FD_CLR(fd, setp)   __madc_fd_clr((fd), (setp))
#define FD_ISSET(fd, setp) __madc_fd_isset((fd), (setp))

// time_t is int64_t on glibc x86-64.
#define time_t int64_t

// suseconds_t is signed long on glibc x86-64.
#define suseconds_t int64_t

// glibc x86-64 struct timeval — 16 bytes.
struct timeval {
    int64_t tv_sec;     // seconds
    int64_t tv_usec;    // microseconds
};

#define timerisset __madc_timerisset
#define timerclear __madc_timerclear
#define timercmp(left_ptr, right_ptr, cmp_token) ((__madc_timeval_sec((left_ptr)) == __madc_timeval_sec((right_ptr))) ? (__madc_timeval_usec((left_ptr)) cmp_token __madc_timeval_usec((right_ptr))) : (__madc_timeval_sec((left_ptr)) cmp_token __madc_timeval_sec((right_ptr))))
#define timeradd __madc_timeradd
#define timersub __madc_timersub

// struct timezone — deprecated by POSIX; glibc still accepts NULL for it.
struct timezone {
    int32_t tz_minuteswest;
    int32_t tz_dsttime;
};

// Function prototypes (needed by transpiler — JIT uses dlsym fallback)
int gettimeofday(struct timeval *tv, void *tz);
int settimeofday(const struct timeval *tv, const void *tz);
)EMBED"},
    {"sys/types.h", R"EMBED(// madc embedded sys/types.h — POSIX type aliases
// These supplement the aliases in unistd.h

#define pid_t    int
#define uid_t    int
#define gid_t    int
#define off_t    int64_t
#define off64_t  int64_t
#define size_t   uint64_t
#define ssize_t  int64_t
#define mode_t   int
#define dev_t    int64_t
#define ino_t    uint64_t
#define nlink_t  int64_t
#define blksize_t int64_t
#define blkcnt_t  int64_t
#define socklen_t int
#define sa_family_t int
)EMBED"},
    {"sys/un.h", R"EMBED(// madc embedded sys/un.h — UNIX domain socket support
// AF_UNIX / AF_LOCAL = 1 (defined in sys/socket.h)
// struct sockaddr_un access deferred (requires struct interop)
// Functions via dlsym fallback (same as sys/socket.h: socket, bind, connect, etc.)
)EMBED"},
    {"sys/vfs.h", R"EMBED(// madc embedded sys/vfs.h — filesystem statistics
// statfs() is available via dlsym fallback.

#ifndef __MADC_SYS_VFS_H
#define __MADC_SYS_VFS_H 1

#include <sys/types.h>

struct statfs {
    long f_type;
    long f_bsize;
    long f_blocks;
    long f_bfree;
    long f_bavail;
    long f_files;
    long f_ffree;
    long f_fsid[2];
    long f_namelen;
    long f_frsize;
    long f_flags;
    long f_spare[4];
};

extern int statfs(const char *path, struct statfs *buf);

#endif
)EMBED"},
    {"sys/wait.h", R"EMBED(// madc embedded sys/wait.h — process wait constants
// Functions (wait, waitpid) available via dlsym fallback

#define WNOHANG   1
#define WUNTRACED 2
#define WCONTINUED 8

// Macros to extract status from waitpid() result
// (implemented as simple integer expressions)
#define WIFEXITED(s)    (((s) & 0x7f) == 0)
#define WEXITSTATUS(s)  (((s) >> 8) & 0xff)
#define WIFSIGNALED(s)  (((s) & 0x7f) != 0 && ((s) & 0x7f) != 0x7f)
#define WTERMSIG(s)     ((s) & 0x7f)
#define WIFSTOPPED(s)   (((s) & 0xff) == 0x7f)
#define WSTOPSIG(s)     (((s) >> 8) & 0xff)
)EMBED"},
    {"syslog.h", R"EMBED(// madc embedded syslog.h — system logging constants
// Functions (openlog, syslog, closelog, setlogmask) available via dlsym fallback

// Priorities (severity levels)
#define LOG_EMERG   0
#define LOG_ALERT   1
#define LOG_CRIT    2
#define LOG_ERR     3
#define LOG_WARNING 4
#define LOG_NOTICE  5
#define LOG_INFO    6
#define LOG_DEBUG   7

// Facilities
#define LOG_KERN    0
#define LOG_USER    8
#define LOG_MAIL    16
#define LOG_DAEMON  24
#define LOG_AUTH    32
#define LOG_SYSLOG  40
#define LOG_LPR     48
#define LOG_NEWS    56
#define LOG_UUCP    64
#define LOG_CRON    72
#define LOG_AUTHPRIV 80
#define LOG_FTP     88
#define LOG_LOCAL0  128
#define LOG_LOCAL1  136
#define LOG_LOCAL2  144
#define LOG_LOCAL3  152
#define LOG_LOCAL4  160
#define LOG_LOCAL5  168
#define LOG_LOCAL6  176
#define LOG_LOCAL7  184

// openlog() options
#define LOG_PID     1
#define LOG_CONS    2
#define LOG_ODELAY  4
#define LOG_NDELAY  8
#define LOG_NOWAIT  16
#define LOG_PERROR  32
)EMBED"},
    {"termios.h", R"EMBED(// madc embedded termios.h — terminal I/O constants (Linux x86-64)
// Functions (tcgetattr, tcsetattr, tcsendbreak, tcdrain, tcflush,
//            tcflow, cfgetispeed, cfgetospeed, cfsetispeed, cfsetospeed,
//            isatty, ttyname) available via dlsym fallback
// struct termios access deferred

// tcsetattr() action flags
#define TCSANOW   0
#define TCSADRAIN 1
#define TCSAFLUSH 2

// tcflush() queue selectors
#define TCIFLUSH  0
#define TCOFLUSH  1
#define TCIOFLUSH 2

// tcflow() action values
#define TCOOFF 0
#define TCOON  1
#define TCIOFF 2
#define TCION  3

// c_lflag bits
#define ISIG    0000001
#define ICANON  0000002
#define ECHO    0000010
#define ECHOE   0000020
#define ECHOK   0000040
#define ECHONL  0000100
#define NOFLSH  0000200
#define TOSTOP  0000400
#define IEXTEN  0100000

// c_iflag bits
#define IGNBRK  0000001
#define BRKINT  0000002
#define IGNPAR  0000004
#define PARMRK  0000010
#define INPCK   0000020
#define ISTRIP  0000040
#define INLCR   0000100
#define IGNCR   0000200
#define ICRNL   0000400
#define IXON    0002000
#define IXOFF   0010000

// c_oflag bits
#define OPOST   0000001
#define ONLCR   0000004
#define OCRNL   0000010
#define ONOCR   0000020
#define ONLRET  0000040

// Baud rates
#define B0       0
#define B50      1
#define B75      2
#define B110     3
#define B134     4
#define B150     5
#define B200     6
#define B300     7
#define B600     8
#define B1200    9
#define B1800    10
#define B2400    11
#define B4800    12
#define B9600    13
#define B19200   14
#define B38400   15
#define B57600   4097
#define B115200  4098
#define B230400  4099
#define B460800  4100
#define B921600  4103

// ioctl TIOCGWINSZ / TIOCSWINSZ (get/set window size)
#define TIOCGWINSZ 0x5413
#define TIOCSWINSZ 0x5414
)EMBED"},
    {"time.h", R"EMBED(// madc embedded time.h — POSIX time constants, types, and struct tm.
// Functions (time, clock, difftime, mktime, localtime, gmtime, strftime,
// nanosleep) available via dlsym fallback. Use `(struct tm *)` cast on
// the return value of localtime/gmtime to attach field access.

// Clocks
#define CLOCKS_PER_SEC 1000000
#define CLOCK_REALTIME  0
#define CLOCK_MONOTONIC 1
#define CLOCK_PROCESS_CPUTIME_ID 2
#define CLOCK_THREAD_CPUTIME_ID  3

// Time type aliases
#define time_t  int64_t
#define clock_t int64_t

// glibc x86-64 struct tm layout — 56 bytes total, natural C ABI alignment.
// All int fields are 32-bit (C int) to match glibc; tm_gmtoff is long (64-bit
// on LP64); tm_zone is const char *. The 4-byte pad between tm_isdst and
// tm_gmtoff is inserted automatically by madc's natural field alignment.
struct tm {
    int32_t tm_sec;     // seconds  [0, 60]
    int32_t tm_min;     // minutes  [0, 59]
    int32_t tm_hour;    // hours    [0, 23]
    int32_t tm_mday;    // day of month  [1, 31]
    int32_t tm_mon;     // months since Jan [0, 11]
    int32_t tm_year;    // years since 1900
    int32_t tm_wday;    // days since Sunday [0, 6]
    int32_t tm_yday;    // days since Jan 1  [0, 365]
    int32_t tm_isdst;   // DST flag
    int64_t tm_gmtoff;  // seconds east of UTC
    char   *tm_zone;    // timezone abbreviation
};

// Function prototypes (needed by transpiler — JIT uses dlsym fallback)
int64_t time(int64_t *tloc);
int64_t clock(void);
double difftime(int64_t time1, int64_t time0);
int64_t mktime(struct tm *timeptr);
struct tm *localtime(const int64_t *timer);
struct tm *gmtime(const int64_t *timer);
uint64_t strftime(char *s, uint64_t maxsize, const char *format, const struct tm *timeptr);
int nanosleep(const void *req, void *rem);
)EMBED"},
    {"typeinfo", R"EMBED(// madc embedded <typeinfo> — std::type_info as a header-defined class (S5).
//
// type_info's name()/operator==/operator!= are INLINE in libstdc++'s own header
// (they are NOT exported symbols — only the dtors/__do_catch/__do_upcast are), so
// they cannot be bound to libstdc++ via the keystone. They are given inline bodies
// here instead, matching libstdc++'s definitions.
//
// LAYOUT (Itanium): a type_info object is { vtable_ptr @0 ; const char* __name @8 }.
// The objects madc emits for user classes (_ZTI<cls>, see cir_builder S5b) and the
// objects libstdc++ emits (_ZTI<builtin>) both follow this layout, so __name (the
// 2nd field) is the mangled type-name string (_ZTS<cls>). `typeid` (cir_builder S5d)
// yields a type_info reference pointing at one of these objects.
//
// operator== is object identity: madc emits exactly ONE _ZTI per type (deduped in
// Pass 1.5) and typeid always yields that object for a given type, so equal type
// <=> same object. (libstdc++ compares __name; identity is equivalent here and
// needs no strcmp dependency.)
//
// NOTE: no `const` is used on the members/methods/params — madc does not yet parse
// a const-qualified class member or a trailing const method qualifier (orthogonal
// parser gaps), and it does not enforce const-correctness, so this is faithful in
// behaviour. name() returns char* rather than const char* for the same reason.

namespace std {
    class type_info {
	void *__vtable_ptr;   // offset 0: the type_info-class vtable address point
	char *__name;         // offset 8: the mangled type name (_ZTS<cls>)
    public:
	char *name() { return __name; }
	// Identity via the name pointer: madc emits exactly ONE _ZTS per type, so
	// equal type <=> equal __name pointer. (Comparing __name avoids taking the
	// address of a reference param, which madc lowers to a pointer.)
	bool operator==(type_info &__o) { return __name == __o.__name; }
	bool operator!=(type_info &__o) { return __name != __o.__name; }
    };
}
)EMBED"},
    {"unistd.h", R"EMBED(// madc embedded unistd.h — POSIX constants and type aliases
// Functions (read, write, close, lseek, fork, execvp, pipe, dup2,
//           getcwd, chdir, unlink, rmdir, access, getpid, getuid, sleep)
// available via dlsym fallback

// Standard file descriptors
#define STDIN_FILENO  0
#define STDOUT_FILENO 1
#define STDERR_FILENO 2

// access() mode flags
#define F_OK 0
#define X_OK 1
#define W_OK 2
#define R_OK 4

// lseek() whence values (mirrors stdio.h SEEK_*)
#define SEEK_SET 0
#define SEEK_CUR 1
#define SEEK_END 2

// POSIX type aliases — substituted at tokenization time via #define
#define pid_t    int
#define uid_t    int
#define gid_t    int
#define off_t    int64_t
#define size_t   uint64_t
#define ssize_t  int64_t
#define mode_t   int
#define dev_t    int64_t
#define ino_t    uint64_t
#define nlink_t  int64_t
#define intptr_t  int64_t
#define uintptr_t uint64_t
)EMBED"},
    {"vector", R"EMBED(// madc embedded <vector> — std::vector<T> as a real madc template.
//
// std::vector is an ordinary std::-namespaced madc template, instantiated
// per use by the template-instantiation engine (Borland monomorphization).
// It is NOT a lexer keyword and NOT a libstdc++ wrapper — it is madc's own
// STL container, defined here and compiled through the class model.
#include <stdlib.h>
namespace std {
template<typename T> class vector {
    T* data;
    long len;
    long cap;
public:
    vector() { data = (T*)malloc(4 * sizeof(T)); len = 0; cap = 4; }
    ~vector() {
	// Destruct each live element before releasing the buffer, exactly as
	// std::vector does (destroy data[0..len), then deallocate). __destroy
	// is the element-type-driven destroy intrinsic: it calls T's class
	// dtor for an object element (string -> ~basic_string) and is a no-op
	// for a scalar/pointer T (vector<int> destructs nothing). Pointer arith
	// (data + i), NOT &data[i] (member-subscript parser gap).
	long i = 0;
	while ( i < len ) { __destroy(data + i); i = i + 1; }
	free(data);
    }
    void push_back(T v) {
	if (len >= cap) { cap = cap * 2; data = (T*)realloc(data, cap * sizeof(T)); }
	T* slot = data + len;		// pointer arith (NOT &data[len] — parser gap)
	new (slot) T(v);		// placement copy-construct (works for string too)
	len = len + 1;
    }
    T& operator[](long i) { return data[i]; }
    long size() { return len; }
};
}
)EMBED"},
    {"zlib.h", R"EMBED(// madc embedded zlib.h — minimal stub for z_stream pointer members.
// Full zlib functionality requires linking against libz.

typedef struct z_stream_s {
    void *next_in;
    unsigned int avail_in;
    unsigned long total_in;
    void *next_out;
    unsigned int avail_out;
    unsigned long total_out;
    void *msg;
    void *state;
    void *zalloc;
    void *zfree;
    void *opaque;
    int data_type;
    unsigned long adler;
    unsigned long reserved;
} z_stream;
)EMBED"}
};

const std::string *find_embedded_header(const std::string &name)
{
    auto it = embedded_headers.find(name);
    if ( it != embedded_headers.end() )
        return &it->second;
    return nullptr;
}
