// AUTO-GENERATED by scripts/gen_embedded_headers.sh — do not edit
#include <map>
#include <string>

static std::map<std::string, std::string> embedded_headers = {
    {"float.h", R"EMBED(// madc embedded float.h — floating-point characteristics for host x86-64

#ifndef __MADC_FLOAT_H
#define __MADC_FLOAT_H 1

#define FLT_RADIX 2
#define FLT_EVAL_METHOD 0
#define DECIMAL_DIG 21

#define FLT_MANT_DIG 24
#define DBL_MANT_DIG 53
#define LDBL_MANT_DIG 64

#define FLT_DIG 6
#define DBL_DIG 15
#define LDBL_DIG 18

#define FLT_MIN_EXP (-125)
#define DBL_MIN_EXP (-1021)
#define LDBL_MIN_EXP (-16381)

#define FLT_MIN_10_EXP (-37)
#define DBL_MIN_10_EXP (-307)
#define LDBL_MIN_10_EXP (-4931)

#define FLT_MAX_EXP 128
#define DBL_MAX_EXP 1024
#define LDBL_MAX_EXP 16384

#define FLT_MAX_10_EXP 38
#define DBL_MAX_10_EXP 308
#define LDBL_MAX_10_EXP 4932

#define FLT_MAX 3.40282346638528859811704183484516925e+38F
#define DBL_MAX ((double)1.79769313486231570814527423731704357e+308L)
#define LDBL_MAX 1.18973149535723176502126385303097021e+4932L

#define FLT_MIN 1.17549435082228750796873653722224568e-38F
#define DBL_MIN ((double)2.22507385850720138309023271733240406e-308L)
#define LDBL_MIN 3.36210314311209350626267781732175260e-4932L

#define FLT_EPSILON 1.19209289550781250000000000000000000e-7F
#define DBL_EPSILON ((double)2.22044604925031308084726333618164062e-16L)
#define LDBL_EPSILON 1.08420217248550443400745280086994171e-19L

#endif
)EMBED"},
    {"limits.h", R"EMBED(// madc embedded limits.h — integer limit constants

#define CHAR_BIT  8
#define SCHAR_MIN -128
#define SCHAR_MAX 127
#define UCHAR_MAX 255
#define SHRT_MIN  -32768
#define SHRT_MAX  32767
#define USHRT_MAX 65535
#define INT_MIN   -2147483648
#define INT_MAX   2147483647
#define UINT_MAX  4294967295U
#define LONG_MIN  -9223372036854775807L
#define LONG_MAX  9223372036854775807L
#define ULONG_MAX 18446744073709551615UL
#define LLONG_MIN -9223372036854775807LL
#define LLONG_MAX 9223372036854775807LL
#define ULLONG_MAX 18446744073709551615ULL
#define CHAR_MIN  -128
#define CHAR_MAX  127
#define PATH_MAX  4096
#define NAME_MAX  255
)EMBED"},
    {"ns_js", R"EMBED(#include <string>
extern "C" {
    std::string *__js_btoa(std::string *, const char *);
    std::string *__js_atob(std::string *, const char *);
    std::string *__js_encodeURIComponent(std::string *, const char *);
    std::string *__js_decodeURIComponent(std::string *, const char *);
    long __js_parseInt(const char *, long);
    std::string *__js_stringify(std::string *, array *);
}

namespace js {
    std::string &btoa(std::string &result, const char *input) { return *__js_btoa(&result, input); }
    std::string &atob(std::string &result, const char *input) { return *__js_atob(&result, input); }
    std::string &encodeURIComponent(std::string &result, const char *input) { return *__js_encodeURIComponent(&result, input); }
    std::string &decodeURIComponent(std::string &result, const char *input) { return *__js_decodeURIComponent(&result, input); }
    long parseInt(const char *text, long radix) { return __js_parseInt(text, radix); }
    std::string &stringify(std::string &result, array &values) { return *__js_stringify(&result, &values); }
}
)EMBED"},
    {"ns_js.h", R"EMBED(#ifndef MADC_NS_JS_H
#define MADC_NS_JS_H

#ifdef __cplusplus

#include <cstdint>
#include <string>
#include "datadef.h"

extern "C" {
std::string *__js_btoa(std::string *, const char *);
std::string *__js_atob(std::string *, const char *);
std::string *__js_encodeURIComponent(std::string *, const char *);
std::string *__js_decodeURIComponent(std::string *, const char *);
int64_t __js_parseInt(const char *, int64_t);
std::string *__js_stringify(std::string *, madc::value *);
}

namespace js {
inline std::string &btoa(std::string &result, const char *input) { return *__js_btoa(&result, input); }
inline std::string &atob(std::string &result, const char *input) { return *__js_atob(&result, input); }
inline std::string &encodeURIComponent(std::string &result, const char *input) { return *__js_encodeURIComponent(&result, input); }
inline std::string &decodeURIComponent(std::string &result, const char *input) { return *__js_decodeURIComponent(&result, input); }
inline int64_t parseInt(const char *text, int64_t radix) { return __js_parseInt(text, radix); }
inline std::string &stringify(std::string &result, madc::value &values) { return *__js_stringify(&result, &values); }
}

#endif

#endif
)EMBED"},
    {"ns_madc", R"EMBED(// madc embedded <ns_madc> — script-level runtime eval + expression eval.
// Declaration-only: the madc:: publics below resolve mangled-direct
// (Itanium symbols) to the real namespace madc implementations in the
// host, src/ns_madc.cpp (cpp-first-api.md — script namespace publics are
// never routed through extern-C wrappers; the C-linkage __madc_*_runtime
// surface is the API for C hosts only).
//
// VALUE-FIRST (slice V2): the primary API is typed in madc::value and
// const char* — this header deliberately does NOT include <string>, so
// madc::-only scripts never pay the <string> cost. The std::string
// overloads below are CONVENIENCES, declared only when <string> was
// included BEFORE this header (gated on the standard library's own
// include guards). Auto-include orders <string> first, so scripts with
// no explicit includes get them whenever they use a `string`; explicit
// includers write `#include <string>` above `#include <ns_madc>`.
//
// Security: the runtime honours the engine's madc_runtime_eval_policy;
// scope-access variants are gated by the parser's scope-access hooks.

namespace madc {
    // Full-program eval: the source must define (or be wrapped into)
    // `__madc_eval()`. The value-destination forms carry the rendered
    // result text as a string-kind value ("42", "4.000000", "echo").
    value &eval_unit(value &out, const char *source);
    bool eval_bool(const char *source);
    long eval_int(const char *source);
    double eval_double(const char *source);
    value &eval_string(value &out, const char *source);

    // Expression eval: a single expression, no function calls unless the
    // engine's expression policy allows them.
    bool eval_expression_bool(const char *expr);
    long eval_expression_int(const char *expr);
    double eval_expression_double(const char *expr);
    value &eval_expression_string(value &out, const char *expr);

    // Typed out-parameter forms (overloaded on the destination). The
    // value-destination form RENDERS any result type into a string-kind
    // value; eval_expression_string above is the strict string-typed
    // coercion.
    void eval_expression(long &out, const char *expr);
    void eval_expression(double &out, const char *expr);
    void eval_expression(value &out, const char *expr);

    // Context-carrying expression forms: `ctx` is a madc value of nested
    // key/value entries built with the context_set_* helpers below.
    bool eval_expression_bool_ctx(const char *expr, value &ctx);
    long eval_expression_int_ctx(const char *expr, value &ctx);
    double eval_expression_double_ctx(const char *expr, value &ctx);
    value &eval_expression_string_ctx(value &out, const char *expr, value &ctx);
    void eval_expression_ctx(long &out, const char *expr, value &ctx);
    void eval_expression_ctx(double &out, const char *expr, value &ctx);
    void eval_expression_ctx(value &out, const char *expr, value &ctx);

    // Context-carrying full-eval forms — the rebind targets for call-site
    // scope capture.
    value &eval_unit_ctx(value &out, const char *source, value &ctx);
    bool eval_bool_ctx(const char *source, value &ctx);
    long eval_int_ctx(const char *source, value &ctx);
    double eval_double_ctx(const char *source, value &ctx);
    value &eval_string_ctx(value &out, const char *source, value &ctx);

    void context_set_int(value &ctx, const char *key, long v);
    void context_set_real(value &ctx, const char *key, double v);
    void context_set_string(value &ctx, const char *key, const char *v);
    void context_set_array(value &ctx, const char *key, value &v);

#if defined(_GLIBCXX_STRING) || defined(_LIBCPP_STRING)
    // std::string conveniences — present only because <string> precedes
    // this header in this translation unit (libstdc++/libc++ guard).
    std::string &eval_unit(std::string &out, std::string &source);
    bool eval_bool(std::string &source);
    long eval_int(std::string &source);
    double eval_double(std::string &source);
    std::string &eval_string(std::string &out, std::string &source);
    std::string &eval_expression_string(std::string &out, const char *expr);
    void eval_expression(std::string &out, const char *expr);
    std::string &eval_expression_ctx(std::string &out, const char *expr, value &ctx);
    std::string &eval_expression_string_ctx(std::string &out, const char *expr, value &ctx);
    std::string &eval_unit_ctx(std::string &out, std::string &source, value &ctx);
    bool eval_bool_ctx(std::string &source, value &ctx);
    long eval_int_ctx(std::string &source, value &ctx);
    double eval_double_ctx(std::string &source, value &ctx);
    std::string &eval_string_ctx(std::string &out, std::string &source, value &ctx);
    void context_set_int(value &ctx, std::string &key, long v);
    void context_set_real(value &ctx, std::string &key, double v);
    void context_set_string(value &ctx, std::string &key, const char *v);
    void context_set_array(value &ctx, std::string &key, value &v);
#endif

    // The system object (Python `sys` convention — include this header
    // like Python's `import sys`). sys.argv / sys.path are mutable madc
    // arrays (argv[0] = script path; path mutations steer FUTURE
    // #load/eval only); platform / version / hostname are immutable
    // facts (sys.version == MADC_VERSION). The one instance lives in the
    // host (_ZN4madc3sysE); argv/path fill at main entry via the
    // injected __madc_sys_init. LAYOUT CONTRACT with
    // include/libmadc/sysinfo.h — append-only, keep both in sync.
    struct SysInfo {
	array argv;
	array path;
	const char *const platform;
	const char *const version;
	const char *const hostname;
    };
    extern SysInfo sys;

    // madc::channel — one URI-addressed byte channel with line helpers
    // (exec://, tcp://, file://, ... via the host channel registry).
    // Declaration-only: methods resolve mangled-direct to the host class
    // (src/madc_channel_object.cpp). LAYOUT CONTRACT with
    // include/madcdis/channel.h — a single void* member, append-only,
    // keep both in sync. Modes: "r" "w" "rw" (default) "a".
    // readline() strips the trailing newline (and a preceding '\r') and
    // returns the final unterminated tail; false only at EOF.
    // Non-copyable: the copy ctor is private and unimplemented.
    class channel {
    public:
	channel(const char *uri);
	channel(const char *uri, const char *mode);
	~channel();

	bool ok() const;
	const char *last_error() const;

	long read(void *buffer, long capacity);
	// value carriers: the line/payload lands as a string-kind value;
	// write() sends the value's text view.
	bool readline(value &out);
	bool readall(value &out);
	bool write(const char *text);
	bool write(const char *buffer, long size);
	bool write(value &text);
#if defined(_GLIBCXX_STRING) || defined(_LIBCPP_STRING)
	// std::string conveniences — <string> must precede this header.
	bool readline(std::string &out);
	bool readall(std::string &out);
	bool write(std::string &text);
#endif
	bool close_write();
	void close();

    private:
	channel(const channel &);
	channel &operator=(const channel &);

	void *impl_;
    };
}
)EMBED"},
    {"ns_perl", R"EMBED(#include <string>
extern "C" {
    long __perl_chop(std::string *);
    long __perl_chomp(std::string *);
    void __perl_grep(array *, const char *, array *);
    void __perl_glob(array *, const char *);
    long __perl_scalar(array *);
    void __perl_push(array *, const char *);
    std::string *__perl_pop(std::string *, array *);
    std::string *__perl_shift(std::string *, array *);
    void __perl_unshift(array *, const char *);
    std::string *__perl_join(std::string *, const char *, array *);
    void __perl_split(array *, const char *, const char *);
    std::string *__perl_reverse(std::string *);
    std::string *__perl_lc(std::string *);
    std::string *__perl_uc(std::string *);
    std::string *__perl_ucfirst(std::string *);
    std::string *__perl_lcfirst(std::string *);
    long __perl_index(const char *, const char *);
    long __perl_rindex(const char *, const char *);
    long __perl_length(const char *);
    std::string *__perl_substr(std::string *, const char *, long, long);
}

namespace perl {
    long chop(std::string &s) { return __perl_chop(&s); }
    long chomp(std::string &s) { return __perl_chomp(&s); }
    void grep(array &dest, const char *needle, array &src) { __perl_grep(&dest, needle, &src); }
    void glob(array &out, const char *pattern) { __perl_glob(&out, pattern); }
    long scalar(array &values) { return __perl_scalar(&values); }
    void push(array &values, const char *text) { __perl_push(&values, text); }
    std::string &pop(std::string &result, array &values) { return *__perl_pop(&result, &values); }
    std::string &shift(std::string &result, array &values) { return *__perl_shift(&result, &values); }
    void unshift(array &values, const char *text) { __perl_unshift(&values, text); }
    std::string &join(std::string &result, const char *separator, array &values) { return *__perl_join(&result, separator, &values); }
    void split(array &out, const char *pattern, const char *text) { __perl_split(&out, pattern, text); }
    std::string &reverse(std::string &s) { return *__perl_reverse(&s); }
    std::string &lc(std::string &s) { return *__perl_lc(&s); }
    std::string &uc(std::string &s) { return *__perl_uc(&s); }
    std::string &ucfirst(std::string &s) { return *__perl_ucfirst(&s); }
    std::string &lcfirst(std::string &s) { return *__perl_lcfirst(&s); }
    long index(const char *haystack, const char *needle) { return __perl_index(haystack, needle); }
    long rindex(const char *haystack, const char *needle) { return __perl_rindex(haystack, needle); }
    long length(const char *text) { return __perl_length(text); }
    std::string &substr(std::string &result, const char *text, long offset, long length) { return *__perl_substr(&result, text, offset, length); }
}
)EMBED"},
    {"ns_perl.h", R"EMBED(#ifndef MADC_NS_PERL_H
#define MADC_NS_PERL_H

#ifdef __cplusplus

#include <cstdint>
#include <string>
#include "datadef.h"

extern "C" {
int64_t __perl_chop(std::string *);
int64_t __perl_chomp(std::string *);
void __perl_grep(madc::value *, const char *, madc::value *);
void __perl_glob(madc::value *, const char *);
int64_t __perl_scalar(madc::value *);
void __perl_push(madc::value *, const char *);
std::string *__perl_pop(std::string *, madc::value *);
std::string *__perl_shift(std::string *, madc::value *);
void __perl_unshift(madc::value *, const char *);
std::string *__perl_join(std::string *, const char *, madc::value *);
void __perl_split(madc::value *, const char *, const char *);
std::string *__perl_reverse(std::string *);
std::string *__perl_lc(std::string *);
std::string *__perl_uc(std::string *);
std::string *__perl_ucfirst(std::string *);
std::string *__perl_lcfirst(std::string *);
int64_t __perl_index(const char *, const char *);
int64_t __perl_rindex(const char *, const char *);
int64_t __perl_length(const char *);
std::string *__perl_substr(std::string *, const char *, int64_t, int64_t);
}

namespace perl {
inline int64_t chop(std::string &s) { return __perl_chop(&s); }
inline int64_t chomp(std::string &s) { return __perl_chomp(&s); }
inline void grep(madc::value &dest, const char *needle, madc::value &src) { __perl_grep(&dest, needle, &src); }
inline void glob(madc::value &out, const char *pattern) { __perl_glob(&out, pattern); }
inline int64_t scalar(madc::value &values) { return __perl_scalar(&values); }
inline void push(madc::value &values, const char *text) { __perl_push(&values, text); }
inline std::string &pop(std::string &result, madc::value &values) { return *__perl_pop(&result, &values); }
inline std::string &shift(std::string &result, madc::value &values) { return *__perl_shift(&result, &values); }
inline void unshift(madc::value &values, const char *text) { __perl_unshift(&values, text); }
inline std::string &join(std::string &result, const char *separator, madc::value &values) { return *__perl_join(&result, separator, &values); }
inline void split(madc::value &out, const char *pattern, const char *text) { __perl_split(&out, pattern, text); }
inline std::string &reverse(std::string &s) { return *__perl_reverse(&s); }
inline std::string &lc(std::string &s) { return *__perl_lc(&s); }
inline std::string &uc(std::string &s) { return *__perl_uc(&s); }
inline std::string &ucfirst(std::string &s) { return *__perl_ucfirst(&s); }
inline std::string &lcfirst(std::string &s) { return *__perl_lcfirst(&s); }
inline int64_t index(const char *haystack, const char *needle) { return __perl_index(haystack, needle); }
inline int64_t rindex(const char *haystack, const char *needle) { return __perl_rindex(haystack, needle); }
inline int64_t length(const char *text) { return __perl_length(text); }
inline std::string &substr(std::string &result, const char *text, int64_t offset, int64_t length) { return *__perl_substr(&result, text, offset, length); }
}

#endif

#endif
)EMBED"},
    {"ns_php", R"EMBED(#include <string>
extern "C" {
    std::string *__php_trim(std::string *);
    std::string *__php_ltrim(std::string *);
    std::string *__php_rtrim(std::string *);
    std::string *__php_chop(std::string *);
    std::string *__php_ucfirst(std::string *);
    std::string *__php_lcfirst(std::string *);
    std::string *__php_str_repeat(std::string *, long);
    std::string *__php_str_replace(std::string *, std::string *, std::string *);
    std::string *__php_str_pad(std::string *, long, std::string *);
    long __php_str_word_count(std::string *);
    std::string *__php_nl2br(std::string *);
    std::string *__php_str_rot13(std::string *);
    std::string *__php_chunk_split(std::string *, long, std::string *);
    std::string *__php_number_format(std::string *, long, std::string *);
    std::string *__php_wordwrap(std::string *, long, std::string *);

    void __php_explode(array *, const char *, const char *);
    std::string *__php_implode(std::string *, const char *, array *);
    long __php_count(array *);
    void __php_array_push(array *, const char *);
    void __php_array_push_int(array *, long);
    void __php_array_push_array(array *, array *);
    std::string *__php_array_pop(std::string *, array *);
    std::string *__php_array_get(std::string *, array *, long);
    long __php_array_get_int(array *, long);
    const char *__php_array_get_cstr(array *, long);
    void __php_array_reverse(array *);
    long __php_in_array(const char *, array *);
    long __php_array_search(const char *, array *);
    void __php_array_unique(array *);
    std::string *__php_array_shift(std::string *, array *);
    void __php_array_unshift(array *, const char *);
    void __php_sort(array *);
    void __php_rsort(array *);
    void __php_array_slice(array *, array *, long, long);
    void __php_array_merge(array *, array *);
    void __php_array_column(array *, array *, long);
}

namespace php {
    std::string &trim(std::string &s);
    std::string &ltrim(std::string &s);
    std::string &rtrim(std::string &s);
    std::string &chop(std::string &s);
    std::string &ucfirst(std::string &s);
    std::string &lcfirst(std::string &s);
    std::string &str_repeat(std::string &s, long count);
    std::string &str_replace(std::string &search, std::string &replace, std::string &subject);
    std::string &str_pad(std::string &s, long length, std::string &pad);
    long str_word_count(std::string &s);
    std::string &nl2br(std::string &s);
    std::string &str_rot13(std::string &s);
    std::string &chunk_split(std::string &s, long chunklen, std::string &separator);
    std::string &number_format(std::string &result, long number, std::string &separator);
    std::string &wordwrap(std::string &s, long width, std::string &separator);

    void explode(array &out, const char *delim, const char *text) { __php_explode(&out, delim, text); }
    std::string &implode(std::string &result, const char *glue, array &values) { return *__php_implode(&result, glue, &values); }
    long count(array &values) { return __php_count(&values); }
    void array_push(array &values, const char *text) { __php_array_push(&values, text); }
    void array_push_int(array &values, long value) { __php_array_push_int(&values, value); }
    void array_push_array(array &values, array &nested) { __php_array_push_array(&values, &nested); }
    std::string &array_pop(std::string &result, array &values) { return *__php_array_pop(&result, &values); }
    std::string &array_get(std::string &result, array &values, long index) { return *__php_array_get(&result, &values, index); }
    long array_get_int(array &values, long index) { return __php_array_get_int(&values, index); }
    const char *array_get_cstr(array &values, long index) { return __php_array_get_cstr(&values, index); }
    void array_reverse(array &values) { __php_array_reverse(&values); }
    long in_array(const char *needle, array &values) { return __php_in_array(needle, &values); }
    long array_search(const char *needle, array &values) { return __php_array_search(needle, &values); }
    void array_unique(array &values) { __php_array_unique(&values); }
    std::string &array_shift(std::string &result, array &values) { return *__php_array_shift(&result, &values); }
    void array_unshift(array &values, const char *text) { __php_array_unshift(&values, text); }
    void sort(array &values) { __php_sort(&values); }
    void rsort(array &values) { __php_rsort(&values); }
    void array_slice(array &dest, array &src, long offset, long length) { __php_array_slice(&dest, &src, offset, length); }
    void array_merge(array &dest, array &src) { __php_array_merge(&dest, &src); }
    void array_column(array &dest, array &src, long column_index) { __php_array_column(&dest, &src, column_index); }
}
)EMBED"},
    {"ns_php.h", R"EMBED(#ifndef MADC_NS_PHP_H
#define MADC_NS_PHP_H

#ifdef __cplusplus

#include <cstdint>
#include <string>
#include "datadef.h"

extern "C" {
std::string *__php_trim(std::string *);
std::string *__php_ltrim(std::string *);
std::string *__php_rtrim(std::string *);
std::string *__php_chop(std::string *);
std::string *__php_ucfirst(std::string *);
std::string *__php_lcfirst(std::string *);
std::string *__php_str_repeat(std::string *, int64_t);
std::string *__php_str_replace(std::string *, std::string *, std::string *);
std::string *__php_str_pad(std::string *, int64_t, std::string *);
int64_t __php_str_word_count(std::string *);
std::string *__php_nl2br(std::string *);
std::string *__php_str_rot13(std::string *);
std::string *__php_chunk_split(std::string *, int64_t, std::string *);
std::string *__php_number_format(std::string *, int64_t, std::string *);
std::string *__php_wordwrap(std::string *, int64_t, std::string *);
void __php_explode(madc::value *, const char *, const char *);
std::string *__php_implode(std::string *, const char *, madc::value *);
int64_t __php_count(madc::value *);
void __php_array_push(madc::value *, const char *);
void __php_array_push_int(madc::value *, int64_t);
void __php_array_push_array(madc::value *, madc::value *);
std::string *__php_array_pop(std::string *, madc::value *);
std::string *__php_array_get(std::string *, madc::value *, int64_t);
int64_t __php_array_get_int(madc::value *, int64_t);
const char *__php_array_get_cstr(madc::value *, int64_t);
void __php_array_reverse(madc::value *);
int64_t __php_in_array(const char *, madc::value *);
int64_t __php_array_search(const char *, madc::value *);
void __php_array_unique(madc::value *);
std::string *__php_array_shift(std::string *, madc::value *);
void __php_array_unshift(madc::value *, const char *);
void __php_sort(madc::value *);
void __php_rsort(madc::value *);
void __php_array_slice(madc::value *, madc::value *, int64_t, int64_t);
void __php_array_merge(madc::value *, madc::value *);
void __php_array_column(madc::value *, madc::value *, int64_t);
}

namespace php {
inline std::string &trim(std::string &s) { return *__php_trim(&s); }
inline std::string &ltrim(std::string &s) { return *__php_ltrim(&s); }
inline std::string &rtrim(std::string &s) { return *__php_rtrim(&s); }
inline std::string &chop(std::string &s) { return *__php_chop(&s); }
inline std::string &ucfirst(std::string &s) { return *__php_ucfirst(&s); }
inline std::string &lcfirst(std::string &s) { return *__php_lcfirst(&s); }
inline std::string &str_repeat(std::string &s, int64_t count) { return *__php_str_repeat(&s, count); }
inline std::string &str_replace(std::string &search, std::string &replace, std::string &subject) { return *__php_str_replace(&search, &replace, &subject); }
inline std::string &str_pad(std::string &s, int64_t length, std::string &pad) { return *__php_str_pad(&s, length, &pad); }
inline int64_t str_word_count(std::string &s) { return __php_str_word_count(&s); }
inline std::string &nl2br(std::string &s) { return *__php_nl2br(&s); }
inline std::string &str_rot13(std::string &s) { return *__php_str_rot13(&s); }
inline std::string &chunk_split(std::string &s, int64_t chunklen, std::string &separator) { return *__php_chunk_split(&s, chunklen, &separator); }
inline std::string &number_format(std::string &result, int64_t number, std::string &separator) { return *__php_number_format(&result, number, &separator); }
inline std::string &wordwrap(std::string &s, int64_t width, std::string &separator) { return *__php_wordwrap(&s, width, &separator); }
inline void explode(madc::value &out, const char *delim, const char *text) { __php_explode(&out, delim, text); }
inline std::string &implode(std::string &result, const char *glue, madc::value &values) { return *__php_implode(&result, glue, &values); }
inline int64_t count(madc::value &values) { return __php_count(&values); }
inline void array_push(madc::value &values, const char *text) { __php_array_push(&values, text); }
inline void array_push_int(madc::value &values, int64_t value) { __php_array_push_int(&values, value); }
inline void array_push_array(madc::value &values, madc::value &nested) { __php_array_push_array(&values, &nested); }
inline std::string &array_pop(std::string &result, madc::value &values) { return *__php_array_pop(&result, &values); }
inline std::string &array_get(std::string &result, madc::value &values, int64_t index) { return *__php_array_get(&result, &values, index); }
inline int64_t array_get_int(madc::value &values, int64_t index) { return __php_array_get_int(&values, index); }
inline const char *array_get_cstr(madc::value &values, int64_t index) { return __php_array_get_cstr(&values, index); }
inline void array_reverse(madc::value &values) { __php_array_reverse(&values); }
inline int64_t in_array(const char *needle, madc::value &values) { return __php_in_array(needle, &values); }
inline int64_t array_search(const char *needle, madc::value &values) { return __php_array_search(needle, &values); }
inline void array_unique(madc::value &values) { __php_array_unique(&values); }
inline std::string &array_shift(std::string &result, madc::value &values) { return *__php_array_shift(&result, &values); }
inline void array_unshift(madc::value &values, const char *text) { __php_array_unshift(&values, text); }
inline void sort(madc::value &values) { __php_sort(&values); }
inline void rsort(madc::value &values) { __php_rsort(&values); }
inline void array_slice(madc::value &dest, madc::value &src, int64_t offset, int64_t length) { __php_array_slice(&dest, &src, offset, length); }
inline void array_merge(madc::value &dest, madc::value &src) { __php_array_merge(&dest, &src); }
inline void array_column(madc::value &dest, madc::value &src, int64_t column_index) { __php_array_column(&dest, &src, column_index); }
}

#endif

#endif
)EMBED"},
    {"ns_python", R"EMBED(#include <string>
extern "C" {
    std::string *__py_title(std::string *);
    std::string *__py_swapcase(std::string *);
    std::string *__py_center(std::string *, long, const char *);
    std::string *__py_ljust(std::string *, long, const char *);
    std::string *__py_rjust(std::string *, long, const char *);
    std::string *__py_zfill(std::string *, long);
    long __py_count(const char *, const char *);
    long __py_startswith(const char *, const char *);
    long __py_endswith(const char *, const char *);
    long __py_isdigit(const char *);
    long __py_isalpha(const char *);
    long __py_isalnum(const char *);
    long __py_isspace(const char *);
    std::string *__py_replace(std::string *, const char *, const char *);
    std::string *__py_format(std::string *, const char *, array *);
}

namespace python {
    std::string &title(std::string &s) { return *__py_title(&s); }
    std::string &swapcase(std::string &s) { return *__py_swapcase(&s); }
    std::string &center(std::string &s, long width, const char *fill) { return *__py_center(&s, width, fill); }
    std::string &ljust(std::string &s, long width, const char *fill) { return *__py_ljust(&s, width, fill); }
    std::string &rjust(std::string &s, long width, const char *fill) { return *__py_rjust(&s, width, fill); }
    std::string &zfill(std::string &s, long width) { return *__py_zfill(&s, width); }
    long count(const char *haystack, const char *needle) { return __py_count(haystack, needle); }
    long startswith(const char *text, const char *prefix) { return __py_startswith(text, prefix); }
    long endswith(const char *text, const char *suffix) { return __py_endswith(text, suffix); }
    long isdigit(const char *text) { return __py_isdigit(text); }
    long isalpha(const char *text) { return __py_isalpha(text); }
    long isalnum(const char *text) { return __py_isalnum(text); }
    long isspace(const char *text) { return __py_isspace(text); }
    std::string &replace(std::string &s, const char *old_text, const char *new_text) { return *__py_replace(&s, old_text, new_text); }
    std::string &format(std::string &result, const char *fmt, array &args) { return *__py_format(&result, fmt, &args); }
}
)EMBED"},
    {"ns_python.h", R"EMBED(#ifndef MADC_NS_PYTHON_H
#define MADC_NS_PYTHON_H

#ifdef __cplusplus

#include <cstdint>
#include <string>
#include "datadef.h"

extern "C" {
std::string *__py_title(std::string *);
std::string *__py_swapcase(std::string *);
std::string *__py_center(std::string *, int64_t, const char *);
std::string *__py_ljust(std::string *, int64_t, const char *);
std::string *__py_rjust(std::string *, int64_t, const char *);
std::string *__py_zfill(std::string *, int64_t);
int64_t __py_count(const char *, const char *);
int64_t __py_startswith(const char *, const char *);
int64_t __py_endswith(const char *, const char *);
int64_t __py_isdigit(const char *);
int64_t __py_isalpha(const char *);
int64_t __py_isalnum(const char *);
int64_t __py_isspace(const char *);
std::string *__py_replace(std::string *, const char *, const char *);
std::string *__py_format(std::string *, const char *, madc::value *);
}

namespace python {
inline std::string &title(std::string &s) { return *__py_title(&s); }
inline std::string &swapcase(std::string &s) { return *__py_swapcase(&s); }
inline std::string &center(std::string &s, int64_t width, const char *fill) { return *__py_center(&s, width, fill); }
inline std::string &ljust(std::string &s, int64_t width, const char *fill) { return *__py_ljust(&s, width, fill); }
inline std::string &rjust(std::string &s, int64_t width, const char *fill) { return *__py_rjust(&s, width, fill); }
inline std::string &zfill(std::string &s, int64_t width) { return *__py_zfill(&s, width); }
inline int64_t count(const char *haystack, const char *needle) { return __py_count(haystack, needle); }
inline int64_t startswith(const char *text, const char *prefix) { return __py_startswith(text, prefix); }
inline int64_t endswith(const char *text, const char *suffix) { return __py_endswith(text, suffix); }
inline int64_t isdigit(const char *text) { return __py_isdigit(text); }
inline int64_t isalpha(const char *text) { return __py_isalpha(text); }
inline int64_t isalnum(const char *text) { return __py_isalnum(text); }
inline int64_t isspace(const char *text) { return __py_isspace(text); }
inline std::string &replace(std::string &s, const char *old_text, const char *new_text) { return *__py_replace(&s, old_text, new_text); }
inline std::string &format(std::string &result, const char *fmt, madc::value &args) { return *__py_format(&result, fmt, &args); }
}

#endif

#endif
)EMBED"},
    {"ns_ruby", R"EMBED(#include <string>
extern "C" {
    std::string *__rb_squeeze(std::string *);
    std::string *__rb_tr(std::string *, const char *, const char *);
    void __rb_chars(array *, const char *);
    std::string *__rb_capitalize(std::string *);
    std::string *__rb_delete(std::string *, const char *);
    long __rb_count(const char *, const char *);
    long __rb_include(const char *, const char *);
    std::string *__rb_gsub(std::string *, const char *, const char *);
    std::string *__rb_sub(std::string *, const char *, const char *);
    void __rb_rotate(array *, long);
    void __rb_compact(array *);
    void __rb_flatten(array *, const char *);
}

namespace ruby {
    std::string &squeeze(std::string &s) { return *__rb_squeeze(&s); }
    std::string &tr(std::string &s, const char *from, const char *to) { return *__rb_tr(&s, from, to); }
    void chars(array &out, const char *text) { __rb_chars(&out, text); }
    std::string &capitalize(std::string &s) { return *__rb_capitalize(&s); }
    std::string &delete(std::string &s, const char *chars) { return *__rb_delete(&s, chars); }
    long count(const char *text, const char *chars) { return __rb_count(text, chars); }
    long include(const char *text, const char *substr) { return __rb_include(text, substr); }
    std::string &gsub(std::string &s, const char *pattern, const char *replacement) { return *__rb_gsub(&s, pattern, replacement); }
    std::string &sub(std::string &s, const char *pattern, const char *replacement) { return *__rb_sub(&s, pattern, replacement); }
    void rotate(array &values, long n) { __rb_rotate(&values, n); }
    void compact(array &values) { __rb_compact(&values); }
    void flatten(array &values, const char *text) { __rb_flatten(&values, text); }
}
)EMBED"},
    {"ns_ruby.h", R"EMBED(#ifndef MADC_NS_RUBY_H
#define MADC_NS_RUBY_H

#ifdef __cplusplus

#include <cstdint>
#include <string>
#include "datadef.h"

extern "C" {
std::string *__rb_squeeze(std::string *);
std::string *__rb_tr(std::string *, const char *, const char *);
void __rb_chars(madc::value *, const char *);
std::string *__rb_capitalize(std::string *);
std::string *__rb_delete(std::string *, const char *);
int64_t __rb_count(const char *, const char *);
int64_t __rb_include(const char *, const char *);
std::string *__rb_gsub(std::string *, const char *, const char *);
std::string *__rb_sub(std::string *, const char *, const char *);
void __rb_rotate(madc::value *, int64_t);
void __rb_compact(madc::value *);
void __rb_flatten(madc::value *, const char *);
}

namespace ruby {
inline std::string &squeeze(std::string &s) { return *__rb_squeeze(&s); }
inline std::string &tr(std::string &s, const char *from, const char *to) { return *__rb_tr(&s, from, to); }
inline void chars(madc::value &out, const char *text) { __rb_chars(&out, text); }
inline std::string &capitalize(std::string &s) { return *__rb_capitalize(&s); }
inline std::string &delete_chars(std::string &s, const char *chars) { return *__rb_delete(&s, chars); }
inline int64_t count(const char *text, const char *chars) { return __rb_count(text, chars); }
inline int64_t include(const char *text, const char *substr) { return __rb_include(text, substr); }
inline std::string &gsub(std::string &s, const char *pattern, const char *replacement) { return *__rb_gsub(&s, pattern, replacement); }
inline std::string &sub(std::string &s, const char *pattern, const char *replacement) { return *__rb_sub(&s, pattern, replacement); }
inline void rotate(madc::value &values, int64_t n) { __rb_rotate(&values, n); }
inline void compact(madc::value &values) { __rb_compact(&values); }
inline void flatten(madc::value &values, const char *text) { __rb_flatten(&values, text); }
}

#endif

#endif
)EMBED"},
    {"ns_rust", R"EMBED(#include <string>
extern "C" {
    long __rust_contains(const char *, const char *);
    long __rust_starts_with(const char *, const char *);
    long __rust_ends_with(const char *, const char *);
    std::string *__rust_trim(std::string *);
    std::string *__rust_trim_start(std::string *);
    std::string *__rust_trim_end(std::string *);
    std::string *__rust_replace(std::string *, const char *, const char *);
    std::string *__rust_repeat(std::string *, long);
    long __rust_len(const char *);
    long __rust_is_empty(const char *);
    void __rust_split(array *, const char *, const char *);
    void __rust_split_whitespace(array *, const char *);
    std::string *__rust_join(std::string *, array *, const char *);
    std::string *__rust_first(std::string *, array *);
    std::string *__rust_last(std::string *, array *);
    std::string *__rust_get(std::string *, array *, long);
    void __rust_push(array *, const char *);
    std::string *__rust_pop(std::string *, array *);
}

namespace rust {
    long contains(const char *text, const char *needle) { return __rust_contains(text, needle); }
    long starts_with(const char *text, const char *prefix) { return __rust_starts_with(text, prefix); }
    long ends_with(const char *text, const char *suffix) { return __rust_ends_with(text, suffix); }
    std::string &trim(std::string &s) { return *__rust_trim(&s); }
    std::string &trim_start(std::string &s) { return *__rust_trim_start(&s); }
    std::string &trim_end(std::string &s) { return *__rust_trim_end(&s); }
    std::string &replace(std::string &s, const char *from, const char *to) { return *__rust_replace(&s, from, to); }
    std::string &repeat(std::string &s, long count) { return *__rust_repeat(&s, count); }
    long len(const char *text) { return __rust_len(text); }
    long is_empty(const char *text) { return __rust_is_empty(text); }
    void split(array &out, const char *text, const char *delim) { __rust_split(&out, text, delim); }
    void split_whitespace(array &out, const char *text) { __rust_split_whitespace(&out, text); }
    std::string &join(std::string &result, array &values, const char *sep) { return *__rust_join(&result, &values, sep); }
    std::string &first(std::string &result, array &values) { return *__rust_first(&result, &values); }
    std::string &last(std::string &result, array &values) { return *__rust_last(&result, &values); }
    std::string &get(std::string &result, array &values, long idx) { return *__rust_get(&result, &values, idx); }
    void push(array &values, const char *value) { __rust_push(&values, value); }
    std::string &pop(std::string &result, array &values) { return *__rust_pop(&result, &values); }
}
)EMBED"},
    {"ns_rust.h", R"EMBED(#ifndef MADC_NS_RUST_H
#define MADC_NS_RUST_H

#ifdef __cplusplus

#include <cstdint>
#include <string>
#include "datadef.h"

extern "C" {
int64_t __rust_contains(const char *, const char *);
int64_t __rust_starts_with(const char *, const char *);
int64_t __rust_ends_with(const char *, const char *);
std::string *__rust_trim(std::string *);
std::string *__rust_trim_start(std::string *);
std::string *__rust_trim_end(std::string *);
std::string *__rust_replace(std::string *, const char *, const char *);
std::string *__rust_repeat(std::string *, int64_t);
int64_t __rust_len(const char *);
int64_t __rust_is_empty(const char *);
void __rust_split(madc::value *, const char *, const char *);
void __rust_split_whitespace(madc::value *, const char *);
std::string *__rust_join(std::string *, madc::value *, const char *);
std::string *__rust_first(std::string *, madc::value *);
std::string *__rust_last(std::string *, madc::value *);
std::string *__rust_get(std::string *, madc::value *, int64_t);
void __rust_push(madc::value *, const char *);
std::string *__rust_pop(std::string *, madc::value *);
}

namespace rust {
inline int64_t contains(const char *text, const char *needle) { return __rust_contains(text, needle); }
inline int64_t starts_with(const char *text, const char *prefix) { return __rust_starts_with(text, prefix); }
inline int64_t ends_with(const char *text, const char *suffix) { return __rust_ends_with(text, suffix); }
inline std::string &trim(std::string &s) { return *__rust_trim(&s); }
inline std::string &trim_start(std::string &s) { return *__rust_trim_start(&s); }
inline std::string &trim_end(std::string &s) { return *__rust_trim_end(&s); }
inline std::string &replace(std::string &s, const char *from, const char *to) { return *__rust_replace(&s, from, to); }
inline std::string &repeat(std::string &s, int64_t count) { return *__rust_repeat(&s, count); }
inline int64_t len(const char *text) { return __rust_len(text); }
inline int64_t is_empty(const char *text) { return __rust_is_empty(text); }
inline void split(madc::value &out, const char *text, const char *delim) { __rust_split(&out, text, delim); }
inline void split_whitespace(madc::value &out, const char *text) { __rust_split_whitespace(&out, text); }
inline std::string &join(std::string &result, madc::value &values, const char *sep) { return *__rust_join(&result, &values, sep); }
inline std::string &first(std::string &result, madc::value &values) { return *__rust_first(&result, &values); }
inline std::string &last(std::string &result, madc::value &values) { return *__rust_last(&result, &values); }
inline std::string &get(std::string &result, madc::value &values, int64_t idx) { return *__rust_get(&result, &values, idx); }
inline void push(madc::value &values, const char *value) { __rust_push(&values, value); }
inline std::string &pop(std::string &result, madc::value &values) { return *__rust_pop(&result, &values); }
}

#endif

#endif
)EMBED"},
    {"stdarg.h", R"EMBED(// madc embedded stdarg.h — variadic function support
//
// Matches the x86-64 System V ABI exactly as gcc/c2mir set it up (see
// c2mir's mirc_x86_64_stdarg.h): va_list is the real __va_list_tag[1] struct,
// and the ABI work is done by the compiler intrinsic __builtin_va_start.
//
// The user's
//   va_list ap; va_start(ap, last);
// lowers directly to c2mir's intrinsic __builtin_va_start(ap), which takes the
// va_list alone and derives the named-argument count from the enclosing
// function's signature — exactly c2mir's own mirc_x86_64_stdarg.h idiom.
// (An earlier model primed a hidden function-entry `__va_args` master and
// copied it per use site — `(ap)[0] = (__va_args)[0]` — but that extra
// va_list struct copy left reg_save_area mis-set in large/complex frames,
// corrupting the list; invoking the intrinsic on the user's own va_list
// avoids the copy and the corruption.)

// ONE definition: the compiler owns the type (Program::builtin_va_list_type —
// the SysV struct __madc_va_list_tag[1] singleton, resolved from the spelling
// __builtin_va_list). This header only aliases it, exactly like real gcc
// stdarg.h; the CIR emitter synthesizes the struct+typedef C when a module
// references the type.
typedef __builtin_va_list va_list;

// GCC's name for the same underlying va_list ABI type. Real system headers
// (e.g. glibc <wchar.h> under `#define __need___va_list`) reference it and then
// do `typedef __gnuc_va_list va_list;`.
typedef __builtin_va_list __gnuc_va_list;

#define va_start(ap, last) __builtin_va_start(ap)
#define va_end(ap) ((void)(ap))
#define va_copy(dest, src) ((dest)[0] = (src)[0])

// va_list is now the real ABI struct, so the v*printf family resolve to the
// real libc functions (which take a va_list) — not the old __madc_* helpers
// that unpacked a custom int64_t[] buffer.
int vsprintf(char *, const char *, va_list);
int vsnprintf(char *, unsigned long, const char *, va_list);
int vfprintf(void *, const char *, va_list);
int vprintf(const char *, va_list);
)EMBED"},
    {"stdbool.h", R"EMBED(// madc embedded stdbool.h

#define bool _Bool
#define true 1
#define false 0
#define __bool_true_false_are_defined 1
)EMBED"},
    {"stddef.h", R"EMBED(// madc embedded stddef.h — standard definitions
// size_t and ptrdiff_t are already native madc types via typedef
// This header provides NULL, offsetof, and max_align_t

#ifndef __MADC_STDDEF_H
#define __MADC_STDDEF_H 1

#ifndef NULL
#define NULL ((void *)0)
#endif

#define offsetof(type, member) ((unsigned long)&((type *)0)->member)

typedef long ptrdiff_t;
typedef unsigned long size_t;
typedef int wchar_t;

#endif
)EMBED"},
    {"stdint.h", R"EMBED(// madc embedded stdint.h — exact-width integer types
// Note: int8_t through uint64_t are native madc types
// This header provides the min/max constants for completeness

#define INT8_MIN    -128
#define INT8_MAX    127
#define UINT8_MAX   255
#define INT16_MIN   -32768
#define INT16_MAX   32767
#define UINT16_MAX  65535
#define INT32_MIN   -2147483648
#define INT32_MAX   2147483647
#define UINT32_MAX  4294967295
#define INT64_MIN   -9223372036854775807
#define INT64_MAX   9223372036854775807
#define UINT64_MAX  0xFFFFFFFFFFFFFFFF
#define SIZE_MAX    0xFFFFFFFFFFFFFFFF
#define INTMAX_MIN  -9223372036854775807
#define INTMAX_MAX  9223372036854775807
#define UINTMAX_MAX 0xFFFFFFFFFFFFFFFF
#define PTRDIFF_MIN -9223372036854775807
#define PTRDIFF_MAX 9223372036854775807

typedef long int intptr_t;
typedef unsigned long int uintptr_t;
)EMBED"}
};

const std::string *find_embedded_header(const std::string &name)
{
    auto it = embedded_headers.find(name);
    if ( it != embedded_headers.end() )
        return &it->second;
    return nullptr;
}
