// madc_anode.h — Integer codes for Gecko abstract node names.
//
// Registered via gp_set_anode_code() at grammar build time.
// Every gp_tree_node's `aux` field holds the code for its anode name.
// Use an_code(node) for O(1) dispatch instead of strcmp on anode names.

#ifndef __MADC_ANODE_H
#define __MADC_ANODE_H 1

enum AnodeCode {
    AN_NONE               = 0,
    AN_ABS_ARRAY          = 1,
    AN_ABS_FUNC           = 2,
    AN_ABS_PTR            = 3,
    AN_ABS_REF            = 4,
    AN_ABS_VLA            = 5,
    AN_ACCESS             = 6,
    AN_ADD                = 7,
    AN_ADD_ASSIGN         = 8,
    AN_ADDROF             = 9,
    AN_ALIGNOF_TYPE       = 10,
    AN_ARG_LIST           = 11,
    AN_ARRAY_DECL         = 12,
    AN_ARROW_MEMBER       = 13,
    AN_ASSIGN             = 14,
    AN_BAND_ASSIGN        = 15,
    AN_BITAND             = 16,
    AN_BITFIELD           = 17,
    AN_BITOR              = 18,
    AN_BITXOR             = 19,
    AN_BLOCK              = 20,
    AN_BNOT               = 21,
    AN_BOR_ASSIGN         = 22,
    AN_BREAK              = 23,
    AN_BSL                = 24,
    AN_BSL_ASSIGN         = 25,
    AN_BSR                = 26,
    AN_BSR_ASSIGN         = 27,
    AN_CALL               = 28,
    AN_CASE               = 29,
    AN_CASE_RANGE         = 30,
    AN_CAST               = 31,
    AN_CATCH              = 32,
    AN_CATCH_ALL          = 33,
    AN_CATCH_LIST         = 34,
    AN_CLASS_BODY         = 35,
    AN_CLASS_DEF          = 36,
    AN_CLASS_INHERIT      = 37,
    AN_COL_ASSIGN         = 38,
    AN_COMMA              = 39,
    AN_COMPOUND_LIT       = 40,
    AN_CONTINUE           = 41,
    AN_CTOR               = 42,
    AN_CTOR_DECL          = 43,
    AN_DECL               = 44,
    AN_DECL_LIST          = 45,
    AN_DEFAULT            = 46,
    AN_DEFER              = 47,
    AN_DELETE             = 48,
    AN_DELETE_ARRAY       = 49,
    AN_DEREF              = 50,
    AN_DESIG_CHAIN        = 51,
    AN_DESIG_INIT         = 52,
    AN_DIV                = 53,
    AN_DIV_ASSIGN         = 54,
    AN_DO_WHILE           = 55,
    AN_DTOR               = 56,
    AN_EMPTY_INIT         = 57,
    AN_ENUM_ASSIGN        = 58,
    AN_ENUM_DEF           = 59,
    AN_ENUM_LIST          = 60,
    AN_ENUM_REF           = 61,
    AN_EQ                 = 62,
    AN_EQ3                = 63,
    AN_EXPR_STMT          = 64,
    AN_FIELD_LIST         = 65,
    AN_FOR                = 66,
    AN_FOR_DECL           = 67,
    AN_FOR_RANGE          = 68,
    AN_FUNC_DECL          = 69,
    AN_FUNC_DEF           = 70,
    AN_FUNCALL_OP         = 71,
    AN_GE                 = 72,
    AN_GOTO               = 73,
    AN_GOTO_INDIRECT      = 74,
    AN_GT                 = 75,
    AN_IDENT_LIST         = 76,
    AN_IF                 = 77,
    AN_IF_ELSE            = 78,
    AN_INDEX_DESIG        = 79,
    AN_INIT_DECL          = 80,
    AN_INIT_LIST          = 81,
    AN_INIT_SEQ           = 82,
    AN_LABEL              = 83,
    AN_LAND               = 84,
    AN_LE                 = 85,
    AN_LIST_TYPE          = 86,
    AN_LNOT               = 87,
    AN_LOR                = 88,
    AN_LT                 = 89,
    AN_MAP_TYPE           = 90,
    AN_MATCH              = 91,
    AN_MATCH_ARM          = 92,
    AN_MATCH_ARMS         = 93,
    AN_MATCH_PATS         = 94,
    AN_MATCH_WILD         = 95,
    AN_MEMBER             = 96,
    AN_MEMBER_DESIG       = 97,
    AN_METHOD             = 98,
    AN_METHOD_PROTO       = 99,
    AN_MOD                = 100,
    AN_MOD_ASSIGN         = 101,
    AN_MUL                = 102,
    AN_MUL_ASSIGN         = 103,
    AN_NAME               = 104,
    AN_NAMESPACE_DEF      = 105,
    AN_NE                 = 106,
    AN_NEG                = 107,
    AN_NEW_CTOR           = 108,
    AN_NEW_PLAIN          = 109,
    AN_NS_CALL            = 110,
    AN_NS_NAME            = 111,
    AN_OPER_METHOD        = 112,
    AN_PARAM              = 113,
    AN_PARAM_LIST         = 114,
    AN_PARAM_VA           = 115,
    AN_PAREN              = 116,
    AN_POS                = 117,
    AN_POST_DEC           = 118,
    AN_POST_INC           = 119,
    AN_PRE_DEC            = 120,
    AN_PRE_INC            = 121,
    AN_PREFER             = 122,
    AN_PTR_DECL           = 123,
    AN_QUAL               = 124,
    AN_QUAL_LIST          = 125,
    AN_REF_DECL           = 126,
    AN_RETURN_MULTI       = 127,
    AN_RETURN_VAL         = 128,
    AN_SET_TYPE           = 129,
    AN_SIZEOF_EXPR        = 130,
    AN_SIZEOF_TYPE        = 131,
    AN_STAR               = 132,
    AN_STARS              = 133,
    AN_STMT_LIST          = 134,
    AN_STRUCT_BODY        = 135,
    AN_STRUCT_DEF         = 136,
    AN_STRUCT_FIELD       = 137,
    AN_STRUCT_REF         = 138,
    AN_SUB                = 139,
    AN_SUB_ASSIGN         = 140,
    AN_SUBSCRIPT          = 141,
    AN_SUBSCRIPT_OP       = 142,
    AN_SWITCH             = 143,
    AN_TERNARY            = 144,
    AN_THREE_WAY          = 145,
    AN_THROW              = 146,
    AN_THROW_EXPR         = 147,
    AN_TRY                = 148,
    AN_TU                 = 149,
    AN_TYPE_NAME          = 150,
    AN_USING_DECL         = 151,
    AN_USING_NS           = 152,
    AN_VECTOR_TYPE        = 153,
    AN_VLA_DECL           = 154,
    AN_WHILE              = 155,
    AN_XOR_ASSIGN         = 156,
    AN_TYPEOF_EXPR        = 157,
    AN_TYPEOF_TYPE        = 158,
    AN_VA_ARG             = 159,
    AN_STATIC_ASSERT      = 160,
    AN_GNU_FIELD_DESIG    = 161,
    AN_RANGE_DESIG        = 162,
    AN_STMT_EXPR          = 163,
    AN_LABEL_ADDR         = 164,
    AN_ALIGNOF_EXPR       = 165,
    AN_KR_FUNC_DEF        = 166,
    AN_KR_DECL_LIST       = 167,
};

// O(1) anode code lookup — returns AN_NONE for non-anode nodes
static inline int an_code(struct gp_tree_node *node)
{
    if (!node || node->type != GP_ANODE) return AN_NONE;
    return node->aux;
}

// O(1) anode check — replaces is_anode(node, "name")
static inline bool is_an(struct gp_tree_node *node, int code)
{
    return node && node->type == GP_ANODE && node->aux == code;
}

#endif // __MADC_ANODE_H
