// AUTO-GENERATED by scripts/gen_precompiled_headers.sh — do not edit
// Pre-compiled headers in .madh format (post-lexer token stream, compressed)
#include <cstdint>
#include <cstddef>
#include <map>
#include <string>

struct PrecompiledHeader {
    const uint8_t *data;
    size_t size;
};


static std::map<std::string, PrecompiledHeader> precompiled_headers = {

};

const PrecompiledHeader *find_precompiled_header(const std::string &name)
{
    auto it = precompiled_headers.find(name);
    if (it != precompiled_headers.end())
        return &it->second;
    return nullptr;
}
